
.TH "GCLOUD_FIREBASE_TEST_ANDROID_LOCALES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud firebase test android locales describe \- describe an Android locale



.SH "SYNOPSIS"
.HP
\f5gcloud firebase test android locales describe\fR \fILOCALE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe an Android locale.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fILOCALE\fR
The locale to describe, found using $ gcloud firebase test android locales list.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
