
.TH "GCLOUD_SOURCE" 1



.SH "NAME"
.HP
gcloud source \- cloud git repository commands



.SH "SYNOPSIS"
.HP
\f5gcloud source\fR \fIGROUP\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

The gcloud source group lets you manipulate git repositories within a Google
Cloud project.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBrepos\fR
Repos command group.
.RE
.sp
