
.TH "GCLOUD_SQL_SSL\-CERTS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud sql ssl\-certs describe \- retrieves information about an SSL cert for a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql ssl\-certs describe\fR \fICOMMON_NAME\fR \fB\-\-instance\fR \fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Retrieves information about an SSL cert for a Cloud SQL instance.



.SH "POSITIONAL ARGUMENTS"

\fICOMMON_NAME\fR
.RS 2m
User supplied name. Constrained to [a\-zA\-Z.\-\fI ]+.


\fR
.RE

.SH "REQUIRED FLAGS"

\fB\-\-instance\fR \fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
.RS 2m
Cloud SQL instance ID.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
