
.TH "GCLOUD_DEPLOYMENT\-MANAGER" 1



.SH "NAME"
.HP
gcloud deployment\-manager \- manage deployments of cloud resources



.SH "SYNOPSIS"
.HP
\f5gcloud deployment\-manager\fR \fIGROUP\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage deployments of cloud resources.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

\fBdeployments\fR
.RS 2m
Commands for Deployment Manager deployments.

.RE
\fBmanifests\fR
.RS 2m
Commands for Deployment Manager manifests.

.RE
\fBoperations\fR
.RS 2m
Commands for Deployment Manager operations.

.RE
\fBresources\fR
.RS 2m
Commands for Deployment Manager resources.

.RE
\fBtypes\fR
.RS 2m
Commands for Deployment Manager types.
.RE
