
.TH "GCLOUD_CONTAINER_NODE\-POOLS" 1



.SH "NAME"
.HP
gcloud container node\-pools \- create and delete operations for Google Container Engine node pools



.SH "SYNOPSIS"
.HP
\f5gcloud container node\-pools\fR \fICOMMAND\fR [\fB\-\-zone\fR\ \fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Create and delete operations for Google Container Engine node pools.



.SH "FLAGS"

\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 2m
The compute zone (e.g. us\-central1\-a) for the cluster


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBcreate\fR
.RS 2m
Create a node pool in a running cluster.

.RE
\fBdelete\fR
.RS 2m
Delete an existing node pool in a running cluster.

.RE
\fBdescribe\fR
.RS 2m
Describe an existing node pool for a cluster.

.RE
\fBlist\fR
.RS 2m
List existing node pools for a cluster.
.RE
