
.TH "GCLOUD_COMPUTE_TARGET\-HTTP\-PROXIES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute target\-http\-proxies describe \- display detailed information about a target HTTP proxy



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-http\-proxies describe\fR \fINAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute target\-http\-proxies describe\fR displays all data associated
with a target HTTP proxy in a project.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the resource to fetch.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
