
.TH "GCLOUD_APP_INSTANCES" 1



.SH "NAME"
.HP
gcloud app instances \- view and manage your App Engine instances



.SH "SYNOPSIS"
.HP
\f5gcloud app instances\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This set of commands can be used to view and manage your existing App Engine
instances.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBdisable\-debug\fR
.RS 2m
Disables debug mode for an instance.

.RE
\fBenable\-debug\fR
.RS 2m
Enables debug mode for an instance.

.RE
\fBlist\fR
.RS 2m
List the instances affiliated with the current App Engine project.


.RE

.SH "EXAMPLES"

To list your App Engine instances, run:

.RS 2m
$ gcloud app instances list
.RE
