
.TH "GCLOUD_DATAPROC_CLUSTERS_DELETE" 1



.SH "NAME"
.HP
gcloud dataproc clusters delete \- delete a cluster



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc clusters delete\fR \fINAME\fR [\fB\-\-async\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete a cluster.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the cluster to delete.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress and don't wait for the
operation to complete.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To delete a cluster, run:

.RS 2m
$ gcloud dataproc clusters delete my_cluster
.RE
