
.TH "GCLOUD_COMPUTE_TARGET\-VPN\-GATEWAYS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute target\-vpn\-gateways describe \- describe a Google Compute Engine target vpn gateway



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-vpn\-gateways describe\fR \fINAME\fR [\fB\-\-region\fR\ \fIREGION\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute target\-vpn\-gateways describe\fR displays all data associated
with a Google Compute Engine target vpn gateway in a project.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the resource to fetch.


.RE

.SH "FLAGS"

\fB\-\-region\fR \fIREGION\fR
.RS 2m
The region of the resource to fetch. If not specified, you will be prompted to
select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
