
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_UPDATE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts update \- update the metadata of an IAM service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts update\fR \fIIAM\-ACCOUNT\fR [\fB\-\-display\-name\fR\ \fIDISPLAY_NAME\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Update the metadata of an IAM service account.



.SH "POSITIONAL ARGUMENTS"

\fIIAM\-ACCOUNT\fR
.RS 2m
The IAM service account to update.


.RE

.SH "FLAGS"

\fB\-\-display\-name\fR \fIDISPLAY_NAME\fR
.RS 2m
The new textual name to display for the account.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
