
.TH "GCLOUD_DATAPROC_CLUSTERS_DIAGNOSE" 1



.SH "NAME"
.HP
gcloud dataproc clusters diagnose \- run a detailed diagnostic on a cluster



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc clusters diagnose\fR \fINAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Run a detailed diagnostic on a cluster.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the cluster to diagnose.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
