
.TH "GCLOUD_COMPUTE_INSTANCE\-GROUPS_MANAGED_STOP\-AUTOSCALING" 1



.SH "NAME"
.HP
gcloud compute instance\-groups managed stop\-autoscaling \- stop autoscaling a managed instance group



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-groups managed stop\-autoscaling\fR \fINAME\fR [\fB\-\-region\fR=\fIREGION\fR\ |\ \fB\-\-zone\fR=\fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute instance\-groups managed stop\-autoscaling\fR stops
autoscaling a managed instance group. If autoscaling is not enabled for the
managed instance group, this command does nothing and will report an error.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the managed instance group.


.RE

.SH "FLAGS"

At most one of these may be specified:

\fB\-\-region\fR=\fIREGION\fR
.RS 2m
The region of the managed instance group to operate on. If not specified, you
will be prompted to select a region.

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

.RE
\fB\-\-zone\fR=\fIZONE\fR
.RS 2m
The zone of the managed instance group to operate on. If not specified, you will
be prompted to select a zone.

A list of zones can be fetched by running:

.RS 2m
$ gcloud compute zones list
.RE


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
