
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_DELETE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts delete \- delete a service account from a project



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts delete\fR \fIIAM\-ACCOUNT\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete a service account from a project.



.SH "POSITIONAL ARGUMENTS"

\fIIAM\-ACCOUNT\fR
.RS 2m
The service account to delete.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To delete an service account from your project, run:

.RS 2m
$ gcloud iam service\-accounts delete my\-iam\-account@somedomain.com
.RE
