
.TH "GCLOUD_COMPUTE_SSL\-CERTIFICATES_CREATE" 1



.SH "NAME"
.HP
gcloud compute ssl\-certificates create \- create a Google Compute Engine SSL certificate



.SH "SYNOPSIS"
.HP
\f5gcloud compute ssl\-certificates create\fR \fINAME\fR \fB\-\-certificate\fR \fILOCAL_FILE_PATH\fR \fB\-\-private\-key\fR \fILOCAL_FILE_PATH\fR [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute ssl\-certificates create\fR is used to create SSL certificates
which can be used to configure a target HTTPS proxy. An SSL certificate consists
of a certificate and private key. The private key is encrypted before it is
stored.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the SSL certificate.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-certificate\fR \fILOCAL_FILE_PATH\fR
.RS 2m
The path to a local certificate file. The certificate must be in PEM format. The
certificate chain must be no greater than 5 certs long. The chain must include
at least one intermediate cert.

.RE
\fB\-\-private\-key\fR \fILOCAL_FILE_PATH\fR
.RS 2m
The path to a local private key file. The private key must be in PEM format and
must use RSA or ECDSA encryption.


.RE

.SH "OPTIONAL FLAGS"

\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 2m
An optional, textual description for the SSL certificate.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
