
.TH "GCLOUD_COMPUTE_SNAPSHOTS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute snapshots describe \- describe a Google Compute Engine snapshot



.SH "SYNOPSIS"
.HP
\f5gcloud compute snapshots describe\fR \fINAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute snapshots describe\fR displays all data associated with a
Google Compute Engine snapshot in a project.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the resource to fetch.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
