
.TH "GCLOUD_COMPUTE_VPN\-TUNNELS" 1



.SH "NAME"
.HP
gcloud compute vpn\-tunnels \- read and manipulate Google Compute Engine VPN Tunnels



.SH "SYNOPSIS"
.HP
\f5gcloud compute vpn\-tunnels\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Read and manipulate Google Compute Engine VPN Tunnels.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBcreate\fR
.RS 2m
Create a VPN tunnel.

.RE
\fBdelete\fR
.RS 2m
Delete vpn tunnels.

.RE
\fBdescribe\fR
.RS 2m
Describe a Google Compute Engine vpn tunnel.

.RE
\fBlist\fR
.RS 2m
List Google Compute Engine VPN tunnels.
.RE
