
.TH "GCLOUD_PREVIEW" 1



.SH "NAME"
.HP
gcloud preview \- preview versions of gcloud commands



.SH "SYNOPSIS"
.HP
\f5gcloud preview\fR \fIGROUP\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(PREVIEW)\fR Preview versions of gcloud commands.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

\fBdatastore\fR
.RS 2m
\fB(PREVIEW)\fR Manage your Cloud Datastore.


.RE

.SH "NOTES"

This command is currently in DEVELOPER PREVIEW and may change without notice.

