
.TH "GCLOUD_DNS_MANAGED\-ZONES" 1



.SH "NAME"
.HP
gcloud dns managed\-zones \- manage your Cloud DNS managed\-zones



.SH "SYNOPSIS"
.HP
\f5gcloud dns managed\-zones\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage your Cloud DNS managed\-zones.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBcreate\fR
.RS 2m
Create a Cloud DNS managed\-zone.

.RE
\fBdelete\fR
.RS 2m
Delete an empty Cloud DNS managed\-zone.

.RE
\fBdescribe\fR
.RS 2m
View the details of a Cloud DNS managed\-zone.

.RE
\fBlist\fR
.RS 2m
View the list of all your managed\-zones.


.RE

.SH "EXAMPLES"

To create a managed\-zone, run:

.RS 2m
$ gcloud dns managed\-zones create my_zone \-\-description="My Zone" \e
    \-\-dns\-name="my.zone.com."
.RE

To delete a managed\-zone, run:

.RS 2m
$ gcloud dns managed\-zones delete my_zone
.RE

To view the details of a managed\-zone, run:

.RS 2m
$ gcloud dns managed\-zones describe my_zone
.RE

To see the list of all managed\-zones, run:

.RS 2m
$ gcloud dns managed\-zones list
.RE
