
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_SIGN\-BLOB" 1



.SH "NAME"
.HP
gcloud iam service\-accounts sign\-blob \- sign a blob with a managed service account key



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts sign\-blob\fR \fIINPUT\-FILE\fR \fIOUTPUT\-FILE\fR \fB\-\-iam\-account\fR \fIIAM_ACCOUNT\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command signs a file containing arbitrary binary data (a blob) using a
system\-managed service account key.



.SH "POSITIONAL ARGUMENTS"

\fIINPUT\-FILE\fR
.RS 2m
A path to the blob file to be signed.

.RE
\fIOUTPUT\-FILE\fR
.RS 2m
A path the resulting signed blob will be written to.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-iam\-account\fR \fIIAM_ACCOUNT\fR
.RS 2m
The service account to sign as.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To sign a blob file with a system\-managed service account key, run:

.RS 2m
$ gcloud iam service\-accounts sign\-blob \e
    \-\-iam\-account my\-account@somedomain.com input.bin output.bin
.RE



.SH "SEE ALSO"

For more information on how this command ties into the wider cloud
infrastructure, please see
https://cloud.google.com/appengine/docs/java/appidentity/
