
.TH "GCLOUD_CONFIG_CONFIGURATIONS" 1



.SH "NAME"
.HP
gcloud config configurations \- manage the set of gcloud named configurations



.SH "SYNOPSIS"
.HP
\f5gcloud config configurations\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage the set of gcloud named configurations.

See \f5gcloud topic configurations\fR for an overview of named configurations.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBactivate\fR
.RS 2m
Activates an existing named configuration.

.RE
\fBcreate\fR
.RS 2m
Creates a new named configuration.

.RE
\fBdelete\fR
.RS 2m
Deletes a named configuration.

.RE
\fBdescribe\fR
.RS 2m
Describes a named configuration by listing its properties.

.RE
\fBlist\fR
.RS 2m
Lists existing named configurations.
.RE
