
.TH "GCLOUD_COMPUTE_SSL\-CERTIFICATES_DELETE" 1



.SH "NAME"
.HP
gcloud compute ssl\-certificates delete \- delete Google Compute Engine SSL certificates



.SH "SYNOPSIS"
.HP
\f5gcloud compute ssl\-certificates delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute ssl\-certificates delete\fR deletes one or more Google Compute
Engine SSL certificates. SSL certificates can only be deleted when no other
resources (e.g., target HTTPS proxies) refer to them.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR [\fINAME\fR ...]
.RS 2m
The resources to delete.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
