
.TH "GCLOUD_PROJECTS_UPDATE" 1



.SH "NAME"
.HP
gcloud projects update \- update the name of a project



.SH "SYNOPSIS"
.HP
\f5gcloud projects update\fR \fIPROJECT_ID\fR \fB\-\-name\fR \fINAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Updates the given project with new name.

This command can fail for the following reasons:
.RS 2m
.IP "\(bu" 2m
There is no project with the given ID.
.RE
.RS 2m
.IP "\(bu" 2m
The active account does not have Owner or Editor permissions for the given
project.
.RE



.SH "POSITIONAL ARGUMENTS"

\fIPROJECT_ID\fR
.RS 2m
ID for the project you want to update.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-name\fR \fINAME\fR
.RS 2m
New name for the project.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

The following command updates a project with the ID \f5example\-foo\-bar\-1\fR
to have the name "Foo Bar and Grill":

.RS 2m
$ gcloud projects update example\-foo\-bar\-1 \-\-name="Foo Bar and Grill"
.RE
