
.TH "GCLOUD_APP_VERSIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud app versions describe \- display all data about an existing version



.SH "SYNOPSIS"
.HP
\f5gcloud app versions describe\fR \fIVERSION\fR \fB\-\-service\fR \fISERVICE\fR, \fB\-s\fR \fISERVICE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Display all data about an existing version.



.SH "POSITIONAL ARGUMENTS"

\fIVERSION\fR
.RS 2m
The ID of the version to show.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-service\fR \fISERVICE\fR, \fB\-s\fR \fISERVICE\fR
.RS 2m
The service corresponding to the version to show.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
