
.TH "GCLOUD_COMPUTE_TARGET\-HTTP\-PROXIES_UPDATE" 1



.SH "NAME"
.HP
gcloud compute target\-http\-proxies update \- update a target HTTP proxy



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-http\-proxies update\fR \fINAME\fR \fB\-\-url\-map\fR \fIURL_MAP\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute target\-http\-proxies update\fR is used to change the URL map
of existing target HTTP proxies. A target HTTP proxy is referenced by one or
more forwarding rules which define which packets the proxy is responsible for
routing. The target HTTP proxy in turn points to a URL map that defines the
rules for routing the requests. The URL map's job is to map URLs to backend
services which handle the actual requests.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the target HTTP proxy.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-url\-map\fR \fIURL_MAP\fR
.RS 2m
A reference to a URL map resource that will define the mapping of URLs to
backend services. The URL map must exist and cannot be deleted while referenced
by a target HTTP proxy.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
