
.TH "GCLOUD_FIREBASE_TEST" 1



.SH "NAME"
.HP
gcloud firebase test \- interact with Firebase Test Lab



.SH "SYNOPSIS"
.HP
\f5gcloud firebase test\fR \fIGROUP\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Explore devices and OS versions available as test targets, run tests, monitor
test progress, and view detailed test results in the Firebase console.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBandroid\fR
Command group for Android application testing.
.RE
.sp
