
.TH "GCLOUD_SQL_FLAGS_LIST" 1



.SH "NAME"
.HP
gcloud sql flags list \- lists customizable MySQL flags for Google Cloud SQL instances



.SH "SYNOPSIS"
.HP
\f5gcloud sql flags list\fR [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

Lists customizable MySQL flags for Google Cloud SQL instances.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
