
.TH "GCLOUD_SERVICE\-MANAGEMENT_UNDELETE" 1



.SH "NAME"
.HP
gcloud service\-management undelete \- undeletes a service configuration given a service name



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management undelete\fR \fISERVICE\fR [\fB\-\-async\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Note: This command is effective for up to 30 days after a service configuration
has been marked for deletion.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICE\fR
The name of the service to undelete.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress and don't wait for the
operation to complete.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
