
.TH "GCLOUD_IAM" 1



.SH "NAME"
.HP
gcloud iam \- manage IAM service accounts and keys



.SH "SYNOPSIS"
.HP
\f5gcloud iam\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage IAM service accounts and keys.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

\fBservice\-accounts\fR
.RS 2m
Create and manipulate service accounts.


.RE

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBlist\-grantable\-roles\fR
.RS 2m
List IAM grantable roles for a resource.
.RE
