
.TH "GCLOUD_PROJECTS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud projects describe \- show metadata for a project



.SH "SYNOPSIS"
.HP
\f5gcloud projects describe\fR \fIPROJECT_ID\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Shows metadata for a project given a valid project ID.

This command can fail for the following reasons:
.RS 2m
.IP "\(bu" 2m
The project specified does not exist.
.RE
.RS 2m
.IP "\(bu" 2m
The active account does not have permission to access the given project.
.RE



.SH "POSITIONAL ARGUMENTS"

\fIPROJECT_ID\fR
.RS 2m
ID for the project you want to describe.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

The following command prints metadata for a project with the ID
\f5example\-foo\-bar\-1\fR:

.RS 2m
$ gcloud projects describe example\-foo\-bar\-1
.RE
