
.TH "GCLOUD_AUTH_LIST" 1



.SH "NAME"
.HP
gcloud auth list \- lists credentialed accounts



.SH "SYNOPSIS"
.HP
\f5gcloud auth list\fR [\fB\-\-filter\-account\fR\ \fIFILTER_ACCOUNT\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Lists accounts whose credentials have been obtained using \f5gcloud init\fR,
\f5gcloud auth login\fR and \f5gcloud auth activate\-service\-account\fR, and
shows which account is active. The active account is used by gcloud and other
Cloud SDK tools to access Google Cloud Platform.



.SH "FLAGS"

\fB\-\-filter\-account\fR \fIFILTER_ACCOUNT\fR
.RS 2m
List only the specified account.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
