
.TH "GCLOUD_SQL_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud sql operations describe \- retrieves information about a Cloud SQL instance operation



.SH "SYNOPSIS"
.HP
\f5gcloud sql operations describe\fR \fIOPERATION\fR \fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Retrieves information about a Cloud SQL instance operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
Name that uniquely identifies the operation.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
