
.TH "GCLOUD_DATAPROC_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud dataproc operations describe \- view the details of an operation



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc operations describe\fR \fIOPERATION\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

View the details of an operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
The ID of the operation to describe.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To view the details of an operation, run:

.RS 2m
$ gcloud dataproc operations describe operation_id
.RE
