
.TH "GCLOUD_DATAPROC_JOBS_DELETE" 1



.SH "NAME"
.HP
gcloud dataproc jobs delete \- delete the record of an inactive job



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc jobs delete\fR \fIJOB_ID\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete the record of an inactive job.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB_ID\fR
The ID of the job to delete.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To delete the record of a job, run:

.RS 2m
$ gcloud dataproc jobs delete job_id
.RE
