
.TH "GCLOUD_PREVIEW_DATASTORE_CREATE\-INDEXES" 1



.SH "NAME"
.HP
gcloud preview datastore create\-indexes \- create new datastore indexes based on your local index configuration



.SH "SYNOPSIS"
.HP
\f5gcloud preview datastore create\-indexes\fR \fIINDEX_FILE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(PREVIEW)\fR \fB(DEPRECATED)\fR Create new datastore indexes based on your
local index configuration.

This is now available in GA and preview has been deprecated. Please use the
\f5gcloud datastore\fR commands instead.


This command creates new datastore indexes based on your local index
configuration. Any indexes in your index file that do not exist will be created.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINDEX_FILE\fR
The path to your index.yaml file.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To create new indexes based on your local configuration, run:

.RS 2m
$ gcloud preview datastore create\-indexes ~/myapp/index.yaml
.RE



.SH "NOTES"

This command is currently in DEVELOPER PREVIEW and may change without notice.

