
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts describe \- show metadata for a service account from a project



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts describe\fR \fIIAM\-ACCOUNT\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command shows metadata for a service account.

This call can fail for the following reasons:
.RS 2m
.IP "\(bu" 2m
The service account specified does not exist.
.RE
.RS 2m
.IP "\(bu" 2m
The active user does not have permission to access the given service account.
.RE



.SH "POSITIONAL ARGUMENTS"

\fIIAM\-ACCOUNT\fR
.RS 2m
The service account to describe.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To print metadata for a service account from your project, run:

.RS 2m
$ gcloud iam service\-accounts describe my\-iam\-account@somedomain.com
.RE
