
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_KEYS_DELETE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts keys delete \- delete a user\-managed key from a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts keys delete\fR \fIKEY\-ID\fR \fB\-\-iam\-account\fR \fIIAM_ACCOUNT\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete a user\-managed key from a service account.



.SH "POSITIONAL ARGUMENTS"

\fIKEY\-ID\fR
.RS 2m
The key to delete.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-iam\-account\fR \fIIAM_ACCOUNT\fR
.RS 2m
The service account whose key to delete.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
