
.TH "GCLOUD_SQL_BACKUPS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud sql backups describe \- retrieves information about a backup



.SH "SYNOPSIS"
.HP
\f5gcloud sql backups describe\fR \fIDUE_TIME\fR \fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Retrieves information about a backup.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIDUE_TIME\fR
The time when this run is due to start in RFC 3339 format, for example
2012\-11\-15T16:19:00.094Z.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-instance\fR=\fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
