
.TH "GCLOUD_PREVIEW_APP_LOGS" 1



.SH "NAME"
.HP
gcloud preview app logs \- manage your App Engine logs



.SH "SYNOPSIS"
.HP
\f5gcloud preview app logs\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

\fB(PREVIEW)\fR This set of commands can be used to view your existing App
Engine logs.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBread\fR
.RS 2m
\fB(PREVIEW)\fR Reads log entries for the current App Engine app.


.RE

.SH "EXAMPLES"

To read the logs for the current App Engine project, run:

.RS 2m
$ gcloud preview app logs read
.RE



.SH "NOTES"

This command is currently in DEVELOPER PREVIEW and may change without notice.

