
.TH "GCLOUD_PREVIEW_APP_RUN" 1



.SH "NAME"
.HP
gcloud preview app run \- \fB(BETA)\fR (REMOVED) Run one or more modules in the local development server



.SH "SYNOPSIS"
.HP
\f5gcloud preview app run\fR [\fIGLOBAL\-FLAG\ ...\fR] [\fIUNUSED\fR\ ...]


.SH "DESCRIPTION"

\fB(BETA)\fR (REMOVED) Run one or more modules in the local development server.



.SH "POSITIONAL ARGUMENTS"

[\fIUNUSED\fR ...]
.RS 2m



.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

This command is deprecated. Please use the dev_appserver.py script instead.



.SH "NOTES"

This command is currently in BETA and may change without notice.

