
.TH "GCLOUD_COMPUTE_FIREWALL\-RULES_DELETE" 1



.SH "NAME"
.HP
gcloud compute firewall\-rules delete \- delete Google Compute Engine firewall rules



.SH "SYNOPSIS"
.HP
\f5gcloud compute firewall\-rules delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute firewall\-rules delete\fR deletes one or more Google Compute
Engine firewall.RS 2m
rules.

.RE



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR [\fINAME\fR ...]
.RS 2m
The resources to delete.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
