
.TH "GCLOUD_DEPLOYMENT\-MANAGER_DEPLOYMENTS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud deployment\-manager deployments describe \- provide information about a deployment



.SH "SYNOPSIS"
.HP
\f5gcloud deployment\-manager deployments describe\fR \fIDEPLOYMENT_NAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command prints out all available details about a deployment.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIDEPLOYMENT_NAME\fR
Deployment name.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To display information about a deployment, run:

.RS 2m
$ gcloud deployment\-manager deployments describe my\-deployment
.RE
