
.TH "GCLOUD_COMPUTE_INSTANCE\-GROUPS_MANAGED_DELETE" 1



.SH "NAME"
.HP
gcloud compute instance\-groups managed delete \- delete Google Compute Engine managed instance groups



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-groups managed delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fB\-\-zone\fR\ \fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute instance\-groups managed delete\fR deletes one or more Google
Compute Engine managed instance groups.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR [\fINAME\fR ...]
.RS 2m
The resources to delete.


.RE

.SH "FLAGS"

\fB\-\-zone\fR \fIZONE\fR
.RS 2m
The zone of the resources to delete. If not specified, you will be prompted to
select a zone.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/zone\fR\fR property:

.RS 2m
$ gcloud config set compute/zone ZONE
.RE

A list of zones can be fetched by running:

.RS 2m
$ gcloud compute zones list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/zone
.RE

Alternatively, the zone can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_ZONE\fR\fR.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
