
.TH "GCLOUD_COMPUTE_INSTANCES" 1



.SH "NAME"
.HP
gcloud compute instances \- read and manipulate Google Compute Engine virtual machine instances



.SH "SYNOPSIS"
.HP
\f5gcloud compute instances\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Read and manipulate Google Compute Engine virtual machine instances.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBadd\-access\-config\fR
.RS 2m
Create a Google Compute Engine virtual machine access configuration.

.RE
\fBadd\-metadata\fR
.RS 2m
Add or update instance metadata.

.RE
\fBadd\-tags\fR
.RS 2m
Add tags to Google Compute Engine virtual machine instances.

.RE
\fBattach\-disk\fR
.RS 2m
Attach a disk to an instance.

.RE
\fBcreate\fR
.RS 2m
Create Google Compute Engine virtual machine instances.

.RE
\fBdelete\fR
.RS 2m
Delete Google Compute Engine virtual machine instances.

.RE
\fBdelete\-access\-config\fR
.RS 2m
Delete an access configuration from a virtual machine network interface.

.RE
\fBdescribe\fR
.RS 2m
Describe a virtual machine instance.

.RE
\fBdetach\-disk\fR
.RS 2m
Detach disks from Compute Engine virtual machine instances.

.RE
\fBget\-serial\-port\-output\fR
.RS 2m
Read output from a virtual machine instance's serial port.

.RE
\fBlist\fR
.RS 2m
List Google Compute Engine instances.

.RE
\fBmove\fR
.RS 2m
Move an instance between zones.

.RE
\fBremove\-metadata\fR
.RS 2m
Remove instance metadata.

.RE
\fBremove\-tags\fR
.RS 2m
Remove tags from Google Compute Engine virtual machine instances.

.RE
\fBreset\fR
.RS 2m
Reset a virtual machine instance.

.RE
\fBset\-disk\-auto\-delete\fR
.RS 2m
Set auto\-delete behavior for disks.

.RE
\fBset\-machine\-type\fR
.RS 2m
Set machine type for Google Compute Engine virtual machines.

.RE
\fBset\-scheduling\fR
.RS 2m
Set scheduling options for Google Compute Engine virtual machines.

.RE
\fBstart\fR
.RS 2m
Start a stopped virtual machine instance.

.RE
\fBstop\fR
.RS 2m
Stop a virtual machine instance.
.RE
