
.TH "GCLOUD_KMS" 1



.SH "NAME"
.HP
gcloud kms \- manage cryptographic keys in the cloud



.SH "SYNOPSIS"
.HP
\f5gcloud kms\fR \fIGROUP\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage cryptographic keys in the cloud.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBkeyrings\fR
Create and manage keyrings.

.TP 2m
\fBkeys\fR
Create and manage keys.

.TP 2m
\fBlocations\fR
View locations available for a project.
.RE
.sp
