
.TH "GCLOUD_COMPUTE_NETWORKS" 1



.SH "NAME"
.HP
gcloud compute networks \- list, create, and delete Google Compute Engine networks



.SH "SYNOPSIS"
.HP
\f5gcloud compute networks\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

List, create, and delete Google Compute Engine networks.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBsubnets\fR
List, describe, and delete Google Compute Engine subnetworks.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBcreate\fR
Create a Google Compute Engine network.

.TP 2m
\fBdelete\fR
Delete Google Compute Engine networks.

.TP 2m
\fBdescribe\fR
Describe a Google Compute Engine network.

.TP 2m
\fBlist\fR
List Google Compute Engine networks.

.TP 2m
\fBswitch\-mode\fR
Switch the mode of a Google Compute Engine network.
.RE
.sp
