
.TH "GCLOUD_COMPUTE_ZONES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute zones describe \- describe a Google Compute Engine zone



.SH "SYNOPSIS"
.HP
\f5gcloud compute zones describe\fR \fINAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute zones describe\fR displays all data associated with a Google
Compute Engine zone.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the resource to fetch.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
