
.TH "GCLOUD_ORGANIZATIONS" 1



.SH "NAME"
.HP
gcloud organizations \- manage Cloud Organizations



.SH "SYNOPSIS"
.HP
\f5gcloud organizations\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Commands to query and update your Cloud Organizations.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
Add IAM policy binding for a organization.

.TP 2m
\fBdescribe\fR
Show metadata for an organization.

.TP 2m
\fBget\-iam\-policy\fR
Get IAM policy for an organization.

.TP 2m
\fBlist\fR
List organizations accessible by the active account.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
Remove IAM policy binding for a organization.

.TP 2m
\fBset\-iam\-policy\fR
Set IAM policy for an organization.
.RE
.sp
