
.TH "GCLOUD_COMPUTE_HTTPS\-HEALTH\-CHECKS_DELETE" 1



.SH "NAME"
.HP
gcloud compute https\-health\-checks delete \- delete HTTPS health checks



.SH "SYNOPSIS"
.HP
\f5gcloud compute https\-health\-checks delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute https\-health\-checks delete\fR deletes one or more Google
Compute Engine HTTPS health checks.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR [\fINAME\fR ...]
.RS 2m
The resources to delete.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
