
.TH "GCLOUD_PROJECTS" 1



.SH "NAME"
.HP
gcloud projects \- manage your projects



.SH "SYNOPSIS"
.HP
\f5gcloud projects\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Commands to get information about your Google Developer projects.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBadd\-iam\-policy\-binding\fR
Add IAM policy binding for a project.

.TP 2m
\fBdelete\fR
Delete a project.

.TP 2m
\fBdescribe\fR
Show metadata for a project.

.TP 2m
\fBget\-iam\-policy\fR
Get IAM policy for a project.

.TP 2m
\fBlist\fR
List projects accessible by the active account.

.TP 2m
\fBremove\-iam\-policy\-binding\fR
Remove IAM policy binding for a project.

.TP 2m
\fBset\-iam\-policy\fR
Set IAM policy for a project.

.TP 2m
\fBundelete\fR
Undelete a project.

.TP 2m
\fBupdate\fR
Update the name of a project.
.RE
.sp
