
.TH "GCLOUD_SERVICE\-MANAGEMENT_CONFIGS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud service\-management configs describe \- describes the configuration for a given version of a service



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management configs describe\fR \fICONFIG_ID\fR \fB\-\-service\fR=\fISERVICE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Describes the configuration for a given version of a service.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fICONFIG_ID\fR
The configuration ID to retrieve.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-service\fR=\fISERVICE\fR
The service from which to retrieve the configuration.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
