
.TH "GCLOUD_KMS" 1



.SH "NAME"
.HP
gcloud kms \- manage cryptographic keys in the cloud



.SH "SYNOPSIS"
.HP
\f5gcloud kms\fR \fIGROUP\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage cryptographic keys in the cloud.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBkeyrings\fR
Create and manage keyrings.

.TP 2m
\fBkeys\fR
Create and manage keys.

.TP 2m
\fBlocations\fR
View locations available for a project.
.RE
.sp
