
.TH "GCLOUD_PREVIEW_APP_MODULES_START" 1



.SH "NAME"
.HP
gcloud preview app modules start \- \fB(BETA)\fR start serving a specific version of the given modules



.SH "SYNOPSIS"
.HP
\f5gcloud preview app modules start\fR \fIMODULES\fR [\fIMODULES\fR\ ...] \fB\-\-version\fR \fIVERSION\fR [\fB\-\-server\fR\ \fISERVER\fR] [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

\fB(BETA)\fR This command starts serving a specific version of the given
modules. It may only be used if the scaling module for your module has been set
to manual.



.SH "POSITIONAL ARGUMENTS"

\fIMODULES\fR [\fIMODULES\fR ...]
.RS 2m
One or more module names to perform this action on. To select the default module
for your app, use "default".


.RE

.SH "REQUIRED FLAGS"

\fB\-\-version\fR \fIVERSION\fR
.RS 2m
The version of the app that you want to operate on.


.RE

.SH "OPTIONAL FLAGS"

\fB\-\-server\fR \fISERVER\fR
.RS 2m
The App Engine server to connect to. You will not typically need to change this
value.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To start serving a single module, run:

.RS 2m
$ gcloud preview app modules start default \-\-version=1
.RE

To start serving multiple modules, run:

.RS 2m
$ gcloud preview app modules start module1 module2 \-\-version=1
.RE



.SH "NOTES"

This command is currently in BETA and may change without notice.

