
.TH "GCLOUD_DNS_RECORD\-SETS_LIST" 1



.SH "NAME"
.HP
gcloud dns record\-sets list \- view the list of record\-sets in a managed\-zone



.SH "SYNOPSIS"
.HP
\f5gcloud dns record\-sets list\fR [\fB\-\-limit\fR\ \fILIMIT\fR] [\fB\-\-name\fR\ \fINAME\fR] [\fB\-\-type\fR\ \fITYPE\fR] [\fB\-\-zone\fR\ \fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

This command displays the list of record\-sets contained within the specified
managed\-zone.



.SH "FLAGS"

\fB\-\-limit\fR \fILIMIT\fR
.RS 2m
Maximum number of record\-sets to list.

.RE
\fB\-\-name\fR \fINAME\fR
.RS 2m
Only list record\-sets with this exact domain name.

.RE
\fB\-\-type\fR \fITYPE\fR
.RS 2m
Only list records of this type. If present, the \-\-name parameter must also be
present.


.RE

.SH "GROUP FLAGS"

\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 2m
Name of the managed\-zone whose record\-sets you want to manage.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To see the list of all record\-sets in my_zone, run:

.RS 2m
$ gcloud dns record\-sets \-z my_zone list
.RE

To see the list of first 10 record\-sets in my_zone, run:

.RS 2m
$ gcloud dns record\-sets \-z my_zone list \-\-limit=10
.RE

To see the list of 'my.zone.com.' record\-sets in my_zone, run:

.RS 2m
$ gcloud dns record\-sets \-z my_zone list \-\-name="my.zone.com."
.RE

To see the list of 'my.zone.com.' CNAME record\-sets in my_zone, run:

.RS 2m
$ gcloud dns record\-sets \-z my_zone list \-\-name="my.zone.com." \e
    \-\-type="CNAME"
.RE
