
.TH "GCLOUD_TOPIC_FORMATS" 1



.SH "NAME"
.HP
gcloud topic formats \- resource formats supplementary help



.SH "DESCRIPTION"

Most \fBgcloud\fR commands return a list of resources on success. By default
they are pretty\-printed on the standard output. The
\fB\-\-format=\fR\fINAME\fR[\fIATTRIBUTES\fR]\fB(\fR\fIPROJECTION\fR\fB)\fR flag
changes the default output:

\fINAME\fR
.RS 2m
The format name.
.RE
\fIATTRIBUTES\fR
.RS 2m
Format specific attributes. Resource formats are described in detail below.
.RE
\fIPROJECTION\fR
.RS 2m
A list of resource keys that selects the data listed. For details run $ gcloud
topic projections.
.RE
\fIresource keys\fR
.RS 2m
Keys are names for resource resource items. For details run $ gcloud topic
resource\-keys. Most \fBgcloud\fR \fBlist\fR commands have a
\fB\-\-filter=\fR\fIEXPRESSION\fR flag that selects resources to be listed. For
details run $ gcloud topic filters.


.RE

.SH "Formats"

A format expression has 3 parts:

\fINAME\fR
.RS 2m
\fIname\fR
.RE
\fIATTRIBUTES\fR
.RS 2m
\fB[\fR [no\-]\fIattribute\-name\fR[=\fIvalue\fR] [, ... ] \fB]\fR
.RE
\fIPROJECTION\fR
.RS 2m
\fB(\fR \fIresource\-key\fR [, ...] \fB)\fR \fINAME\fR is required,
\fIATTRIBUTES\fR are optional, and \fIPROJECTIONS\fR may be required for some
formats. Unknown attribute names are silently ignored.

.RE
Each \fBgcloud\fR \fBlist\fR command has a default format expression. The
\fB\-\-format\fR flag can alter or replace the default. For example,

.RS 2m
\-\-format='[box]'
.RE

adds box decorations to a default table, and

.RS 2m
\-\-format=json
.RE

lists the resource in \fBjson\fR format.

The formats and format specific attributes are:

\fBconfig\fR
.RS 2m
A dictionary of dictionaries in config style.

.RE
\fBcsv\fR
.RS 2m
Comma Separated Values (http://www.ietf.org/rfc/rfc4180.txt) with no keys. This
format requires a projection to define the values to be printed.

The format attributes are:

\fBno\-heading\fR
.RS 2m
Disables the initial key name heading record.

.RE
.RE
\fBdefault\fR
.RS 2m
An alias for the \fByaml\fR format.

.RE
\fBflattened\fR
.RS 2m
A flattened tree. Each output line contains one \fBkey\fR:\fBvalue\fR pair.

The format attributes are:

\fBno\-pad\fR
.RS 2m
Don't print space after the separator. The default adjusts the space to align
the values into the same output column. Use \fBno\-pad\fR for comparing resource
outputs.
.RE
\fBseparator=\fISEPARATOR\fR\fR
.RS 2m
Print \fISEPARATOR\fR between the \fBkey\fR and \fBvalue\fR. The default is ":
".

.RE
.RE
\fBjson\fR
.RS 2m
JSON (http://www.json.org), JavaScript Object Notation.

The format attributes are:

\fBno\-undefined\fR
.RS 2m
Does not display resource data items with null values.

.RE
.RE
\fBlist\fR
.RS 2m
An ordered list of items.

The format attributes are:

\fBcompact\fR
.RS 2m
Display all items in a record on one line.

.RE
.RE
\fBmulti\fR
.RS 2m
Each projection key must have a subformat defined by the :format=FORMAT\-STRING
attribute. For example, \fI\-\-format='multi(data:format=json,
info:format="table[box](a, b, c)")'\fR formats the \fBdata\fR field as JSON and
the \fBinfo\fR field as a boxed table.

.RE
\fBnone\fR
.RS 2m
Disables formatted output and consumes the resources.

.RE
\fBtable\fR
.RS 2m
Aligned left\-adjusted columns with optional title, column headings and sorting.
This format requires a projection to define the table columns. The default
column headings are the disambiguated right hand components of the column keys
in ANGRY_SNAKE_CASE. For example, the projection keys (first.name, last.name)
produce the default column heading ('NAME', 'LAST_NAME'). If
\fB\-\-page\-size\fR=\fIN\fR is specified then output is grouped into tables
with at most \fIN\fR rows. Headings, alignment and sorting are done per\-page.
The title, if any, is printed before the first table.

The format attributes are:

\fBbox\fR
.RS 2m
Prints a box around the entire table and each cell, including the title if any.
.RE
\fBformat=\fIFORMAT\-STRING\fR\fR
.RS 2m
Prints the key data indented by 4 spaces using \fIFORMAT\-STRING\fR which can
reference any of the supported formats.
.RE
\fBno\-heading\fR
.RS 2m
Disables the column headings.
.RE
\fBoptional\fR
.RS 2m
Does not display the column if it is empty.
.RE
\fBpad=N\fR
.RS 2m
Sets the column horizontal pad to \fIN\fR spaces. The default is 1 for box, 2
otherwise.
.RE
\fBtitle=\fITITLE\fR\fR
.RS 2m
Prints a centered \fITITLE\fR at the top of the table, within the table box if
\fBbox\fR is enabled.

.RE
.RE
\fBtext\fR
.RS 2m
An alias for the \fBflattened\fR format.

.RE
\fBvalue\fR
.RS 2m
CSV with no heading and <TAB> separator instead of <COMMA>. Used to retrieve
individual resource values. This format requires a projection to define the
value(s) to be printed.

The format attributes are:

\fBquote\fR
.RS 2m
"..." quote values that contain <TAB>, <NEWLINE> or ".

.RE
.RE
\fByaml\fR
.RS 2m
YAML (http://www.yaml.org), YAML ain't markup language.

The format attributes are:

\fBnull=string\fR
.RS 2m
Display string instead of \f5null\fR for null/None values.
.RE
\fBno\-undefined\fR
.RS 2m
Does not display resource data items with null values.

.RE
.RE
All formats have these attributes:

\fBdisable\fR
.RS 2m
Disables formatted output and does not consume the resources.
.RE
\fBprivate\fR
.RS 2m
Disables log file output. Use this for sensitive resource data that should not
be displayed in log files. Explicit command line IO redirection overrides this
attribute.


.RE

.SH "EXAMPLES"

List a table of compute instance resources sorted by \fBname\fR with box
decorations and title \fBInstances\fR:

.RS 2m
$ gcloud compute instances list \e
    \-\-format='table[box,title=Instances](name:sort=1,
 zone:title=zone, status)'
.RE

List the disk interfaces for all compute instances as a compact comma separated
list:

.RS 2m
$ gcloud compute instances list \e
    \-\-format='value(disks[].interface.list())'
.RE

List the URIs for all compute instances:

.RS 2m
$ gcloud compute instances list \-\-format='value(uri())'
.RE

List the project authenticated user email address:

.RS 2m
$ gcloud info \-\-format='value(config.account)'
.RE
