
.TH "GCLOUD_SQL_INSTANCES_PROMOTE\-REPLICA" 1



.SH "NAME"
.HP
gcloud sql instances promote\-replica \- promotes Cloud SQL read replica to a stand\-alone instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql instances promote\-replica\fR \fIREPLICA\fR [\fB\-\-async\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Promotes Cloud SQL read replica to a stand\-alone instance.



.SH "POSITIONAL ARGUMENTS"

\fIREPLICA\fR
.RS 2m
Cloud SQL read replica ID.


.RE

.SH "FLAGS"

\fB\-\-async\fR
.RS 2m
Display information about the operation in progress and don't wait for the
operation to complete.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
