
.TH "GCLOUD_AUTH_LIST" 1



.SH "NAME"
.HP
gcloud auth list \- lists credentialed accounts



.SH "SYNOPSIS"
.HP
\f5gcloud auth list\fR [\fB\-\-filter\-account\fR=\fIFILTER_ACCOUNT\fR] [\fB\-\-filter\fR=\fIEXPRESSION\fR] [\fB\-\-limit\fR=\fILIMIT\fR] [\fB\-\-page\-size\fR=\fIPAGE_SIZE\fR] [\fB\-\-sort\-by\fR=[\fIFIELD\fR,...]] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Lists accounts whose credentials have been obtained using \f5gcloud init\fR,
\f5gcloud auth login\fR and \f5gcloud auth activate\-service\-account\fR, and
shows which account is active. The active account is used by gcloud and other
Cloud SDK tools to access Google Cloud Platform.



.SH "FLAGS"

\fB\-\-filter\-account\fR=\fIFILTER_ACCOUNT\fR
.RS 2m
List only credentials for one account. Use \-\-filter="account~\fIPATTERN\fR" to
select accounts that match \fIPATTERN\fR.


.RE

.SH "LIST COMMAND FLAGS"

\fB\-\-filter\fR=\fIEXPRESSION\fR
.RS 2m
Apply a Boolean filter \fIEXPRESSION\fR to each resource item to be listed. If
the expression evaluates True then that item is listed. For more details run $
gcloud topic filters. If \fB\-\-limit\fR is also specified then it is applied
after \fB\-\-filter\fR.

.RE
\fB\-\-limit\fR=\fILIMIT\fR
.RS 2m
The maximum number of resources to list. The default is \fBunlimited\fR. If
\fB\-\-filter\fR is also specified then it is applied before \fB\-\-limit\fR.

.RE
\fB\-\-page\-size\fR=\fIPAGE_SIZE\fR
.RS 2m
Some services group resource list output into pages. This flag specifies the
maximum number of resources per page. The default is determined by the service
if it supports paging, otherwise it is \fBunlimited\fR (no paging). Paging may
be applied before or after \fB\-\-filter\fR and \fB\-\-limit\fR depending on the
service.

.RE
\fB\-\-sort\-by\fR=[\fIFIELD\fR,...]
.RS 2m
A comma\-separated list of resource field key names to sort by. The default
order is ascending. Prefix a field with ``~'' for descending order on that
field.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To list the active account name:

.RS 2m
$ gcloud auth list \-\-filter=status:ACTIVE \-\-format="value(account)"
.RE

To list the inactive account names with prefix \f5test\fR:

.RS 2m
$ gcloud auth list \-\-filter="\-status:ACTIVE account:test*" \e
    \-\-format="value(account)"
.RE
