
.TH "GCLOUD_COMPUTE_ROUTES_DELETE" 1



.SH "NAME"
.HP
gcloud compute routes delete \- delete routes



.SH "SYNOPSIS"
.HP
\f5gcloud compute routes delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute routes delete\fR deletes one or more Google Compute Engine
routes.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR [\fINAME\fR ...]
.RS 2m
The resources to delete.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
