
.TH "GCLOUD_COMPUTE_URL\-MAPS_EDIT" 1



.SH "NAME"
.HP
gcloud compute url\-maps edit \- modify URL maps



.SH "SYNOPSIS"
.HP
\f5gcloud compute url\-maps edit\fR \fINAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute url\-maps edit\fR can be used to modify a URL map. The URL map
resource is fetched from the server and presented in a text editor. After the
file is saved and closed, this command will update the resource. Only fields
that can be modified are displayed in the editor.

The editor used to modify the resource is chosen by inspecting the
\f5\fIEDITOR\fR\fR environment variable.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the URL map.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
