
.TH "GCLOUD_SQL_BACKUPS" 1



.SH "NAME"
.HP
gcloud sql backups \- provide commands for working with backups of Cloud SQL instances



.SH "SYNOPSIS"
.HP
\f5gcloud sql backups\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Provide commands for working with backups of Cloud SQL instances including
listing and getting information about backups for a Cloud SQL instance.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Retrieves information about a backup.

.TP 2m
\fBlist\fR
Lists all backups associated with a given instance.
.RE
.sp
