
.TH "GCLOUD_COMPUTE_BACKEND\-SERVICES_DELETE" 1



.SH "NAME"
.HP
gcloud compute backend\-services delete \- delete backend services



.SH "SYNOPSIS"
.HP
\f5gcloud compute backend\-services delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fB\-\-global\fR\ |\ \fB\-\-region\fR=\fIREGION\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute backend\-services delete\fR deletes one or more backend
services.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The names of the backend services.


.RE
.sp

.SH "FLAGS"

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-global\fR
If provided, it is assumed the backend service is global.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the backend service to operate on. Overrides the default
\fBcompute/region\fR property value for this command invocation.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
