
.TH "GCLOUD_SQL_INSTANCES_RESET\-SSL\-CONFIG" 1



.SH "NAME"
.HP
gcloud sql instances reset\-ssl\-config \- deletes all client certificates and generates a new server certificate



.SH "SYNOPSIS"
.HP
\f5gcloud sql instances reset\-ssl\-config\fR \fIINSTANCE\fR [\fB\-\-async\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Deletes all client certificates and generates a new server certificate.



.SH "POSITIONAL ARGUMENTS"

\fIINSTANCE\fR
.RS 2m
Cloud SQL instance ID.


.RE

.SH "FLAGS"

\fB\-\-async\fR
.RS 2m
Display information about the operation in progress and don't wait for the
operation to complete.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
