
.TH "GCLOUD_FIREBASE" 1



.SH "NAME"
.HP
gcloud firebase \- work with Google Firebase



.SH "SYNOPSIS"
.HP
\f5gcloud firebase\fR \fIGROUP\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

To view all options available for using Firebase Test Lab, run:

.RS 2m
$ gcloud firebase test \-\-help
.RE



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBtest\fR
Interact with Firebase Test Lab.
.RE
.sp
