
.TH "GCLOUD_ML\-ENGINE_MODELS_DELETE" 1



.SH "NAME"
.HP
gcloud ml\-engine models delete \- delete an existing Cloud ML Engine model



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine models delete\fR \fIMODEL\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete an existing Cloud ML Engine model.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIMODEL\fR
Name of the model.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
