
.TH "GCLOUD_SQL" 1



.SH "NAME"
.HP
gcloud sql \- manage Cloud SQL databases



.SH "SYNOPSIS"
.HP
\f5gcloud sql\fR \fIGROUP\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud SQL databases.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

\fBbackups\fR
.RS 2m
Provide commands for working with backups of Cloud SQL instances.

.RE
\fBflags\fR
.RS 2m
Provide a command to list flags.

.RE
\fBinstances\fR
.RS 2m
Provide commands for managing Cloud SQL instances.

.RE
\fBoperations\fR
.RS 2m
Provide commands for working with Cloud SQL instance operations.

.RE
\fBssl\-certs\fR
.RS 2m
Provide commands for managing SSL certificates of Cloud SQL instances.

.RE
\fBtiers\fR
.RS 2m
Provide a command to list tiers.
.RE
