
.TH "GCLOUD_AUTH_ACTIVATE\-SERVICE\-ACCOUNT" 1



.SH "NAME"
.HP
gcloud auth activate\-service\-account \- authorize access to Google Cloud Platform using a service account



.SH "SYNOPSIS"
.HP
\f5gcloud auth activate\-service\-account\fR [\fIACCOUNT\fR] \fB\-\-key\-file\fR \fIKEY_FILE\fR [\fB\-\-password\-file\fR\ \fIPASSWORD_FILE\fR\ |\ \fB\-\-prompt\-for\-password\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Obtains access credentials for the service account using a .json (preferred) or
.p12 file that contains a private authorization key. You obtain the key file
from the Cloud Platform console (https://console.cloud.google.com). For .p12
files, a password is required. This password is displayed in the console when
you create the key. If you specify a project using the \f5\-\-project\fR flag,
the project is set in your active configuration.

Any previously active credentials will still be retained, they will just no
longer be the active credentials.



.SH "POSITIONAL ARGUMENTS"

[\fIACCOUNT\fR]
.RS 2m
E\-mail address of the service account.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-key\-file\fR \fIKEY_FILE\fR
.RS 2m
Path to the private key file.


.RE

.SH "OPTIONAL FLAGS"

\fB\-\-password\-file\fR \fIPASSWORD_FILE\fR
.RS 2m
Path to a file containing the password for the service account private key (only
for a .p12 file).

.RE
\fB\-\-prompt\-for\-password\fR
.RS 2m
Prompt for the password for the service account private key (only for a .p12
file).


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
