
.TH "GCLOUD_ML\-ENGINE_JOBS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud ml\-engine jobs describe \- describe a Cloud ML Engine job



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine jobs describe\fR \fIJOB\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe a Cloud ML Engine job.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB\fR
Name of the job.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
