
.TH "GCLOUD_SQL_INSTANCES_DELETE" 1



.SH "NAME"
.HP
gcloud sql instances delete \- deletes a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql instances delete\fR \fIINSTANCE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Deletes a Cloud SQL instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
