
.TH "GCLOUD_CONTAINER_CLUSTERS_GET\-CREDENTIALS" 1



.SH "NAME"
.HP
gcloud container clusters get\-credentials \- fetch credentials for a running cluster



.SH "SYNOPSIS"
.HP
\f5gcloud container clusters get\-credentials\fR \fINAME\fR [\fB\-\-zone\fR\ \fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

See https://cloud.google.com/container\-engine/docs/kubectl for kubectl
documentation.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the cluster to get credentials for.


.RE

.SH "FLAGS"

\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 2m
The compute zone (e.g. us\-central1\-a) for the cluster


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
