
.TH "GCLOUD_CONTAINER_NODE\-POOLS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud container node\-pools describe \- describe an existing node pool for a cluster



.SH "SYNOPSIS"
.HP
\f5gcloud container node\-pools describe\fR \fINAME\fR [\fB\-\-cluster\fR\ \fICLUSTER\fR] [\fB\-\-zone\fR\ \fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud container node\-pools describe\fR displays all data associated with
the node pool in the Google Container Engine cluster.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the node pool.


.RE

.SH "FLAGS"

\fB\-\-cluster\fR \fICLUSTER\fR
.RS 2m
The name of the cluster.

.RE
\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 2m
The compute zone (e.g. us\-central1\-a) for the cluster


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
