
.TH "GCLOUD_APP_BROWSE" 1



.SH "NAME"
.HP
gcloud app browse \- open the current app in a web browser



.SH "SYNOPSIS"
.HP
\f5gcloud app browse\fR [\fB\-\-service\fR=\fISERVICE\fR,\ \fB\-s\fR\ \fISERVICE\fR] [\fB\-\-version\fR=\fIVERSION\fR,\ \fB\-v\fR\ \fIVERSION\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Open the current app in a web browser.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-service\fR=\fISERVICE\fR, \fB\-s\fR \fISERVICE\fR
The service that should be opened. If not specified, use the default service.
May be used in conjunction with \f5\-\-version\fR.

.TP 2m
\fB\-\-version\fR=\fIVERSION\fR, \fB\-v\fR \fIVERSION\fR
The version of the app that should be opened. If not specified, choose a version
based on the service's traffic split.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To open the default service, run:

.RS 2m
$ gcloud app browse
.RE

To open a specific service, run:

.RS 2m
$ gcloud app browse \-\-service="myService"
.RE

To open a specific version, run:

.RS 2m
$ gcloud app browse \-\-service="myService" \-\-version="v1"
.RE
