
.TH "GCLOUD_ML\-ENGINE" 1



.SH "NAME"
.HP
gcloud ml\-engine \- cloud ML Engine command groups



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Cloud ML Engine command groups.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBjobs\fR
Cloud ML Engine Jobs commands.

.TP 2m
\fBlocal\fR
Cloud ML Engine Local commands.

.TP 2m
\fBmodels\fR
Cloud ML Engine Models commands.

.TP 2m
\fBoperations\fR
Manage Cloud ML Engine operations.

.TP 2m
\fBversions\fR
Cloud ML Engine Versions commands.


.RE
.sp

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBinit\-project\fR
Initialize project for Cloud ML Engine.

.TP 2m
\fBpredict\fR
Run Cloud ML Engine online prediction.
.RE
.sp
