
.TH "GCLOUD_SQL_INSTANCES_RESTART" 1



.SH "NAME"
.HP
gcloud sql instances restart \- restarts a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql instances restart\fR \fIINSTANCE\fR [\fB\-\-async\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Restarts a Cloud SQL instance.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\fR
Cloud SQL instance ID.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress and don't wait for the
operation to complete.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
