
.TH "GCLOUD_PREVIEW" 1



.SH "NAME"
.HP
gcloud preview \- manage Preview CLI command groups



.SH "SYNOPSIS"
.HP
\f5gcloud preview\fR \fIGROUP\fR [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

Manage Preview CLI command groups.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

\fBapp\fR
.RS 2m
\fB(BETA)\fR Manage your App Engine app.

.RE
\fBdatastore\fR
.RS 2m
\fB(BETA)\fR Manage your Cloud Datastore.
.RE
