
.TH "GCLOUD_COMPUTE_URL\-MAPS_SET\-DEFAULT\-SERVICE" 1



.SH "NAME"
.HP
gcloud compute url\-maps set\-default\-service \- change the default service of a URL map



.SH "SYNOPSIS"
.HP
\f5gcloud compute url\-maps set\-default\-service\fR \fINAME\fR \fB\-\-default\-service\fR \fIDEFAULT_SERVICE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute url\-maps set\-default\-service\fR is used to change the
default service of a URL map. The default service is used for any requests for
which there is no mapping in the URL map.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the URL map.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-default\-service\fR \fIDEFAULT_SERVICE\fR
.RS 2m
A backend service that will be used for requests for which this URL map has no
mappings.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
