
.TH "GCLOUD_ML\-ENGINE_INIT\-PROJECT" 1



.SH "NAME"
.HP
gcloud ml\-engine init\-project \- initialize project for Cloud ML Engine



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine init\-project\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Initialize project for Cloud ML Engine.

gcloud ml\-engine init\-project initializes the current project for use with
Google Cloud Machine Learning Engine. Specifically, it adds the required Cloud
Machine Learning Engine service accounts to the current project as editors.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
