
.TH "GCLOUD_CONTAINER_NODE\-POOLS_LIST" 1



.SH "NAME"
.HP
gcloud container node\-pools list \- list existing node pools for a cluster



.SH "SYNOPSIS"
.HP
\f5gcloud container node\-pools list\fR [\fB\-\-cluster\fR\ \fICLUSTER\fR] [\fB\-\-zone\fR\ \fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fB\-\-filter\fR\ \fIEXPRESSION\fR] [\fB\-\-flatten\fR\ [\fIKEY\fR,...]] [\fB\-\-limit\fR\ \fILIMIT\fR] [\fB\-\-page\-size\fR\ \fIPAGE_SIZE\fR] [\fB\-\-sort\-by\fR\ \fIFIELDS\fR] [\fB\-\-uri\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud container node\-pools list\fR displays all node pools in the Google
Container Engine cluster.



.SH "FLAGS"

\fB\-\-cluster\fR \fICLUSTER\fR
.RS 2m
The name of the cluster.

.RE
\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 2m
The compute zone (e.g. us\-central1\-a) for the cluster


.RE

.SH "LIST COMMAND FLAGS"

\fB\-\-filter\fR \fIEXPRESSION\fR
.RS 2m
Apply a Boolean filter \fIEXPRESSION\fR to each resource item to be listed. If
the expression evaluates True then that item is listed. For more details run $
gcloud topic filters. If \fB\-\-limit\fR is also specified then it is applied
after \fB\-\-filter\fR.

.RE
\fB\-\-flatten\fR [\fIKEY\fR,...]
.RS 2m
Flatten \fIname\fR[] resource slices in \fIKEY\fR to separate records for each
item in each slice. Multiple keys and slices may be specified. This also
flattens keys for \fB\-\-format\fR and \fB\-\-filter\fR. For example,
\fB\-\-flatten=abc.def[]\fR flattens \fBabc.def[].ghi\fR references to
\fBabc.def.ghi\fR.

.RE
\fB\-\-limit\fR \fILIMIT\fR
.RS 2m
The maximum number of resources to list. The default is \fBunlimited\fR. If
\fB\-\-filter\fR is also specified then it is applied before \fB\-\-limit\fR.

.RE
\fB\-\-page\-size\fR \fIPAGE_SIZE\fR
.RS 2m
Some services group resource list output into pages. This flag specifies the
maximum number of resources per page. The default is determined by the service
if it supports paging, otherwise it is \fBunlimited\fR (no paging). Paging may
be applied before or after \fB\-\-filter\fR and \fB\-\-limit\fR depending on the
service.

.RE
\fB\-\-sort\-by\fR \fIFIELDS\fR
.RS 2m
A comma\-separated list of resource field key names to sort by. The default
order is ascending. Prefix a field with ``~'' for descending order on that
field.

.RE
\fB\-\-uri\fR
.RS 2m
Print a list of resource URIs instead of the default output.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To list all node pools in the cluster "sample\-cluster" in table form, run:

.RS 2m
$ gcloud container node\-pools list \-\-cluster=sample\-cluster
.RE
