
.TH "GCLOUD_COMPUTE_INSTANCE\-GROUPS_UNMANAGED" 1



.SH "NAME"
.HP
gcloud compute instance\-groups unmanaged \- read and manipulate Google Compute Engine unmanaged instance group



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-groups unmanaged\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Read and manipulate Google Compute Engine unmanaged instance groups.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBadd\-instances\fR
.RS 2m
Adds instances to an unmanaged instance group by name.

.RE
\fBcreate\fR
.RS 2m
Create a Compute Engine unmanaged instance group.

.RE
\fBdelete\fR
.RS 2m
Delete Google Compute Engine unmanaged instance groups.

.RE
\fBdescribe\fR
.RS 2m
Describe an instance group.

.RE
\fBget\-named\-ports\fR
.RS 2m
Lists the named ports for an instance group resource.

.RE
\fBlist\fR
.RS 2m
List Google Compute Engine unmanaged instance groups.

.RE
\fBlist\-instances\fR
.RS 2m
List instances present in the instance group.

.RE
\fBremove\-instances\fR
.RS 2m
Removes resources from an unmanaged instance group by instance name.

.RE
\fBset\-named\-ports\fR
.RS 2m
Sets the list of named ports for an instance group.
.RE
