
.TH "GCLOUD_SQL_INSTANCES_SET\-ROOT\-PASSWORD" 1



.SH "NAME"
.HP
gcloud sql instances set\-root\-password \- sets the password of the MySQL root user



.SH "SYNOPSIS"
.HP
\f5gcloud sql instances set\-root\-password\fR \fIINSTANCE\fR [\fB\-\-async\fR] [\fB\-\-password\fR\ \fIPASSWORD\fR,\ \fB\-p\fR\ \fIPASSWORD\fR\ |\ \fB\-\-password\-file\fR\ \fIPASSWORD_FILE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Sets the password of the MySQL root user.



.SH "POSITIONAL ARGUMENTS"

\fIINSTANCE\fR
.RS 2m
Cloud SQL instance ID.


.RE

.SH "FLAGS"

\fB\-\-async\fR
.RS 2m
Display information about the operation in progress and don't wait for the
operation to complete.

.RE
\fB\-\-password\fR \fIPASSWORD\fR, \fB\-p\fR \fIPASSWORD\fR
.RS 2m
The password for the root user. WARNING: Setting password using this option can
potentially expose the password to other users of this machine. Instead, you can
use \-\-password\-file to get the password from a file.

.RE
\fB\-\-password\-file\fR \fIPASSWORD_FILE\fR
.RS 2m
The path to the filename which has the password to be set. The first line of the
file will be interpreted as the password to be set.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
