
.TH "GCLOUD_DATAPROC_OPERATIONS_CANCEL" 1



.SH "NAME"
.HP
gcloud dataproc operations cancel \- cancel an active operation



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc operations cancel\fR \fIOPERATION\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Cancel an active operation.



.SH "POSITIONAL ARGUMENTS"

\fIOPERATION\fR
.RS 2m
The ID of the operation to cancel.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To cancel an operation, run:

.RS 2m
$ gcloud dataproc operations cancel operation_id
.RE
