
.TH "GCLOUD_SERVICE\-MANAGEMENT_OPERATIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud service\-management operations describe \- describes an operation resource for a given operation name



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management operations describe\fR \fIOPERATION\fR [\fB\-\-full\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Describes an operation resource for a given operation name.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
The name of the operation to describe.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-full\fR
Print the entire operation resource, which could be large. By default, a summary
will be printed instead.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
