
.TH "GCLOUD_COMPUTE_SSL\-CERTIFICATES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute ssl\-certificates describe \- describe a Google Compute Engine SSL certificate



.SH "SYNOPSIS"
.HP
\f5gcloud compute ssl\-certificates describe\fR \fINAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute ssl\-certificates describe\fR displays all data associated
with Google Compute Engine SSL certificate in a project.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the resource to fetch.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
