
.TH "GCLOUD_FEEDBACK" 1



.SH "NAME"
.HP
gcloud feedback \- provide feedback to the Google Cloud SDK team



.SH "SYNOPSIS"
.HP
\f5gcloud feedback\fR [\fB\-\-log\-file\fR\ \fILOG_FILE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

The Google Cloud SDK team offers support through a number of channels:

.RS 2m
.IP "\(bu" 2m
Google Cloud SDK Issue Tracker
.RE
.RS 2m
.IP "\(bu" 2m
Stack Overflow "#gcloud" tag
.RE
.RS 2m
.IP "\(bu" 2m
google\-cloud\-dev Google group
.RE

This command lists the available channels and facilitates getting help through
one of them by opening a web browser to the relevant page, possibly with
information relevant to the current install and configuration pre\-populated in
form fields on that page.



.SH "FLAGS"

\fB\-\-log\-file\fR \fILOG_FILE\fR
.RS 2m
Path to the log file from a prior gcloud run.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
