
.TH "GCLOUD_CONTAINER_CLUSTERS_LIST" 1



.SH "NAME"
.HP
gcloud container clusters list \- list existing clusters for running containers



.SH "SYNOPSIS"
.HP
\f5gcloud container clusters list\fR [\fB\-\-zone\fR\ \fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

List existing clusters for running containers.



.SH "FLAGS"

\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 2m
The compute zone (e.g. us\-central1\-a) for the cluster


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
