
.TH "GCLOUD_COMPUTE_URL\-MAPS_DELETE" 1



.SH "NAME"
.HP
gcloud compute url\-maps delete \- delete URL maps



.SH "SYNOPSIS"
.HP
\f5gcloud compute url\-maps delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute url\-maps delete\fR deletes one or more URL maps.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The resources to delete.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
