
.TH "GCLOUD_COMPUTE_TARGET\-HTTPS\-PROXIES_DELETE" 1



.SH "NAME"
.HP
gcloud compute target\-https\-proxies delete \- delete target HTTPS proxies



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-https\-proxies delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute target\-https\-proxies delete\fR deletes one or more target
HTTPS proxies.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The resources to delete.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
