
.TH "GCLOUD_SQL_OPERATIONS_LIST" 1



.SH "NAME"
.HP
gcloud sql operations list \- lists all instance operations for the given Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql operations list\fR [\fB\-\-instance\fR\ \fIINSTANCE\fR,\ \fB\-i\fR\ \fIINSTANCE\fR] [\fB\-\-limit\fR\ \fILIMIT\fR] [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

Lists all instance operations for the given Cloud SQL instance.



.SH "FLAGS"

\fB\-\-instance\fR \fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
.RS 2m
Cloud SQL instance ID.

.RE
\fB\-\-limit\fR \fILIMIT\fR
.RS 2m
Maximum number of operations to list.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
