
.TH "GCLOUD_SQL_OPERATIONS_WAIT" 1



.SH "NAME"
.HP
gcloud sql operations wait \- waits for one or more operations to complete



.SH "SYNOPSIS"
.HP
\f5gcloud sql operations wait\fR \fIOPERATION\fR [\fIOPERATION\fR\ ...] \fB\-\-instance\fR \fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Waits for one or more operations to complete.



.SH "POSITIONAL ARGUMENTS"

\fIOPERATION\fR [\fIOPERATION\fR ...]
.RS 2m
An identifier that uniquely identifies the operation.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-instance\fR \fIINSTANCE\fR, \fB\-i\fR \fIINSTANCE\fR
.RS 2m
Cloud SQL instance ID.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
