
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_ADD\-IAM\-POLICY\-BINDING" 1



.SH "NAME"
.HP
gcloud iam service\-accounts add\-iam\-policy\-binding \- add IAM policy binding for a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts add\-iam\-policy\-binding\fR \fIIAM\-ACCOUNT\fR \fB\-\-member\fR \fIMEMBER\fR \fB\-\-role\fR \fIROLE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command adds a policy binding to the IAM policy of a service account, given
an IAM\-ACCOUNT and the binding.



.SH "POSITIONAL ARGUMENTS"

\fIIAM\-ACCOUNT\fR
.RS 2m
The service account whose policy to add bindings to.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-member\fR \fIMEMBER\fR
.RS 2m
The member to add to the binding.

.RE
\fB\-\-role\fR \fIROLE\fR
.RS 2m
Define the role of the member.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

The following command will add an IAM policy binding for the role of
\'roles/editor' for the user 'test\-user@gmail.com' on a service account with
identifier 'my\-iam\-account@somedomain.com'

.RS 2m
$ gcloud iam service\-accounts add\-iam\-policy\-binding \e
    my\-iam\-account@somedomain.com \e
    \-\-member='user:test\-user@gmail.com' \-\-role='roles/editor'
.RE

See https://cloud.google.com/iam/docs/managing\-policies for details of policy
role and member types.
