
.TH "GCLOUD_APP_VERSIONS" 1



.SH "NAME"
.HP
gcloud app versions \- view and manage your App Engine versions



.SH "SYNOPSIS"
.HP
\f5gcloud app versions\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This set of commands can be used to view and manage your existing App Engine
versions. To create new deployments, use \f5gcloud app deploy\fR.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBbrowse\fR
.RS 2m
Open the specified versions in a browser.

.RE
\fBdelete\fR
.RS 2m
Delete a specified version.

.RE
\fBdescribe\fR
.RS 2m
Display all data about an existing version.

.RE
\fBlist\fR
.RS 2m
List your existing versions.

.RE
\fBstart\fR
.RS 2m
Start serving specified versions.

.RE
\fBstop\fR
.RS 2m
Stop serving specified versions.


.RE

.SH "EXAMPLES"

To list your deployed versions, run:

.RS 2m
$ gcloud app versions list
.RE
