
.TH "GCLOUD_CONFIG_CONFIGURATIONS_CREATE" 1



.SH "NAME"
.HP
gcloud config configurations create \- creates a new named configuration



.SH "SYNOPSIS"
.HP
\f5gcloud config configurations create\fR \fICONFIGURATION_NAME\fR [\fB\-\-activate\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Creates a new named configuration.

See \f5gcloud topic configurations\fR for an overview of named configurations.



.SH "POSITIONAL ARGUMENTS"

\fICONFIGURATION_NAME\fR
.RS 2m
Name of the configuration to create


.RE

.SH "FLAGS"

\fB\-\-activate\fR
.RS 2m
If true, activate this configuration upon create. Overrides the default
\fBactivate_on_create\fR property value for this command invocation. Use
\fB\-\-no\-activate\fR to disable.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To create a new named configuration, run:

.RS 2m
$ gcloud config configurations create my_config
.RE
