
.TH "GCLOUD_DATAPROC_JOBS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud dataproc jobs describe \- view the details of a job



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc jobs describe\fR \fIJOB_ID\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

View the details of a job.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB_ID\fR
The ID of the job to describe.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To view the details of a job, run:

.RS 2m
$ gcloud dataproc jobs describe job_id
.RE
