
.TH "GCLOUD_COMPUTE_ADDRESSES_DELETE" 1



.SH "NAME"
.HP
gcloud compute addresses delete \- release reserved IP addresses



.SH "SYNOPSIS"
.HP
\f5gcloud compute addresses delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fB\-\-global\fR\ |\ \fB\-\-region\fR=\fIREGION\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute addresses delete\fR releases one or more Google Compute Engine
IP addresses.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The address names to operate on.


.RE
.sp

.SH "FLAGS"

At most one of these may be specified:

.RS 2m
.TP 2m
\fB\-\-global\fR
If provided, it is assumed the address name is global.

.TP 2m
\fB\-\-region\fR=\fIREGION\fR
The region of the address name to operate on. If not specified, you will be
prompted to select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
