
.TH "GCLOUD_COMPUTE_INSTANCE\-GROUPS_MANAGED_ABANDON\-INSTANCES" 1



.SH "NAME"
.HP
gcloud compute instance\-groups managed abandon\-instances \- abandon instances owned by a managed instance group



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-groups managed abandon\-instances\fR \fINAME\fR \fB\-\-instances\fR=\fIINSTANCE\fR,[\fIINSTANCE\fR,...] [\fB\-\-region\fR=\fIREGION\fR\ |\ \fB\-\-zone\fR=\fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute instance\-groups managed abandon\-instances\fR abandons one or
more instances from a managed instance group, thereby reducing the targetSize of
the group. Once instances have been abandoned, the currentSize of the group is
automatically reduced as well to reflect the change.

Abandoning an instance does not delete the underlying virtual machine instances,
but just removes the instances from the instance group. If you would like the
delete the underlying instances, use the delete\-instances command instead.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the managed instance group.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-instances\fR=\fIINSTANCE\fR,[\fIINSTANCE\fR,...]
.RS 2m
Names of instances to abandon.


.RE

.SH "OPTIONAL FLAGS"

At most one of these may be specified:

\fB\-\-region\fR=\fIREGION\fR
.RS 2m
The region of the managed instance group to operate on. If not specified, you
will be prompted to select a region.

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

.RE
\fB\-\-zone\fR=\fIZONE\fR
.RS 2m
The zone of the managed instance group to operate on. If not specified, you will
be prompted to select a zone.

A list of zones can be fetched by running:

.RS 2m
$ gcloud compute zones list
.RE


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
