
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_GET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud iam service\-accounts get\-iam\-policy \- get the IAM policy for a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts get\-iam\-policy\fR \fIIAM\-ACCOUNT\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Get the IAM policy for a service account.



.SH "POSITIONAL ARGUMENTS"

\fIIAM\-ACCOUNT\fR
.RS 2m
The service account whose policy to get.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To print the IAM policy for a given service account, run:

.RS 2m
$ gcloud iam service\-accounts get\-iam\-policy \e
    my\-iam\-account@somedomain.com
.RE
