
.TH "GCLOUD_INFO" 1



.SH "NAME"
.HP
gcloud info \- display information about the current gcloud environment



.SH "SYNOPSIS"
.HP
\f5gcloud info\fR [\fB\-\-run\-diagnostics\fR] [\fB\-\-show\-log\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command displays information about the current gcloud environment.



.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-run\-diagnostics\fR
Run diagnostics on your installation of the Cloud SDK.

.TP 2m
\fB\-\-show\-log\fR
Print the contents of the last log file.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
