
.TH "GCLOUD_CONTAINER_CLUSTERS_DELETE" 1



.SH "NAME"
.HP
gcloud container clusters delete \- delete an existing cluster for running containers



.SH "SYNOPSIS"
.HP
\f5gcloud container clusters delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fB\-\-async\fR] [\fB\-\-wait\fR] [\fB\-\-zone\fR\ \fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete an existing cluster for running containers.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR [\fINAME\fR ...]
.RS 2m
The names of the clusters to delete.


.RE

.SH "FLAGS"

\fB\-\-async\fR
.RS 2m
Don't wait for the operation to complete. Use \fB\-\-no\-async\fR to disable.

.RE
\fB\-\-wait\fR
.RS 2m
Poll the operation for completion after issuing a create request. Use
\fB\-\-no\-wait\fR to disable.

.RE
\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 2m
The compute zone (e.g. us\-central1\-a) for the cluster


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
