
.TH "GCLOUD_COMPUTE_IMAGES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute images describe \- describe a Google Compute Engine image



.SH "SYNOPSIS"
.HP
\f5gcloud compute images describe\fR \fINAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute images describe\fR displays all data associated with a Google
Compute Engine image in a project.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the resource to fetch.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
