
.TH "GCLOUD_PREVIEW_APP_MODULES" 1



.SH "NAME"
.HP
gcloud preview app modules \- deprecated. View and manage your App Engine modules



.SH "SYNOPSIS"
.HP
\f5gcloud preview app modules\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

\fB(PREVIEW)\fR This set of commands can be used to view and manage your
existing App Engine modules. To create new deployments of modules, use gcloud
preview app deploy.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBdelete\fR
.RS 2m
\fB(PREVIEW)\fR Delete a specific version of the given modules.

.RE
\fBget\-logs\fR
.RS 2m
\fB(PREVIEW)\fR Gets the logs for the given module.

.RE
\fBlist\fR
.RS 2m
\fB(PREVIEW)\fR List your existing deployed modules and versions.

.RE
\fBset\-default\fR
.RS 2m
\fB(PREVIEW)\fR Set the default serving version for the given modules.

.RE
\fBset\-managed\-by\fR
.RS 2m
\fB(PREVIEW)\fR Sets the policy for the Flexible VMs of the given services and
version.

.RE
\fBstart\fR
.RS 2m
\fB(PREVIEW)\fR Start serving a specific version of the given modules.

.RE
\fBstop\fR
.RS 2m
\fB(PREVIEW)\fR Stop serving a specific version of the given modules.


.RE

.SH "EXAMPLES"

To list your deployed modules, run:

.RS 2m
$ gcloud preview app modules list
.RE



.SH "NOTES"

This command is currently in DEVELOPER PREVIEW and may change without notice.

