
.TH "GCLOUD_CONFIG_UNSET" 1



.SH "NAME"
.HP
gcloud config unset \- erase Google Cloud SDK properties



.SH "SYNOPSIS"
.HP
\f5gcloud config unset\fR \fISECTION\fR/\fIPROPERTY\fR [\fB\-\-installation\fR] [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

Unset a property to be as if it were never defined in the first place. You may
optionally use the \-\-scope flag to specify a configuration file to update.



.SH "POSITIONAL ARGUMENTS"

\fISECTION\fR/\fIPROPERTY\fR
.RS 2m
The property to be unset. Note that SECTION/ is optional while referring to
properties in the core section.


.RE

.SH "FLAGS"

\fB\-\-installation\fR
.RS 2m
Typically properties are updated only in the currently active configuration, but
when \f5\-\-installation\fR is given the property is updated for the entire
gcloud installation.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To unset the project property in the core section, run:

.RS 2m
$ gcloud config unset project
.RE

To unset the zone property in the compute section, run:

.RS 2m
$ gcloud config unset compute/zone
.RE
