
.TH "GCLOUD_PROJECTS_LIST" 1



.SH "NAME"
.HP
gcloud projects list \- list projects accessible by the active account



.SH "SYNOPSIS"
.HP
\f5gcloud projects list\fR [\fB\-\-limit\fR\ \fILIMIT\fR] [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

Lists all active projects, where the active account has Owner, Editor or Viewer
permissions. Projects are listed in alphabetical order by project name. Projects
that have been deleted or are pending deletion are not included.

You can specify the maximum number of projects to list using the \f5\-\-limit\fR
flag.



.SH "FLAGS"

\fB\-\-limit\fR \fILIMIT\fR
.RS 2m
Maximum number of results.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

The following command lists a maximum of five projects sorted alphabetically by
name:

.RS 2m
$ gcloud projects list \-\-limit=5
.RE
