
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_REMOVE\-IAM\-POLICY\-BINDING" 1



.SH "NAME"
.HP
gcloud iam service\-accounts remove\-iam\-policy\-binding \- remove IAM policy binding for a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts remove\-iam\-policy\-binding\fR \fIIAM\-ACCOUNT\fR \fB\-\-member\fR=\fIMEMBER\fR \fB\-\-role\fR=\fIROLE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command removes a policy binding to the IAM policy of a service account,
given an IAM\-ACCOUNT and the binding.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIIAM\-ACCOUNT\fR
The service account whose policy to remove the binding from.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-member\fR=\fIMEMBER\fR
The member to remove from the binding.

.TP 2m
\fB\-\-role\fR=\fIROLE\fR
The role to remove the member from.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

The following command will remove a IAM policy binding for the role of
\'roles/editor' for the user 'test\-user@gmail.com' on service account with
identifier 'my\-iam\-account@somedomain.com'

.RS 2m
$ gcloud iam service\-accounts remove\-iam\-policy\-binding \e
    my\-iam\-account@somedomain.com \e
    \-\-member='user:test\-user@gmail.com' \-\-role='roles/editor'
.RE

See https://cloud.google.com/iam/docs/managing\-policies for details of policy
role and member types.
