
.TH "GCLOUD_COMPUTE_PROJECT\-INFO_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute project\-info describe \- describe the Google Compute Engine project resource



.SH "SYNOPSIS"
.HP
\f5gcloud compute project\-info describe\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute project\-info describe\fR displays all data associated with
the Google Compute Engine project resource. The project resource contains data
such as global quotas, common instance metadata, and the project's creation
time.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
