
.TH "GCLOUD_COMPUTE_FORWARDING\-RULES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute forwarding\-rules describe \- display detailed information about a forwarding rule



.SH "SYNOPSIS"
.HP
\f5gcloud compute forwarding\-rules describe\fR \fINAME\fR [\fB\-\-global\fR\ |\ \fB\-\-region\fR\ \fIREGION\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute forwarding\-rules describe\fR displays all data associated
with a forwarding rule in a project.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the resource to fetch.


.RE

.SH "FLAGS"

\fB\-\-global\fR
.RS 2m
If provided, it is assumed that the requested resource is global.

.RE
\fB\-\-region\fR \fIREGION\fR
.RS 2m
The region of the resource to fetch.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To get details about a global forwarding rule, run:

.RS 2m
$ gcloud compute forwarding\-rules describe FORWARDING\-RULE \-\-global
.RE

To get details about a regional forwarding rule, run:

.RS 2m
$ gcloud compute forwarding\-rules describe FORWARDING\-RULE \e
    \-\-region us\-central1
.RE
