
.TH "GCLOUD_COMPUTE_URL\-MAPS" 1



.SH "NAME"
.HP
gcloud compute url\-maps \- list, create, and delete URL maps



.SH "SYNOPSIS"
.HP
\f5gcloud compute url\-maps\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

List, create, and delete URL maps.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBadd\-host\-rule\fR
.RS 2m
Add a rule to a URL map to map hosts to a path matcher.

.RE
\fBadd\-path\-matcher\fR
.RS 2m
Add a path matcher to a URL map.

.RE
\fBcreate\fR
.RS 2m
Create a URL map.

.RE
\fBdelete\fR
.RS 2m
Delete URL maps.

.RE
\fBdescribe\fR
.RS 2m
Describe a URL map.

.RE
\fBedit\fR
.RS 2m
Modify URL maps.

.RE
\fBinvalidate\-cdn\-cache\fR
.RS 2m
Invalidate specified objects for a URL map in Cloud CDN caches.

.RE
\fBlist\fR
.RS 2m
List Google Compute Engine URL maps.

.RE
\fBremove\-host\-rule\fR
.RS 2m
Remove a host rule from a URL map.

.RE
\fBremove\-path\-matcher\fR
.RS 2m
Remove a path matcher from a URL map.

.RE
\fBset\-default\-service\fR
.RS 2m
Change the default service of a URL map.
.RE
