
.TH "GCLOUD_ML\-ENGINE_MODELS_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud ml\-engine models set\-iam\-policy \- set the IAM policy for a model



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine models set\-iam\-policy\fR \fIMODEL\fR \fIPOLICY_FILE\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

Sets the IAM policy for the given model as defined in a JSON file.

See https://cloud.google.com/iam/docs/managing\-policies for details of the
policy file format and contents.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIMODEL\fR
Name of the model.

.TP 2m
\fIPOLICY_FILE\fR
JSON file with the IAM policy


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The following command will read am IAM policy defined in a JSON file
\'policy.json' and set it for the model \f5my_model\fR:

.RS 2m
$ gcloud ml\-engine models set\-iam\-policy my_model policy.json
.RE
