
.TH "GCLOUD_COMPUTE_TARGET\-POOLS" 1



.SH "NAME"
.HP
gcloud compute target\-pools \- control Compute Engine target pools for network load balancing



.SH "SYNOPSIS"
.HP
\f5gcloud compute target\-pools\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Control Compute Engine target pools for network load balancing.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBadd\-health\-checks\fR
.RS 2m
Add an HTTP health check to a target pool.

.RE
\fBadd\-instances\fR
.RS 2m
Add instances to a target pool.

.RE
\fBcreate\fR
.RS 2m
Define a load\-balanced pool of virtual machine instances.

.RE
\fBdelete\fR
.RS 2m
Delete target pools.

.RE
\fBdescribe\fR
.RS 2m
Describe a Google Compute Engine target pool.

.RE
\fBget\-health\fR
.RS 2m
Get the health of instances in a target pool.

.RE
\fBlist\fR
.RS 2m
List Google Compute Engine target pools.

.RE
\fBremove\-health\-checks\fR
.RS 2m
Remove an HTTP health check from a target pool.

.RE
\fBremove\-instances\fR
.RS 2m
Remove instances from a target pool.

.RE
\fBset\-backup\fR
.RS 2m
Set a backup pool for a target pool.
.RE
