
.TH "GCLOUD_SERVICE\-MANAGEMENT_DESCRIBE" 1



.SH "NAME"
.HP
gcloud service\-management describe \- describes a service given a service name



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management describe\fR \fISERVICE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Describes a service given a service name.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICE\fR
The name of the service to describe.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
