
.TH "GCLOUD_COMPUTE_INSTANCES_LIST" 1



.SH "NAME"
.HP
gcloud compute instances list \- list Google Compute Engine instances



.SH "SYNOPSIS"
.HP
\f5gcloud compute instances list\fR [\fINAME\fR\ ...] [\fB\-\-limit\fR\ \fILIMIT\fR] [\fB\-\-regexp\fR\ \fIREGEXP\fR,\ \fB\-r\fR\ \fIREGEXP\fR] [\fB\-\-sort\-by\fR\ \fISORT_BY\fR] [\fB\-\-uri\fR] [\fB\-\-zones\fR\ \fIZONE\fR,[\fIZONE\fR,...]] [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

\fBgcloud compute instances list\fR displays all Google Compute Engine instances
in a project.

By default, instances from all zones are listed. The results can be narrowed
down by providing the \f5\fI\-\-zones\fR\fR flag.



.SH "POSITIONAL ARGUMENTS"

[\fINAME\fR ...]
.RS 2m
If provided, show details for the specified names and/or URIs of resources.


.RE

.SH "FLAGS"

\fB\-\-limit\fR \fILIMIT\fR
.RS 2m
The maximum number of results.

.RE
\fB\-\-regexp\fR \fIREGEXP\fR, \fB\-r\fR \fIREGEXP\fR
.RS 2m
A regular expression to filter the names of the results on. Any names that do
not match the entire regular expression will be filtered out.

.RE
\fB\-\-sort\-by\fR \fISORT_BY\fR
.RS 2m
A field to sort by. To perform a descending\-order sort, prefix the value of
this flag with a tilde (``~'').

.RE
\fB\-\-uri\fR
.RS 2m
If provided, the list command will only print URIs for the resources returned.
If this flag is not provided, the list command will print a human\-readable
table of useful resource data.

.RE
\fB\-\-zones\fR \fIZONE\fR,[\fIZONE\fR,...]
.RS 2m
If provided, only resources from the given zones are queried.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To list all instances in a project in table form, run:

.RS 2m
$ gcloud compute instances list
.RE

To list the URIs of all instances in a project, run:

.RS 2m
$ gcloud compute instances list \-\-uri
.RE

To list all instances in the \f5\fIus\-central1\-b\fR\fR and
\f5\fIeurope\-west1\-d\fR\fR zones, run:

.RS 2m
$ gcloud compute instances list \-\-zones us\-central1\-b \e
    europe\-west1\-d
.RE
