
.TH "GCLOUD_SQL" 1



.SH "NAME"
.HP
gcloud sql \- manage Cloud SQL databases



.SH "SYNOPSIS"
.HP
\f5gcloud sql\fR \fIGROUP\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Cloud SQL databases.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBbackups\fR
Provide commands for working with backups of Cloud SQL instances.

.TP 2m
\fBflags\fR
Provide a command to list flags.

.TP 2m
\fBinstances\fR
Provide commands for managing Cloud SQL instances.

.TP 2m
\fBoperations\fR
Provide commands for working with Cloud SQL instance operations.

.TP 2m
\fBssl\-certs\fR
Provide commands for managing SSL certificates of Cloud SQL instances.

.TP 2m
\fBtiers\fR
Provide a command to list tiers.
.RE
.sp
