
.TH "GCLOUD_DNS_MANAGED\-ZONES_CREATE" 1



.SH "NAME"
.HP
gcloud dns managed\-zones create \- create a Cloud DNS managed\-zone



.SH "SYNOPSIS"
.HP
\f5gcloud dns managed\-zones create\fR \fIZONE_NAME\fR \fB\-\-description\fR \fIDESCRIPTION\fR \fB\-\-dns\-name\fR \fIDNS_NAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command creates a Cloud DNS managed\-zone.



.SH "POSITIONAL ARGUMENTS"

\fIZONE_NAME\fR
.RS 2m
Name of the managed\-zone to be created.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 2m
Short description for the managed\-zone.

.RE
\fB\-\-dns\-name\fR \fIDNS_NAME\fR
.RS 2m
The DNS name suffix that will be managed with the created zone.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To create a managed\-zone, run:

.RS 2m
$ gcloud dns managed\-zones create my_zone \-\-dns_name my.zone.com. \e
    \-\-description "My zone!"
.RE
