
.TH "GCLOUD_COMPUTE_INSTANCE\-GROUPS_MANAGED_RESIZE" 1



.SH "NAME"
.HP
gcloud compute instance\-groups managed resize \- set managed instance group size



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-groups managed resize\fR \fINAME\fR \fB\-\-size\fR=\fISIZE\fR [\fB\-\-region\fR=\fIREGION\fR\ |\ \fB\-\-zone\fR=\fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute instance\-groups managed resize\fR resize a managed instance
group to a provided size.

If you resize down, the Instance Group Manager service deletes instances from
the group until the group reaches the desired size. To understand in what order
instances will be deleted, see the API documentation.

If you resize up, the service adds instances to the group using the current
instance template until the group reaches the desired size.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the managed instance group.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-size\fR=\fISIZE\fR
.RS 2m
Target number of instances in managed instance group.


.RE

.SH "OPTIONAL FLAGS"

At most one of these may be specified:

\fB\-\-region\fR=\fIREGION\fR
.RS 2m
The region of the managed instance group to operate on. If not specified, you
will be prompted to select a region.

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

.RE
\fB\-\-zone\fR=\fIZONE\fR
.RS 2m
The zone of the managed instance group to operate on. If not specified, you will
be prompted to select a zone.

A list of zones can be fetched by running:

.RS 2m
$ gcloud compute zones list
.RE


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
