
.TH "GCLOUD_DATAPROC_JOBS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud dataproc jobs describe \- view the details of a job



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc jobs describe\fR \fIJOB_ID\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

View the details of a job.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB_ID\fR
The ID of the job to describe.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

To view the details of a job, run:

.RS 2m
$ gcloud dataproc jobs describe job_id
.RE
