
.TH "GCLOUD_APP_DEPLOY" 1



.SH "NAME"
.HP
gcloud app deploy \- deploy the local code and/or configuration of your app to App Engine



.SH "SYNOPSIS"
.HP
\f5gcloud app deploy\fR [\fIDEPLOYABLES\fR\ ...] [\fB\-\-bucket\fR\ \fIBUCKET\fR] [\fB\-\-image\-url\fR\ \fIIMAGE_URL\fR] [\fB\-\-no\-promote\fR] [\fB\-\-no\-stop\-previous\-version\fR] [\fB\-\-version\fR\ \fIVERSION\fR,\ \fB\-v\fR\ \fIVERSION\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command is used to deploy both code and configuration to the App Engine
server. As an input it takes one or more \f5\fIDEPLOYABLES\fR\fR that should be
uploaded. A \f5\fIDEPLOYABLE\fR\fR can be a service's .yaml file or a
configuration's .yaml file.



.SH "POSITIONAL ARGUMENTS"

[\fIDEPLOYABLES\fR ...]
.RS 2m
The yaml files for the services or configurations you want to deploy. If not
given, defaults to \f5app.yaml\fR in the current directory. If that is not
found, attempts to automatically generate necessary configuration files (such as
app.yaml) in the current directory.


.RE

.SH "FLAGS"

\fB\-\-bucket\fR \fIBUCKET\fR
.RS 2m
The Google Cloud Storage bucket used to stage files associated with the
deployment. If this argument is not specified, the application's default code
bucket is used.

.RE
\fB\-\-image\-url\fR \fIIMAGE_URL\fR
.RS 2m
Deploy with a specific Docker image. Docker url must be from one of the valid
gcr hostnames.

.RE
\fB\-\-promote\fR
.RS 2m
Promote the deployed version to receive all traffic.

True by default. To change the default behavior for your current environment,
run:

.RS 2m
$ gcloud config set app/promote_by_default false
.RE

Overrides the default \fBpromote_by_default\fR property value for this command
invocation. Use \fB\-\-no\-promote\fR to disable.

.RE
\fB\-\-stop\-previous\-version\fR
.RS 2m
Stop the previously running version when deploying a new version that receives
all traffic. Overrides the default \fBstop_previous_version\fR property value
for this command invocation. Use \fB\-\-no\-stop\-previous\-version\fR to
disable.

.RE
\fB\-\-version\fR \fIVERSION\fR, \fB\-v\fR \fIVERSION\fR
.RS 2m
The version of the app that will be created or replaced by this deployment. If
you do not specify a version, one will be generated for you.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To deploy a single service, run:

.RS 2m
$ gcloud app deploy ~/my_app/app.yaml
.RE

To deploy multiple services, run:

.RS 2m
$ gcloud app deploy ~/my_app/app.yaml ~/my_app/another_service.yaml
.RE
