
.TH "GCLOUD_SQL_INSTANCES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud sql instances describe \- retrieves information about a Cloud SQL instance



.SH "SYNOPSIS"
.HP
\f5gcloud sql instances describe\fR \fIINSTANCE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Retrieves information about a Cloud SQL instance.



.SH "POSITIONAL ARGUMENTS"

\fIINSTANCE\fR
.RS 2m
Cloud SQL instance ID.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
