
.TH "GCLOUD_DNS_RECORD\-SETS_TRANSACTION_ABORT" 1



.SH "NAME"
.HP
gcloud dns record\-sets transaction abort \- abort transaction



.SH "SYNOPSIS"
.HP
\f5gcloud dns record\-sets transaction abort\fR \fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR [\fB\-\-transaction\-file\fR\ \fITRANSACTION_FILE\fR;\ default="transaction.yaml"] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command aborts the transaction and deletes the transaction file.



.SH "REQUIRED FLAGS"

\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 2m
Name of the managed\-zone whose record\-sets you want to manage.


.RE

.SH "OPTIONAL FLAGS"

\fB\-\-transaction\-file\fR \fITRANSACTION_FILE\fR; default="transaction.yaml"
.RS 2m
Path of the file which contains the transaction.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To abort the transaction, run:

.RS 2m
$ gcloud dns record\-sets transaction abort \-z MANAGED_ZONE
.RE
