
.TH "GCLOUD_DATAPROC_OPERATIONS_DELETE" 1



.SH "NAME"
.HP
gcloud dataproc operations delete \- delete the record of an inactive operation



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc operations delete\fR \fIOPERATION\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete the record of an inactive operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
The ID of the operation to delete.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To delete the record of an operation, run:

.RS 2m
$ gcloud dataproc operations delete operation_id
.RE
