
.TH "GCLOUD_COMPUTE_INSTANCE\-TEMPLATES_DELETE" 1



.SH "NAME"
.HP
gcloud compute instance\-templates delete \- delete Google Compute Engine virtual machine instance templates



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-templates delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute instance\-templates delete\fR deletes one or more Google
Compute Engine virtual machine instance templates.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR [\fINAME\fR ...]
The resources to delete.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
