
.TH "GCLOUD_SERVICE\-MANAGEMENT_CHECK\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud service\-management check\-iam\-policy \- returns information about a member's permissions on a service



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management check\-iam\-policy\fR \fISERVICE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Returns information about a member's permissions on a service.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICE\fR
The name of the service for which to check the IAM policy.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
