
.TH "GCLOUD_AUTH" 1



.SH "NAME"
.HP
gcloud auth \- manage oauth2 credentials for the Google Cloud SDK



.SH "SYNOPSIS"
.HP
\f5gcloud auth\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage oauth2 credentials for the Google Cloud SDK.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBactivate\-service\-account\fR
.RS 2m
Authorize access to Google Cloud Platform using a service account.

.RE
\fBlist\fR
.RS 2m
Lists credentialed accounts.

.RE
\fBlogin\fR
.RS 2m
Authorize gcloud to access Google Cloud Platform.

.RE
\fBrevoke\fR
.RS 2m
Revoke access credentials for an account.
.RE
