
.TH "GCLOUD_DATAPROC_CLUSTERS_LIST" 1



.SH "NAME"
.HP
gcloud dataproc clusters list \- view a list of all clusters in a project



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc clusters list\fR [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

View a list of all clusters in a project.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To see the list of all clusters, run:

.RS 2m
$ gcloud dataproc clusters list
.RE
