
.TH "GCLOUD_KMS_LOCATIONS" 1



.SH "NAME"
.HP
gcloud kms locations \- view locations available for a project



.SH "SYNOPSIS"
.HP
\f5gcloud kms locations\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

View locations available for a project.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBlist\fR
List the project's locations.
.RE
.sp
