
.TH "GCLOUD_SERVICE\-MANAGEMENT_ENABLE" 1



.SH "NAME"
.HP
gcloud service\-management enable \- enables a service on the current project



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management enable\fR \fISERVICE\fR [\fB\-\-async\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Enables a service on the current project.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fISERVICE\fR
The name of the service to enable.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress and don't wait for the
operation to complete.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
