
.TH "GCLOUD_ML\-ENGINE_OPERATIONS_DELETE" 1



.SH "NAME"
.HP
gcloud ml\-engine operations delete \- delete a Cloud ML Engine operation



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine operations delete\fR \fIOPERATION\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete a Cloud ML Engine operation.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIOPERATION\fR
Name of the operation.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
