
.TH "GCLOUD_CONFIG_CONFIGURATIONS_LIST" 1



.SH "NAME"
.HP
gcloud config configurations list \- lists available named configurations



.SH "SYNOPSIS"
.HP
\f5gcloud config configurations list\fR [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

Lists available named configurations.

See \f5gcloud topic configurations\fR for an overview of named configurations.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To list all available configurations, run:

.RS 2m
$ gcloud config configurations list
.RE
