
.TH "GCLOUD_SOURCE_REPOS_CLONE" 1



.SH "NAME"
.HP
gcloud source repos clone \- clone a cloud source repository



.SH "SYNOPSIS"
.HP
\f5gcloud source repos clone\fR \fIREPOSITORY_NAME\fR [\fIDIRECTORY_NAME\fR] [\fB\-\-dry\-run\fR] [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

This command clones a git repository for the currently active Google Cloud
Platform project into the specified directory or into the current directory if
no target directory is specified. This command gives a warning if the cloud
source repository is a mirror.

The clone operation configures the local clone to use your gcloud credentials to
authenticate future git operations.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIREPOSITORY_NAME\fR
Name of the repository.

.TP 2m
[\fIDIRECTORY_NAME\fR]
Directory name for the cloned repo. Defaults to the repository name.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-dry\-run\fR
If provided, prints the command that would be run to standard out instead of
executing it.


.RE
.sp

.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.



.SH "EXAMPLES"

The example commands below show a sample workflow.

.RS 2m
$ gcloud init
$ gcloud source repos clone REPOSITORY_NAME DIRECTORY_NAME
$ cd DIRECTORY_NAME
... create/edit files and create one or more commits ...
$ git push origin master
.RE
