
.TH "GCLOUD_COMPUTE_REGIONS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute regions describe \- describe a Google Compute Engine region



.SH "SYNOPSIS"
.HP
\f5gcloud compute regions describe\fR \fINAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute regions describe\fR displays all data associated with a Google
Compute Engine region.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the resource to fetch.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
