
.TH "GCLOUD_SQL_TIERS_LIST" 1



.SH "NAME"
.HP
gcloud sql tiers list \- lists all available service tiers for Google Cloud SQL



.SH "SYNOPSIS"
.HP
\f5gcloud sql tiers list\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Lists all available service tiers for Google Cloud SQL.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
