
.TH "GCLOUD_ML\-ENGINE_VERSIONS_DELETE" 1



.SH "NAME"
.HP
gcloud ml\-engine versions delete \- delete an existing Cloud ML Engine version



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine versions delete\fR \fIVERSION\fR \fB\-\-model\fR=\fIMODEL\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Delete an existing Cloud ML Engine version.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIVERSION\fR
Name of the model version.


.RE
.sp

.SH "REQUIRED FLAGS"

.RS 2m
.TP 2m
\fB\-\-model\fR=\fIMODEL\fR
Name of the model.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
