
.TH "GCLOUD_SPANNER_INSTANCE\-CONFIGS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud spanner instance\-configs describe \- describe a Cloud Spanner instance config



.SH "SYNOPSIS"
.HP
\f5gcloud spanner instance\-configs describe\fR \fIINSTANCE\-CONFIG\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Describe a Cloud Spanner instance config.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIINSTANCE\-CONFIG\fR
Cloud Spanner instance config.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
