
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_SET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud iam service\-accounts set\-iam\-policy \- set IAM policy for a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts set\-iam\-policy\fR \fIIAM\-ACCOUNT\fR \fIPOLICY\-FILE\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command sets the IAM policy for a service account, given an IAM\-ACCOUNT
and a file that contains the JSON encoded IAM policy.



.SH "POSITIONAL ARGUMENTS"

\fIIAM\-ACCOUNT\fR
.RS 2m
The service account whose policy to set.

.RE
\fIPOLICY\-FILE\fR
.RS 2m
Path to a local JSON formatted file containing a valid policy.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

The following command will read an IAM policy defined in a JSON file
\'policy.json' and set it for a service account with identifier
\'my\-iam\-account@somedomain.com'

.RS 2m
$ gcloud iam service\-accounts set\-iam\-policy \e
    my\-iam\-account@somedomain.com policy.json
.RE

See https://cloud.google.com/iam/docs/managing\-policies for details of the
policy file format and contents.
