
.TH "GCLOUD_PROJECTS_LIST" 1



.SH "NAME"
.HP
gcloud projects list \- list all active Projects



.SH "SYNOPSIS"
.HP
\f5gcloud projects list\fR [\fB\-\-limit\fR\ \fILIMIT\fR] [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

\fBgcloud projects list\fR lists all active Projects (ID and title), for the
active user's credentials, in alphabetical order by Project title. Projects
which have been deleted or are pending deletion will not be included.

You can specify the maximum number of Projects to list with the 'limit' flag.



.SH "FLAGS"

\fB\-\-limit\fR \fILIMIT\fR
.RS 2m
Maximum number of results.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

The following command will list a maximum of 5 Projects, out of all of the
active user's active Projects, sorted alphabetically by title.

.RS 2m
$ gcloud projects list \-\-limit=5
.RE
