
.TH "GCLOUD_DATAPROC_CLUSTERS_UPDATE" 1



.SH "NAME"
.HP
gcloud dataproc clusters update \- update the number of worker nodes in a cluster



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc clusters update\fR \fINAME\fR [\fB\-\-async\fR] [\fB\-\-num\-preemptible\-workers\fR=\fINUM_PREEMPTIBLE_WORKERS\fR] [\fB\-\-num\-workers\fR=\fINUM_WORKERS\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Update the number of worker nodes in a cluster.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the cluster to update.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-async\fR
Display information about the operation in progress and don't wait for the
operation to complete.

.TP 2m
\fB\-\-num\-preemptible\-workers\fR=\fINUM_PREEMPTIBLE_WORKERS\fR
The new number of preemptible worker nodes in the cluster.

.TP 2m
\fB\-\-num\-workers\fR=\fINUM_WORKERS\fR
The new number of worker nodes in the cluster.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To resize a cluster, run:

.RS 2m
$ gcloud dataproc clusters update my_cluster \-\-num\-workers 5
.RE

To change the number preemptible workers in a cluster, run:

.RS 2m
$ gcloud dataproc clusters update my_cluster \e
    \-\-num\-preemptible\-workers 5
.RE
