
.TH "GCLOUD_DATAPROC" 1



.SH "NAME"
.HP
gcloud dataproc \- create and manage Google Cloud Dataproc clusters and jobs



.SH "SYNOPSIS"
.HP
\f5gcloud dataproc\fR \fIGROUP\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Create and manage Google Cloud Dataproc clusters and jobs.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

\fBclusters\fR
.RS 2m
Create and manage Google Cloud Dataproc clusters.

.RE
\fBjobs\fR
.RS 2m
Submit and manage Google Cloud Dataproc jobs.

.RE
\fBoperations\fR
.RS 2m
View and manage Google Cloud Dataproc operations.


.RE

.SH "EXAMPLES"

To see how to create and manage clusters, run:

.RS 2m
$ gcloud dataproc clusters
.RE

To see how to submit and manage jobs, run:

.RS 2m
$ gcloud dataproc jobs
.RE
