
.TH "GCLOUD_DATAFLOW_JOBS_CANCEL" 1



.SH "NAME"
.HP
gcloud dataflow jobs cancel \- cancels all jobs that match the command line arguments



.SH "SYNOPSIS"
.HP
\f5gcloud dataflow jobs cancel\fR \fIJOB\fR [\fIJOB\fR\ ...] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Cancels all jobs that match the command line arguments.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB\fR [\fIJOB\fR ...]
The jobs to operate on.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
