
.TH "GCLOUD_SERVICE\-MANAGEMENT_OPERATIONS" 1



.SH "NAME"
.HP
gcloud service\-management operations \- manage Operation for various services



.SH "SYNOPSIS"
.HP
\f5gcloud service\-management operations\fR \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Manage Operation for various services.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

.RS 2m
.TP 2m
\fBdescribe\fR
Describes an operation resource for a given operation name.

.TP 2m
\fBwait\fR
Waits for an operation to complete.
.RE
.sp
