
.TH "GCLOUD_ML\-ENGINE_INIT\-PROJECT" 1



.SH "NAME"
.HP
gcloud ml\-engine init\-project \- initialize project for Cloud ML Engine



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine init\-project\fR [\fIGCLOUD_WIDE_FLAG\ ...\fR]



.SH "DESCRIPTION"

\fB(DEPRECATED)\fR The \f5init\-project\fR command is deprecated and will be
removed in the 160.0.0 Cloud SDK release. This command is no longer necessary;
Cloud ML Engine will work without having run it.

gcloud ml\-engine init\-project initializes the current project for use with
Google Cloud Machine Learning Engine. Specifically, it adds the required Cloud
Machine Learning Engine service accounts to the current project as editors.



.SH "GCLOUD WIDE FLAGS"

These flags are available to all commands: \-\-account, \-\-configuration,
\-\-flatten, \-\-format, \-\-help, \-\-log\-http, \-\-project, \-\-quiet,
\-\-trace\-token, \-\-user\-output\-enabled, \-\-verbosity. Run \fB$ gcloud
help\fR for details.
