
.TH "GCLOUD_VERSION" 1



.SH "NAME"
.HP
gcloud version \- print version information for Cloud SDK components



.SH "SYNOPSIS"
.HP
\f5gcloud version\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command prints version information for each installed Cloud SDK component
and prints a message if updates are available.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
