
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS" 1



.SH "NAME"
.HP
gcloud iam service\-accounts \- create and manipulate service accounts



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Create and manipulate service accounts.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

\fBkeys\fR
.RS 2m
Manage service account keys.


.RE

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBadd\-iam\-policy\-binding\fR
.RS 2m
Add IAM policy binding for a service account.

.RE
\fBcreate\fR
.RS 2m
Create an service account for a project.

.RE
\fBdelete\fR
.RS 2m
Delete a service account from a project.

.RE
\fBdescribe\fR
.RS 2m
Show metadata for a service account from a project.

.RE
\fBget\-iam\-policy\fR
.RS 2m
Get the IAM policy for a service account.

.RE
\fBlist\fR
.RS 2m
List all of a project's service accounts.

.RE
\fBremove\-iam\-policy\-binding\fR
.RS 2m
Remove IAM policy binding for a service account.

.RE
\fBset\-iam\-policy\fR
.RS 2m
Set IAM policy for a service account.

.RE
\fBsign\-blob\fR
.RS 2m
Sign a blob with a managed service account key.

.RE
\fBupdate\fR
.RS 2m
Update the metadata of an IAM service account.
.RE
