
.TH "GCLOUD_CONTAINER_OPERATIONS_WAIT" 1



.SH "NAME"
.HP
gcloud container operations wait \- poll an operation for completion



.SH "SYNOPSIS"
.HP
\f5gcloud container operations wait\fR \fIOPERATION_ID\fR [\fB\-\-zone\fR\ \fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Poll an operation for completion.



.SH "POSITIONAL ARGUMENTS"

\fIOPERATION_ID\fR
.RS 2m
The operation id to poll.


.RE

.SH "FLAGS"

\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 2m
The compute zone (e.g. us\-central1\-a) for the cluster


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
