
.TH "GCLOUD_COMPUTE_INSTANCE\-TEMPLATES_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute instance\-templates describe \- describe a virtual machine instance template



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-templates describe\fR \fINAME\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute instance\-templates describe\fR displays all data associated
with a Google Compute Engine virtual machine instance template.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the resource to fetch.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
