
.TH "GCLOUD_COMPUTE_BACKEND\-BUCKETS_UPDATE" 1



.SH "NAME"
.HP
gcloud compute backend\-buckets update \- update a backend bucket



.SH "SYNOPSIS"
.HP
\f5gcloud compute backend\-buckets update\fR \fINAME\fR [\fB\-\-description\fR=\fIDESCRIPTION\fR] [\fB\-\-enable\-cdn\fR] [\fB\-\-gcs\-bucket\-name\fR=\fIGCS_BUCKET_NAME\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute backend\-buckets update\fR is used to update backend buckets.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fINAME\fR
The name of the backend bucket.


.RE
.sp

.SH "FLAGS"

.RS 2m
.TP 2m
\fB\-\-description\fR=\fIDESCRIPTION\fR
An optional, textual description for the backend bucket.

.TP 2m
\fB\-\-enable\-cdn\fR
Enable Cloud CDN for the backend bucket. Cloud CDN can cache HTTP responses from
a backend bucket at the edge of the network, close to users.

.TP 2m
\fB\-\-gcs\-bucket\-name\fR=\fIGCS_BUCKET_NAME\fR
The name of the Google Cloud Storage bucket to serve from. The storage bucket
must be owned by the project's owner.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
