
.TH "GCLOUD_COMPONENTS_REPOSITORIES_LIST" 1



.SH "NAME"
.HP
gcloud components repositories list \- list any Trusted Tester component repositories you have registered



.SH "SYNOPSIS"
.HP
\f5gcloud components repositories list\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

List all Trusted Tester component repositories that are registered with the
component manager. If you have additional repositories, the component manager
will look at them to discover additional components to install, or different
versions of existing components that are available.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
