
.TH "GCLOUD_COMPUTE_ROUTERS_UPDATE\-BGP\-PEER" 1



.SH "NAME"
.HP
gcloud compute routers update\-bgp\-peer \- update a BGP peer on a router



.SH "SYNOPSIS"
.HP
\f5gcloud compute routers update\-bgp\-peer\fR \fINAME\fR \fB\-\-peer\-name\fR \fIPEER_NAME\fR [\fB\-\-advertised\-route\-priority\fR\ \fIADVERTISED_ROUTE_PRIORITY\fR] [\fB\-\-interface\fR\ \fIINTERFACE\fR] [\fB\-\-ip\-address\fR\ \fIIP_ADDRESS\fR] [\fB\-\-peer\-asn\fR\ \fIPEER_ASN\fR] [\fB\-\-peer\-ip\-address\fR\ \fIPEER_IP_ADDRESS\fR] [\fB\-\-region\fR\ \fIREGION\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute routers update\-bgp\-peer\fR is used to update a BGP peer on a
router.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the router.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-peer\-name\fR \fIPEER_NAME\fR
.RS 2m
The name of the peer being modified.


.RE

.SH "OPTIONAL FLAGS"

\fB\-\-advertised\-route\-priority\fR \fIADVERTISED_ROUTE_PRIORITY\fR
.RS 2m
The priority of routes advertised to this BGP peer. In the case where there is
more than one matching route of maximum length, the routes with lowest priority
value win. 0 <= priority <= 65535.

.RE
\fB\-\-interface\fR \fIINTERFACE\fR
.RS 2m
The new interface of the peer being modified.

.RE
\fB\-\-ip\-address\fR \fIIP_ADDRESS\fR
.RS 2m
The new link local address of the router for this peer.

.RE
\fB\-\-peer\-asn\fR \fIPEER_ASN\fR
.RS 2m
The new asn of the peer being modified.

.RE
\fB\-\-peer\-ip\-address\fR \fIPEER_IP_ADDRESS\fR
.RS 2m
The new link local address of the peer.

.RE
\fB\-\-region\fR \fIREGION\fR
.RS 2m
The region of the router to update. If not specified, you will be prompted to
select a region.

To avoid prompting when this flag is omitted, you can set the
\f5\fIcompute/region\fR\fR property:

.RS 2m
$ gcloud config set compute/region REGION
.RE

A list of regions can be fetched by running:

.RS 2m
$ gcloud compute regions list
.RE

To unset the property, run:

.RS 2m
$ gcloud config unset compute/region
.RE

Alternatively, the region can be stored in the environment variable
\f5\fICLOUDSDK_COMPUTE_REGION\fR\fR.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
