
.TH "GCLOUD_COMPUTE_SNAPSHOTS_DELETE" 1



.SH "NAME"
.HP
gcloud compute snapshots delete \- delete Google Compute Engine snapshots



.SH "SYNOPSIS"
.HP
\f5gcloud compute snapshots delete\fR \fINAME\fR [\fINAME\fR\ ...] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute snapshots delete\fR deletes one or more Google Compute Engine.RS 2m
snapshots.

.RE



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR [\fINAME\fR ...]
.RS 2m
The resources to delete.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
