
.TH "GCLOUD_ML\-ENGINE_JOBS_CANCEL" 1



.SH "NAME"
.HP
gcloud ml\-engine jobs cancel \- cancel a running Cloud ML Engine job



.SH "SYNOPSIS"
.HP
\f5gcloud ml\-engine jobs cancel\fR \fIJOB\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud ml\-engine jobs cancel\fR cancels a running Cloud ML Engine job. If
the job is already finished, the command will not perform an operation and exit
successfully.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIJOB\fR
Name of the job.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
