
.TH "GCLOUD_ORGANIZATIONS_GET\-IAM\-POLICY" 1



.SH "NAME"
.HP
gcloud organizations get\-iam\-policy \- get IAM policy for an organization



.SH "SYNOPSIS"
.HP
\f5gcloud organizations get\-iam\-policy\fR \fIORGANIZATION_ID\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Gets the IAM policy for an organization, given an organization ID.



.SH "POSITIONAL ARGUMENTS"

.RS 2m
.TP 2m
\fIORGANIZATION_ID\fR
ID for the organization whose policy you want to get.


.RE
.sp

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

The following command prints the IAM policy for an organization with the ID
\f5123456789\fR:

.RS 2m
$ gcloud organizations get\-iam\-policy 123456789
.RE
