
.TH "GCLOUD_IAM_SERVICE\-ACCOUNTS_KEYS_CREATE" 1



.SH "NAME"
.HP
gcloud iam service\-accounts keys create \- create a private key for a service account



.SH "SYNOPSIS"
.HP
\f5gcloud iam service\-accounts keys create\fR \fIOUTPUT\-FILE\fR \fB\-\-iam\-account\fR \fIIAM_ACCOUNT\fR [\fB\-\-key\-file\-type\fR\ \fIKEY_FILE_TYPE\fR;\ default="json"] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Create a private key for a service account.



.SH "POSITIONAL ARGUMENTS"

\fIOUTPUT\-FILE\fR
.RS 2m
The path where the resulting private key should be written.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-iam\-account\fR \fIIAM_ACCOUNT\fR
.RS 2m
The service account for which to create a key.


.RE

.SH "OPTIONAL FLAGS"

\fB\-\-key\-file\-type\fR \fIKEY_FILE_TYPE\fR; default="json"
.RS 2m
The type of key to create. Can be either "json" or "p12". When unspecified,
defaults to "json".


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To create a new private key for a service account, and save a copy of it
locally, run:

.RS 2m
$ gcloud iam service\-accounts keys create \e
    \-\-iam\-account my\-iam\-account@somedomain.com key.json
.RE
