
.TH "GCLOUD_AUTH_ACTIVATE\-SERVICE\-ACCOUNT" 1



.SH "NAME"
.HP
gcloud auth activate\-service\-account \- get credentials via the private key for a service account



.SH "SYNOPSIS"
.HP
\f5gcloud auth activate\-service\-account\fR [\fIACCOUNT\fR] \fB\-\-key\-file\fR \fIKEY_FILE\fR [\fB\-\-password\-file\fR\ \fIPASSWORD_FILE\fR\ |\ \fB\-\-prompt\-for\-password\fR] [\fIGLOBAL\-FLAG\ ...\fR]


.SH "DESCRIPTION"

Get credentials for a service account, using a .json file or a .p12 file for the
private key. Password is only applicable for .p12 file. If \-\-project is set,
set the default project.



.SH "POSITIONAL ARGUMENTS"

[\fIACCOUNT\fR]
.RS 2m
The email for the service account.


.RE

.SH "FLAGS"

\fB\-\-key\-file\fR \fIKEY_FILE\fR
.RS 2m
Path to the service accounts private key.

.RE
\fB\-\-password\-file\fR \fIPASSWORD_FILE\fR
.RS 2m
Path to a file containing the password for the service account private key (only
for .p12 file).

.RE
\fB\-\-prompt\-for\-password\fR
.RS 2m
Prompt for the password for the service account private key (only for .p12
file).


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
