
.TH "GCLOUD_COMPUTE_NETWORKS" 1



.SH "NAME"
.HP
gcloud compute networks \- list, create, and delete Google Compute Engine networks



.SH "SYNOPSIS"
.HP
\f5gcloud compute networks\fR \fIGROUP\fR | \fICOMMAND\fR [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

List, create, and delete Google Compute Engine networks.



.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "GROUPS"

\f5\fIGROUP\fR\fR is one of the following:

\fBsubnets\fR
.RS 2m
List, describe, and delete Google Compute Engine subnetworks.


.RE

.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBcreate\fR
.RS 2m
Create a Google Compute Engine network.

.RE
\fBdelete\fR
.RS 2m
Delete Google Compute Engine networks.

.RE
\fBdescribe\fR
.RS 2m
Describe a Google Compute Engine network.

.RE
\fBlist\fR
.RS 2m
List Google Compute Engine networks.
.RE
