
.TH "GCLOUD_CONTAINER_CLUSTERS" 1



.SH "NAME"
.HP
gcloud container clusters \- deploy and teardown Google Container Engine clusters



.SH "SYNOPSIS"
.HP
\f5gcloud container clusters\fR \fICOMMAND\fR [\fB\-\-zone\fR\ \fIZONE\fR,\ \fB\-z\fR\ \fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

Deploy and teardown Google Container Engine clusters.



.SH "FLAGS"

\fB\-\-zone\fR \fIZONE\fR, \fB\-z\fR \fIZONE\fR
.RS 2m
The compute zone (e.g. us\-central1\-a) for the cluster


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "COMMANDS"

\f5\fICOMMAND\fR\fR is one of the following:

\fBcreate\fR
.RS 2m
Create a cluster for running containers.

.RE
\fBdelete\fR
.RS 2m
Delete an existing cluster for running containers.

.RE
\fBdescribe\fR
.RS 2m
Describe an existing cluster for running containers.

.RE
\fBget\-credentials\fR
.RS 2m
Fetch credentials for a running cluster.

.RE
\fBlist\fR
.RS 2m
List existing clusters for running containers.

.RE
\fBresize\fR
.RS 2m
Resizes an existing cluster for running containers.

.RE
\fBupdate\fR
.RS 2m
Update cluster settings for an existing container cluster.

.RE
\fBupgrade\fR
.RS 2m
Upgrade the Kubernetes version of an existing container cluster.
.RE
