
.TH "GCLOUD_INFO" 1



.SH "NAME"
.HP
gcloud info \- display information about the current gcloud environment



.SH "SYNOPSIS"
.HP
\f5gcloud info\fR [\fB\-\-show\-log\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

This command displays information about the current gcloud environment.



.SH "FLAGS"

\fB\-\-show\-log\fR
.RS 2m
Print the contents of the last log file.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.
