
.TH "GCLOUD_COMPUTE_URL\-MAPS_ADD\-PATH\-MATCHER" 1



.SH "NAME"
.HP
gcloud compute url\-maps add\-path\-matcher \- add a path matcher to a URL map



.SH "SYNOPSIS"
.HP
\f5gcloud compute url\-maps add\-path\-matcher\fR \fINAME\fR \fB\-\-default\-service\fR \fIDEFAULT_SERVICE\fR \fB\-\-path\-matcher\-name\fR \fIPATH_MATCHER_NAME\fR [\fB\-\-delete\-orphaned\-path\-matcher\fR] [\fB\-\-description\fR\ \fIDESCRIPTION\fR] [\fB\-\-existing\-host\fR\ \fIEXISTING_HOST\fR\ |\ \fB\-\-new\-hosts\fR\ \fINEW_HOST\fR,[\fINEW_HOST\fR,...]] [\fB\-\-path\-rules\fR\ \fIPATH\fR=\fISERVICE\fR,[\fIPATH\fR=\fISERVICE\fR,...]] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute url\-maps add\-path\-matcher\fR is used to add a path matcher
to a URL map. A path matcher maps HTTP request paths to backend services. Each
path matcher must be referenced by at least one host rule. This command can
create a new host rule through the \f5\fI\-\-new\-hosts\fR\fR flag or it can
reconfigure an existing host rule to point to the newly added path matcher using
\f5\fI\-\-existing\-host\fR\fR. In the latter case, if a path matcher is
orphaned as a result of the operation, this command will fail unless
\f5\fI\-\-delete\-orphaned\-path\-matcher\fR\fR is provided.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the URL map.


.RE

.SH "REQUIRED FLAGS"

\fB\-\-default\-service\fR \fIDEFAULT_SERVICE\fR
.RS 2m
A backend service that will be used for requests that the path matcher cannot
match.

.RE
\fB\-\-path\-matcher\-name\fR \fIPATH_MATCHER_NAME\fR
.RS 2m
The name to assign to the path matcher.


.RE

.SH "OPTIONAL FLAGS"

\fB\-\-delete\-orphaned\-path\-matcher\fR
.RS 2m
If provided and a path matcher is orphaned as a result of this command, the
command removes the orphaned path matcher instead of failing.

.RE
\fB\-\-description\fR \fIDESCRIPTION\fR
.RS 2m
An optional, textual description for the path matcher.

.RE
\fB\-\-existing\-host\fR \fIEXISTING_HOST\fR
.RS 2m
An existing host rule to tie the new path matcher to. Although host rules can
contain more than one host, only a single host is needed to uniquely identify
the host rule.

.RE
\fB\-\-new\-hosts\fR \fINEW_HOST\fR,[\fINEW_HOST\fR,...]
.RS 2m
If specified, a new host rule with the given hosts is created and the path
matcher is tied to the new host rule.

.RE
\fB\-\-path\-rules\fR \fIPATH\fR=\fISERVICE\fR,[\fIPATH\fR=\fISERVICE\fR,...]
.RS 2m
Rules for mapping request paths to services.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To create a rule for mapping the path \f5/search/*\fR to the hypothetical
\f5search\-service\fR and \f5/images/*\fR to the \f5images\-service\fR under the
hosts \f5google.com\fR and \f5*.google.com\fR, run:

.RS 2m
$ gcloud compute url\-maps add\-path\-matcher MY\-URL\-MAP \e
    \-\-path\-matcher\-name MY\-MATCHER \e
    \-\-default\-service MY\-DEFAULT\-SERVICE \e
    \-\-path\-rules \e
    '/search/*=search_service,/images/*=images\-service' \e
    \-\-new\-hosts 'google.com,*.google.com'
.RE

Note that a default service must be provided to handle paths for which there is
no mapping.
