
.TH "GCLOUD_COMPUTE_INSTANCE\-GROUPS_DESCRIBE" 1



.SH "NAME"
.HP
gcloud compute instance\-groups describe \- display detailed information about an instance group



.SH "SYNOPSIS"
.HP
\f5gcloud compute instance\-groups describe\fR \fINAME\fR [\fB\-\-region\fR=\fIREGION\fR\ |\ \fB\-\-zone\fR=\fIZONE\fR] [\fIGLOBAL\-FLAG\ ...\fR]



.SH "DESCRIPTION"

\fBgcloud compute instance\-groups describe\fR displays all data associated with
an instance group in a project.



.SH "POSITIONAL ARGUMENTS"

\fINAME\fR
.RS 2m
The name of the resource to fetch.


.RE

.SH "FLAGS"

At most one of these may be specified:

\fB\-\-region\fR=\fIREGION\fR
.RS 2m
The region of the resource to fetch.

.RE
\fB\-\-zone\fR=\fIZONE\fR
.RS 2m
The zone of the resource to fetch.


.RE

.SH "GLOBAL FLAGS"

Run \fB$ gcloud help\fR for a description of flags available to all commands.



.SH "EXAMPLES"

To get details about a regional instance group in the \f5\fIus\-central1\fR\fR
regions, run:

.RS 2m
$ gcloud compute instance\-groups describe \-\-region us\-central1
.RE

To get details about a zonal instance group in the \f5\fIus\-central1\-b\fR\fR
zone, run:

.RS 2m
$ gcloud compute instance\-groups describe \-\-zone us\-central1\-b
.RE
