"""Generated client library for servicehealth version v1."""
# NOTE: This file is autogenerated and should not be edited by hand.

from apitools.base.py import base_api
from googlecloudsdk.generated_clients.apis.servicehealth.v1 import servicehealth_v1_messages as messages


class ServicehealthV1(base_api.BaseApiClient):
  """Generated client library for service servicehealth version v1."""

  MESSAGES_MODULE = messages
  BASE_URL = 'https://servicehealth.googleapis.com/'
  MTLS_BASE_URL = 'https://servicehealth.mtls.googleapis.com/'

  _PACKAGE = 'servicehealth'
  _SCOPES = ['https://www.googleapis.com/auth/cloud-platform']
  _VERSION = 'v1'
  _CLIENT_ID = 'CLIENT_ID'
  _CLIENT_SECRET = 'CLIENT_SECRET'
  _USER_AGENT = 'google-cloud-sdk'
  _CLIENT_CLASS_NAME = 'ServicehealthV1'
  _URL_VERSION = 'v1'
  _API_KEY = None

  def __init__(self, url='', credentials=None,
               get_credentials=True, http=None, model=None,
               log_request=False, log_response=False,
               credentials_args=None, default_global_params=None,
               additional_http_headers=None, response_encoding=None):
    """Create a new servicehealth handle."""
    url = url or self.BASE_URL
    super(ServicehealthV1, self).__init__(
        url, credentials=credentials,
        get_credentials=get_credentials, http=http, model=model,
        log_request=log_request, log_response=log_response,
        credentials_args=credentials_args,
        default_global_params=default_global_params,
        additional_http_headers=additional_http_headers,
        response_encoding=response_encoding)
    self.organizations_locations_organizationEvents = self.OrganizationsLocationsOrganizationEventsService(self)
    self.organizations_locations_organizationImpacts = self.OrganizationsLocationsOrganizationImpactsService(self)
    self.organizations_locations = self.OrganizationsLocationsService(self)
    self.organizations = self.OrganizationsService(self)
    self.projects_locations_events = self.ProjectsLocationsEventsService(self)
    self.projects_locations = self.ProjectsLocationsService(self)
    self.projects = self.ProjectsService(self)

  class OrganizationsLocationsOrganizationEventsService(base_api.BaseApiService):
    """Service class for the organizations_locations_organizationEvents resource."""

    _NAME = 'organizations_locations_organizationEvents'

    def __init__(self, client):
      super(ServicehealthV1.OrganizationsLocationsOrganizationEventsService, self).__init__(client)
      self._upload_configs = {
          }

    def Get(self, request, global_params=None):
      r"""Retrieves a resource containing information about an event affecting an organization.

      Args:
        request: (ServicehealthOrganizationsLocationsOrganizationEventsGetRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments
      Returns:
        (OrganizationEvent) The response message.
      """
      config = self.GetMethodConfig('Get')
      return self._RunMethod(
          config, request, global_params=global_params)

    Get.method_config = lambda: base_api.ApiMethodInfo(
        flat_path='v1/organizations/{organizationsId}/locations/{locationsId}/organizationEvents/{organizationEventsId}',
        http_method='GET',
        method_id='servicehealth.organizations.locations.organizationEvents.get',
        ordered_params=['name'],
        path_params=['name'],
        query_params=[],
        relative_path='v1/{+name}',
        request_field='',
        request_type_name='ServicehealthOrganizationsLocationsOrganizationEventsGetRequest',
        response_type_name='OrganizationEvent',
        supports_download=False,
    )

    def List(self, request, global_params=None):
      r"""Lists organization events under a given organization and location.

      Args:
        request: (ServicehealthOrganizationsLocationsOrganizationEventsListRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments
      Returns:
        (ListOrganizationEventsResponse) The response message.
      """
      config = self.GetMethodConfig('List')
      return self._RunMethod(
          config, request, global_params=global_params)

    List.method_config = lambda: base_api.ApiMethodInfo(
        flat_path='v1/organizations/{organizationsId}/locations/{locationsId}/organizationEvents',
        http_method='GET',
        method_id='servicehealth.organizations.locations.organizationEvents.list',
        ordered_params=['parent'],
        path_params=['parent'],
        query_params=['filter', 'pageSize', 'pageToken', 'view'],
        relative_path='v1/{+parent}/organizationEvents',
        request_field='',
        request_type_name='ServicehealthOrganizationsLocationsOrganizationEventsListRequest',
        response_type_name='ListOrganizationEventsResponse',
        supports_download=False,
    )

  class OrganizationsLocationsOrganizationImpactsService(base_api.BaseApiService):
    """Service class for the organizations_locations_organizationImpacts resource."""

    _NAME = 'organizations_locations_organizationImpacts'

    def __init__(self, client):
      super(ServicehealthV1.OrganizationsLocationsOrganizationImpactsService, self).__init__(client)
      self._upload_configs = {
          }

    def Get(self, request, global_params=None):
      r"""Retrieves a resource containing information about impact to an asset under an organization affected by a service health event.

      Args:
        request: (ServicehealthOrganizationsLocationsOrganizationImpactsGetRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments
      Returns:
        (OrganizationImpact) The response message.
      """
      config = self.GetMethodConfig('Get')
      return self._RunMethod(
          config, request, global_params=global_params)

    Get.method_config = lambda: base_api.ApiMethodInfo(
        flat_path='v1/organizations/{organizationsId}/locations/{locationsId}/organizationImpacts/{organizationImpactsId}',
        http_method='GET',
        method_id='servicehealth.organizations.locations.organizationImpacts.get',
        ordered_params=['name'],
        path_params=['name'],
        query_params=[],
        relative_path='v1/{+name}',
        request_field='',
        request_type_name='ServicehealthOrganizationsLocationsOrganizationImpactsGetRequest',
        response_type_name='OrganizationImpact',
        supports_download=False,
    )

    def List(self, request, global_params=None):
      r"""Lists assets impacted by organization events under a given organization and location.

      Args:
        request: (ServicehealthOrganizationsLocationsOrganizationImpactsListRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments
      Returns:
        (ListOrganizationImpactsResponse) The response message.
      """
      config = self.GetMethodConfig('List')
      return self._RunMethod(
          config, request, global_params=global_params)

    List.method_config = lambda: base_api.ApiMethodInfo(
        flat_path='v1/organizations/{organizationsId}/locations/{locationsId}/organizationImpacts',
        http_method='GET',
        method_id='servicehealth.organizations.locations.organizationImpacts.list',
        ordered_params=['parent'],
        path_params=['parent'],
        query_params=['filter', 'pageSize', 'pageToken'],
        relative_path='v1/{+parent}/organizationImpacts',
        request_field='',
        request_type_name='ServicehealthOrganizationsLocationsOrganizationImpactsListRequest',
        response_type_name='ListOrganizationImpactsResponse',
        supports_download=False,
    )

  class OrganizationsLocationsService(base_api.BaseApiService):
    """Service class for the organizations_locations resource."""

    _NAME = 'organizations_locations'

    def __init__(self, client):
      super(ServicehealthV1.OrganizationsLocationsService, self).__init__(client)
      self._upload_configs = {
          }

  class OrganizationsService(base_api.BaseApiService):
    """Service class for the organizations resource."""

    _NAME = 'organizations'

    def __init__(self, client):
      super(ServicehealthV1.OrganizationsService, self).__init__(client)
      self._upload_configs = {
          }

  class ProjectsLocationsEventsService(base_api.BaseApiService):
    """Service class for the projects_locations_events resource."""

    _NAME = 'projects_locations_events'

    def __init__(self, client):
      super(ServicehealthV1.ProjectsLocationsEventsService, self).__init__(client)
      self._upload_configs = {
          }

    def Get(self, request, global_params=None):
      r"""Retrieves a resource containing information about an event.

      Args:
        request: (ServicehealthProjectsLocationsEventsGetRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments
      Returns:
        (Event) The response message.
      """
      config = self.GetMethodConfig('Get')
      return self._RunMethod(
          config, request, global_params=global_params)

    Get.method_config = lambda: base_api.ApiMethodInfo(
        flat_path='v1/projects/{projectsId}/locations/{locationsId}/events/{eventsId}',
        http_method='GET',
        method_id='servicehealth.projects.locations.events.get',
        ordered_params=['name'],
        path_params=['name'],
        query_params=[],
        relative_path='v1/{+name}',
        request_field='',
        request_type_name='ServicehealthProjectsLocationsEventsGetRequest',
        response_type_name='Event',
        supports_download=False,
    )

    def List(self, request, global_params=None):
      r"""Lists events under a given project and location.

      Args:
        request: (ServicehealthProjectsLocationsEventsListRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments
      Returns:
        (ListEventsResponse) The response message.
      """
      config = self.GetMethodConfig('List')
      return self._RunMethod(
          config, request, global_params=global_params)

    List.method_config = lambda: base_api.ApiMethodInfo(
        flat_path='v1/projects/{projectsId}/locations/{locationsId}/events',
        http_method='GET',
        method_id='servicehealth.projects.locations.events.list',
        ordered_params=['parent'],
        path_params=['parent'],
        query_params=['filter', 'pageSize', 'pageToken', 'view'],
        relative_path='v1/{+parent}/events',
        request_field='',
        request_type_name='ServicehealthProjectsLocationsEventsListRequest',
        response_type_name='ListEventsResponse',
        supports_download=False,
    )

  class ProjectsLocationsService(base_api.BaseApiService):
    """Service class for the projects_locations resource."""

    _NAME = 'projects_locations'

    def __init__(self, client):
      super(ServicehealthV1.ProjectsLocationsService, self).__init__(client)
      self._upload_configs = {
          }

    def Get(self, request, global_params=None):
      r"""Gets information about a location.

      Args:
        request: (ServicehealthProjectsLocationsGetRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments
      Returns:
        (GoogleCloudLocationLocation) The response message.
      """
      config = self.GetMethodConfig('Get')
      return self._RunMethod(
          config, request, global_params=global_params)

    Get.method_config = lambda: base_api.ApiMethodInfo(
        flat_path='v1/projects/{projectsId}/locations/{locationsId}',
        http_method='GET',
        method_id='servicehealth.projects.locations.get',
        ordered_params=['name'],
        path_params=['name'],
        query_params=[],
        relative_path='v1/{+name}',
        request_field='',
        request_type_name='ServicehealthProjectsLocationsGetRequest',
        response_type_name='GoogleCloudLocationLocation',
        supports_download=False,
    )

    def List(self, request, global_params=None):
      r"""Lists information about the supported locations for this service. This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: * **Global locations**: If `name` is empty, the method lists the public locations available to all projects. * **Project-specific locations**: If `name` follows the format `projects/{project}`, the method lists locations visible to that specific project. This includes public, private, or other project-specific locations enabled for the project. For gRPC and client library implementations, the resource name is passed as the `name` field. For direct service calls, the resource name is incorporated into the request path based on the specific service implementation and version.

      Args:
        request: (ServicehealthProjectsLocationsListRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments
      Returns:
        (ListLocationsResponse) The response message.
      """
      config = self.GetMethodConfig('List')
      return self._RunMethod(
          config, request, global_params=global_params)

    List.method_config = lambda: base_api.ApiMethodInfo(
        flat_path='v1/projects/{projectsId}/locations',
        http_method='GET',
        method_id='servicehealth.projects.locations.list',
        ordered_params=['name'],
        path_params=['name'],
        query_params=['extraLocationTypes', 'filter', 'pageSize', 'pageToken'],
        relative_path='v1/{+name}/locations',
        request_field='',
        request_type_name='ServicehealthProjectsLocationsListRequest',
        response_type_name='ListLocationsResponse',
        supports_download=False,
    )

  class ProjectsService(base_api.BaseApiService):
    """Service class for the projects resource."""

    _NAME = 'projects'

    def __init__(self, client):
      super(ServicehealthV1.ProjectsService, self).__init__(client)
      self._upload_configs = {
          }
