# proto-file: cloud/sdk/tools/poc/component_poc.proto
# proto-message: cloudsdk.PackagedComponentConfigFile

component: {

  component_name: 'gsutil'

  # Required, the site url of the team's internal doc.
  site_url: 'go/frostie'

  # Required, the team's product id which links to team's MOMA page,
  # eg. 1117694444248.
  teams_product_id: 1304534225748

  # Required, the developer mailing list for the team,
  # eg. fake-team@google.com.
  dev_mailing_list: 'frostie-icicle@google.com'

  # Required, the child Buganizer component IDs under
  # Cloud Platform > DevTools > gCloud CLI > Packaged Components > xxx
  # owned by the team,
  buganizer_component_ids: [46029]

  # Required, the date on which the config is last updated, eg. '2021-10-12`.
  last_updated_on: '2023-01-24'

  poc: {
    # Required. Must be a member on the team specified by teams_product_id.
    tech_lead: 'thomasmaclean'
  }

  # Notes

  # Readability Certified


}
