"""Generated client library for useronboarding version v1alpha."""
# NOTE: This file is autogenerated and should not be edited by hand.

from apitools.base.py import base_api
from googlecloudsdk.generated_clients.apis.useronboarding.v1alpha import useronboarding_v1alpha_messages as messages


class UseronboardingV1alpha(base_api.BaseApiClient):
  """Generated client library for service useronboarding version v1alpha."""

  MESSAGES_MODULE = messages
  BASE_URL = 'https://useronboarding.googleapis.com/'
  MTLS_BASE_URL = 'https://useronboarding.mtls.googleapis.com/'

  _PACKAGE = 'useronboarding'
  _SCOPES = ['https://www.googleapis.com/auth/cloud-platform']
  _VERSION = 'v1alpha'
  _CLIENT_ID = 'CLIENT_ID'
  _CLIENT_SECRET = 'CLIENT_SECRET'
  _USER_AGENT = 'google-cloud-sdk'
  _CLIENT_CLASS_NAME = 'UseronboardingV1alpha'
  _URL_VERSION = 'v1alpha'
  _API_KEY = None

  def __init__(self, url='', credentials=None,
               get_credentials=True, http=None, model=None,
               log_request=False, log_response=False,
               credentials_args=None, default_global_params=None,
               additional_http_headers=None, response_encoding=None):
    """Create a new useronboarding handle."""
    url = url or self.BASE_URL
    super(UseronboardingV1alpha, self).__init__(
        url, credentials=credentials,
        get_credentials=get_credentials, http=http, model=model,
        log_request=log_request, log_response=log_response,
        credentials_args=credentials_args,
        default_global_params=default_global_params,
        additional_http_headers=additional_http_headers,
        response_encoding=response_encoding)
    self.sessions = self.SessionsService(self)

  class SessionsService(base_api.BaseApiService):
    """Service class for the sessions resource."""

    _NAME = 'sessions'

    def __init__(self, client):
      super(UseronboardingV1alpha.SessionsService, self).__init__(client)
      self._upload_configs = {
          }

    def Get(self, request, global_params=None):
      r"""Gets an onboarding session by ID. The most recent snapshot of the session is returned. This method is designed to be called from the client to poll the session status and retrieve any pending user inputs. Returns NOT_FOUND error code if the specified session does not exist for the authenticated user.

      Args:
        request: (UseronboardingSessionsGetRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments
      Returns:
        (Session) The response message.
      """
      config = self.GetMethodConfig('Get')
      return self._RunMethod(
          config, request, global_params=global_params)

    Get.method_config = lambda: base_api.ApiMethodInfo(
        flat_path='v1alpha/sessions/{sessionsId}',
        http_method='GET',
        method_id='useronboarding.sessions.get',
        ordered_params=['name'],
        path_params=['name'],
        query_params=[],
        relative_path='v1alpha/{+name}',
        request_field='',
        request_type_name='UseronboardingSessionsGetRequest',
        response_type_name='Session',
        supports_download=False,
    )

    def Patch(self, request, global_params=None):
      r"""Updates an onboarding session with required input.

      The most recent snapshot of the session is returned. All fields of the
      Session resource are optional. Making several calls with identical values
      is allowed, in which case the first one is effective and subsequent ones
      are no-ops. Changing values between calls is not recommended. The service
      may be able to accept the update if it can be correctly processed within
      the ongoing session. Otherwise, the update will be rejected with an error.
      Returns NOT_FOUND error code if the specified session does not exist for
      the authenticated user.

      Args:
        request: (UseronboardingSessionsPatchRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments

      Returns:
        (Session) The response message.
      """
      config = self.GetMethodConfig('Patch')
      return self._RunMethod(
          config, request, global_params=global_params)

    Patch.method_config = lambda: base_api.ApiMethodInfo(
        flat_path='v1alpha/sessions/{sessionsId}',
        http_method='PATCH',
        method_id='useronboarding.sessions.patch',
        ordered_params=['name'],
        path_params=['name'],
        query_params=['updateMask'],
        relative_path='v1alpha/{+name}',
        request_field='session',
        request_type_name='UseronboardingSessionsPatchRequest',
        response_type_name='Session',
        supports_download=False,
    )

    def ResolveSession(self, request, global_params=None):
      r"""Resolves the specified intent into an onboarding session. If there is no active session that maps to the intent, a new session is created. The backend will not attempt to fulfill the intent, but will check if it is already fulfilled. This is useful to know whether onboarding is required at all for the user. The very first call of this endpoint for a user might take longer than subsequent calls for the same user. This is due to the time it takes to initialize a session which may include a fanout to other services.

      Args:
        request: (ResolveSessionRequest) input message
        global_params: (StandardQueryParameters, default: None) global arguments
      Returns:
        (ResolveSessionResponse) The response message.
      """
      config = self.GetMethodConfig('ResolveSession')
      return self._RunMethod(
          config, request, global_params=global_params)

    ResolveSession.method_config = lambda: base_api.ApiMethodInfo(
        http_method='POST',
        method_id='useronboarding.sessions.resolveSession',
        ordered_params=[],
        path_params=[],
        query_params=[],
        relative_path='v1alpha/sessions:resolveSession',
        request_field='<request>',
        request_type_name='ResolveSessionRequest',
        response_type_name='ResolveSessionResponse',
        supports_download=False,
    )
