"""Generated message classes for firebaserules version v1.

Creates and manages rules that determine when a Firebase Rules-enabled service
should permit a request.
"""
# NOTE: This file is autogenerated and should not be edited by hand.

from apitools.base.protorpclite import messages as _messages
from apitools.base.py import encoding
from apitools.base.py import extra_types


package = 'firebaserules'


class Arg(_messages.Message):
  r"""Arg matchers for the mock function.

  Fields:
    anyValue: Argument matches any value provided.
    exactValue: Argument exactly matches value provided.
  """

  anyValue = _messages.MessageField('Empty', 1)
  exactValue = _messages.MessageField('extra_types.JsonValue', 2)


class Empty(_messages.Message):
  r"""A generic empty message that you can re-use to avoid defining duplicated
  empty messages in your APIs. A typical example is to use it as the request
  or the response type of an API method. For instance: service Foo { rpc
  Bar(google.protobuf.Empty) returns (google.protobuf.Empty); }
  """



class ExpressionReport(_messages.Message):
  r"""Describes where in a file an expression is found and what it was
  evaluated to over the course of its use.

  Fields:
    children: Subexpressions
    sourcePosition: Position of expression in original rules source.
    values: Values that this expression evaluated to when encountered.
  """

  children = _messages.MessageField('ExpressionReport', 1, repeated=True)
  sourcePosition = _messages.MessageField('SourcePosition', 2)
  values = _messages.MessageField('ValueCount', 3, repeated=True)


class File(_messages.Message):
  r"""`File` containing source content.

  Fields:
    content: Required. Textual Content.
    fingerprint: Fingerprint (e.g. github sha) associated with the `File`.
    name: Required. File name.
  """

  content = _messages.StringField(1)
  fingerprint = _messages.BytesField(2)
  name = _messages.StringField(3)


class FirebaserulesProjectsReleasesDeleteRequest(_messages.Message):
  r"""A FirebaserulesProjectsReleasesDeleteRequest object.

  Fields:
    name: Required. Resource name for the `Release` to delete. Format:
      `projects/{project_id}/releases/{release_id}`
  """

  name = _messages.StringField(1, required=True)


class FirebaserulesProjectsReleasesGetExecutableRequest(_messages.Message):
  r"""A FirebaserulesProjectsReleasesGetExecutableRequest object.

  Enums:
    ExecutableVersionValueValuesEnum: Optional. The requested runtime
      executable version. Defaults to FIREBASE_RULES_EXECUTABLE_V1.

  Fields:
    executableVersion: Optional. The requested runtime executable version.
      Defaults to FIREBASE_RULES_EXECUTABLE_V1.
    name: Required. Resource name of the `Release`. Format:
      `projects/{project_id}/releases/{release_id}`
  """

  class ExecutableVersionValueValuesEnum(_messages.Enum):
    r"""Optional. The requested runtime executable version. Defaults to
    FIREBASE_RULES_EXECUTABLE_V1.

    Values:
      RELEASE_EXECUTABLE_VERSION_UNSPECIFIED: Executable format unspecified.
        Defaults to FIREBASE_RULES_EXECUTABLE_V1
      FIREBASE_RULES_EXECUTABLE_V1: Firebase Rules syntax 'rules2' executable
        versions: Custom AST for use with Java clients.
      FIREBASE_RULES_EXECUTABLE_V2: CEL-based executable for use with C++
        clients.
      EVENT_FLOW_TRIGGERS_EXECUTABLE_V1: Event Flow executable v1 that maps to
        EventFlow v1beta1 syntax (go/eventflow-v1beta1).
      EVENT_FLOW_TRIGGERS_EXECUTABLE_V2: Event Flow executable v2 that maps to
        EventFlow v1beta2 syntax (go/eventflow-v1beta2).
    """
    RELEASE_EXECUTABLE_VERSION_UNSPECIFIED = 0
    FIREBASE_RULES_EXECUTABLE_V1 = 1
    FIREBASE_RULES_EXECUTABLE_V2 = 2
    EVENT_FLOW_TRIGGERS_EXECUTABLE_V1 = 3
    EVENT_FLOW_TRIGGERS_EXECUTABLE_V2 = 4

  executableVersion = _messages.EnumField('ExecutableVersionValueValuesEnum', 1)
  name = _messages.StringField(2, required=True)


class FirebaserulesProjectsReleasesGetRequest(_messages.Message):
  r"""A FirebaserulesProjectsReleasesGetRequest object.

  Fields:
    name: Required. Resource name of the `Release`. Format:
      `projects/{project_id}/releases/{release_id}`
  """

  name = _messages.StringField(1, required=True)


class FirebaserulesProjectsReleasesListRequest(_messages.Message):
  r"""A FirebaserulesProjectsReleasesListRequest object.

  Fields:
    filter: Optional. `Release` filter. The list method supports filters with
      restrictions on the `Release.name`, and `Release.ruleset_name`. Example
      1: A filter of 'name=prod*' might return `Release`s with names within
      'projects/foo' prefixed with 'prod': Name -> Ruleset Name: *
      projects/foo/releases/prod -> projects/foo/rulesets/uuid1234 *
      projects/foo/releases/prod/v1 -> projects/foo/rulesets/uuid1234 *
      projects/foo/releases/prod/v2 -> projects/foo/rulesets/uuid8888 Example
      2: A filter of `name=prod* ruleset_name=uuid1234` would return only
      `Release` instances for 'projects/foo' with names prefixed with 'prod'
      referring to the same `Ruleset` name of 'uuid1234': Name -> Ruleset
      Name: * projects/foo/releases/prod -> projects/foo/rulesets/1234 *
      projects/foo/releases/prod/v1 -> projects/foo/rulesets/1234 In the
      examples, the filter parameters refer to the search filters are relative
      to the project. Fully qualified prefixed may also be used.
    name: Required. Resource name for the project. Format:
      `projects/{project_id}`
    pageSize: Optional. Page size to load. Maximum of 100. Defaults to 10.
      Note: `page_size` is just a hint and the service may choose to load
      fewer than `page_size` results due to the size of the output. To
      traverse all of the releases, the caller should iterate until the
      `page_token` on the response is empty.
    pageToken: Optional. Next page token for the next batch of `Release`
      instances.
  """

  filter = _messages.StringField(1)
  name = _messages.StringField(2, required=True)
  pageSize = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(4)


class FirebaserulesProjectsReleasesPatchRequest(_messages.Message):
  r"""A FirebaserulesProjectsReleasesPatchRequest object.

  Fields:
    name: Required. Resource name for the project which owns this `Release`.
      Format: `projects/{project_id}`
    updateReleaseRequest: A UpdateReleaseRequest resource to be passed as the
      request body.
  """

  name = _messages.StringField(1, required=True)
  updateReleaseRequest = _messages.MessageField('UpdateReleaseRequest', 2)


class FirebaserulesProjectsRulesetsDeleteRequest(_messages.Message):
  r"""A FirebaserulesProjectsRulesetsDeleteRequest object.

  Fields:
    name: Required. Resource name for the ruleset to delete. Format:
      `projects/{project_id}/rulesets/{ruleset_id}`
  """

  name = _messages.StringField(1, required=True)


class FirebaserulesProjectsRulesetsGetRequest(_messages.Message):
  r"""A FirebaserulesProjectsRulesetsGetRequest object.

  Fields:
    name: Required. Resource name for the ruleset to get. Format:
      `projects/{project_id}/rulesets/{ruleset_id}`
  """

  name = _messages.StringField(1, required=True)


class FirebaserulesProjectsRulesetsListRequest(_messages.Message):
  r"""A FirebaserulesProjectsRulesetsListRequest object.

  Fields:
    filter: Optional. `Ruleset` filter. The list method supports filters with
      restrictions on `Ruleset.name`. Filters on `Ruleset.create_time` should
      use the `date` function which parses strings that conform to the RFC
      3339 date/time specifications. Example: `create_time >
      date("2017-01-01T00:00:00Z") AND name=UUID-*`
    name: Required. Resource name for the project. Format:
      `projects/{project_id}`
    pageSize: Optional. Page size to load. Maximum of 100. Defaults to 10.
      Note: `page_size` is just a hint and the service may choose to load less
      than `page_size` due to the size of the output. To traverse all of the
      releases, caller should iterate until the `page_token` is empty.
    pageToken: Optional. Next page token for loading the next batch of
      `Ruleset` instances.
  """

  filter = _messages.StringField(1)
  name = _messages.StringField(2, required=True)
  pageSize = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(4)


class FirebaserulesProjectsTestRequest(_messages.Message):
  r"""A FirebaserulesProjectsTestRequest object.

  Fields:
    name: Required. Tests may either provide `source` or a `Ruleset` resource
      name. For tests against `source`, the resource name must refer to the
      project: Format: `projects/{project_id}` For tests against a `Ruleset`,
      this must be the `Ruleset` resource name: Format:
      `projects/{project_id}/rulesets/{ruleset_id}`
    testRulesetRequest: A TestRulesetRequest resource to be passed as the
      request body.
  """

  name = _messages.StringField(1, required=True)
  testRulesetRequest = _messages.MessageField('TestRulesetRequest', 2)


class FunctionCall(_messages.Message):
  r"""Represents a service-defined function call that was invoked during test
  execution.

  Fields:
    args: The arguments that were provided to the function.
    function: Name of the function invoked.
  """

  args = _messages.MessageField('extra_types.JsonValue', 1, repeated=True)
  function = _messages.StringField(2)


class FunctionMock(_messages.Message):
  r"""Mock function definition. Mocks must refer to a function declared by the
  target service. The type of the function args and result will be inferred at
  test time. If either the arg or result values are not compatible with
  function type declaration, the request will be considered invalid. More than
  one `FunctionMock` may be provided for a given function name so long as the
  `Arg` matchers are distinct. There may be only one function for a given
  overload where all `Arg` values are `Arg.any_value`.

  Fields:
    args: The list of `Arg` values to match. The order in which the arguments
      are provided is the order in which they must appear in the function
      invocation.
    function: The name of the function. The function name must match one
      provided by a service declaration.
    result: The mock result of the function call.
  """

  args = _messages.MessageField('Arg', 1, repeated=True)
  function = _messages.StringField(2)
  result = _messages.MessageField('Result', 3)


class GetReleaseExecutableResponse(_messages.Message):
  r"""The response for FirebaseRulesService.GetReleaseExecutable

  Enums:
    ExecutableVersionValueValuesEnum: The Rules runtime version of the
      executable.
    LanguageValueValuesEnum: `Language` used to generate the executable bytes.

  Fields:
    executable: Executable view of the `Ruleset` referenced by the `Release`.
    executableVersion: The Rules runtime version of the executable.
    language: `Language` used to generate the executable bytes.
    rulesetName: `Ruleset` name associated with the `Release` executable.
    syncTime: Optional, indicates the freshness of the result. The response is
      guaranteed to be the latest within an interval up to the sync_time
      (inclusive).
    updateTime: Timestamp for the most recent `Release.update_time`.
  """

  class ExecutableVersionValueValuesEnum(_messages.Enum):
    r"""The Rules runtime version of the executable.

    Values:
      RELEASE_EXECUTABLE_VERSION_UNSPECIFIED: Executable format unspecified.
        Defaults to FIREBASE_RULES_EXECUTABLE_V1
      FIREBASE_RULES_EXECUTABLE_V1: Firebase Rules syntax 'rules2' executable
        versions: Custom AST for use with Java clients.
      FIREBASE_RULES_EXECUTABLE_V2: CEL-based executable for use with C++
        clients.
      EVENT_FLOW_TRIGGERS_EXECUTABLE_V1: Event Flow executable v1 that maps to
        EventFlow v1beta1 syntax (go/eventflow-v1beta1).
      EVENT_FLOW_TRIGGERS_EXECUTABLE_V2: Event Flow executable v2 that maps to
        EventFlow v1beta2 syntax (go/eventflow-v1beta2).
    """
    RELEASE_EXECUTABLE_VERSION_UNSPECIFIED = 0
    FIREBASE_RULES_EXECUTABLE_V1 = 1
    FIREBASE_RULES_EXECUTABLE_V2 = 2
    EVENT_FLOW_TRIGGERS_EXECUTABLE_V1 = 3
    EVENT_FLOW_TRIGGERS_EXECUTABLE_V2 = 4

  class LanguageValueValuesEnum(_messages.Enum):
    r"""`Language` used to generate the executable bytes.

    Values:
      LANGUAGE_UNSPECIFIED: Language unspecified. Defaults to FIREBASE_RULES.
      FIREBASE_RULES: Firebase Rules language.
      EVENT_FLOW_TRIGGERS: Event Flow triggers.
    """
    LANGUAGE_UNSPECIFIED = 0
    FIREBASE_RULES = 1
    EVENT_FLOW_TRIGGERS = 2

  executable = _messages.BytesField(1)
  executableVersion = _messages.EnumField('ExecutableVersionValueValuesEnum', 2)
  language = _messages.EnumField('LanguageValueValuesEnum', 3)
  rulesetName = _messages.StringField(4)
  syncTime = _messages.StringField(5)
  updateTime = _messages.StringField(6)


class Issue(_messages.Message):
  r"""Issues include warnings, errors, and deprecation notices.

  Enums:
    SeverityValueValuesEnum: The severity of the issue.

  Fields:
    description: Short error description.
    severity: The severity of the issue.
    sourcePosition: Position of the issue in the `Source`.
  """

  class SeverityValueValuesEnum(_messages.Enum):
    r"""The severity of the issue.

    Values:
      SEVERITY_UNSPECIFIED: An unspecified severity.
      DEPRECATION: Deprecation issue for statements and method that may no
        longer be supported or maintained.
      WARNING: Warnings such as: unused variables.
      ERROR: Errors such as: unmatched curly braces or variable redefinition.
    """
    SEVERITY_UNSPECIFIED = 0
    DEPRECATION = 1
    WARNING = 2
    ERROR = 3

  description = _messages.StringField(1)
  severity = _messages.EnumField('SeverityValueValuesEnum', 2)
  sourcePosition = _messages.MessageField('SourcePosition', 3)


class ListReleasesResponse(_messages.Message):
  r"""The response for FirebaseRulesService.ListReleases.

  Fields:
    nextPageToken: The pagination token to retrieve the next page of results.
      If the value is empty, no further results remain.
    releases: List of `Release` instances.
  """

  nextPageToken = _messages.StringField(1)
  releases = _messages.MessageField('Release', 2, repeated=True)


class ListRulesetsResponse(_messages.Message):
  r"""The response for FirebaseRulesService.ListRulesets.

  Fields:
    nextPageToken: The pagination token to retrieve the next page of results.
      If the value is empty, no further results remain.
    rulesets: List of `Ruleset` instances.
  """

  nextPageToken = _messages.StringField(1)
  rulesets = _messages.MessageField('Ruleset', 2, repeated=True)


class Metadata(_messages.Message):
  r"""Metadata for a Ruleset.

  Fields:
    services: Services that this ruleset has declarations for (e.g.,
      "cloud.firestore"). There may be 0+ of these.
  """

  services = _messages.StringField(1, repeated=True)


class Release(_messages.Message):
  r"""`Release` is a named reference to a `Ruleset`. Once a `Release` refers
  to a `Ruleset`, rules-enabled services will be able to enforce the
  `Ruleset`.

  Fields:
    createTime: Output only. Time the release was created.
    disabled: Disable the release to keep it from being served. The response
      code of NOT_FOUND will be given for executables generated from this
      Release.
    name: Required. Format: `projects/{project_id}/releases/{release_id}`
    rulesetName: Required. Name of the `Ruleset` referred to by this
      `Release`. The `Ruleset` must exist for the `Release` to be created.
    updateTime: Output only. Time the release was updated.
  """

  createTime = _messages.StringField(1)
  disabled = _messages.BooleanField(2)
  name = _messages.StringField(3)
  rulesetName = _messages.StringField(4)
  updateTime = _messages.StringField(5)


class Result(_messages.Message):
  r"""Possible result values from the function mock invocation.

  Fields:
    undefined: The result is undefined, meaning the result could not be
      computed.
    value: The result is an actual value. The type of the value must match
      that of the type declared by the service.
  """

  undefined = _messages.MessageField('Empty', 1)
  value = _messages.MessageField('extra_types.JsonValue', 2)


class Ruleset(_messages.Message):
  r"""`Ruleset` is an immutable copy of `Source` with a globally unique
  identifier and a creation time.

  Fields:
    attachmentPoint: Immutable. Intended resource to which this Ruleset should
      be released. May be left blank to signify the resource associated with
      the default release. Expected format:
      firestore.googleapis.com/projects//databases/
    createTime: Output only. Time the `Ruleset` was created.
    metadata: Output only. The metadata for this ruleset.
    name: Output only. Name of the `Ruleset`. The ruleset_id is auto generated
      by the service. Format: `projects/{project_id}/rulesets/{ruleset_id}`
    source: Required. `Source` for the `Ruleset`.
  """

  attachmentPoint = _messages.StringField(1)
  createTime = _messages.StringField(2)
  metadata = _messages.MessageField('Metadata', 3)
  name = _messages.StringField(4)
  source = _messages.MessageField('Source', 5)


class Source(_messages.Message):
  r"""`Source` is one or more `File` messages comprising a logical set of
  rules.

  Enums:
    LanguageValueValuesEnum: `Language` of the `Source` bundle. If
      unspecified, the language will default to `FIREBASE_RULES`.

  Fields:
    files: Required. `File` set constituting the `Source` bundle.
    language: `Language` of the `Source` bundle. If unspecified, the language
      will default to `FIREBASE_RULES`.
  """

  class LanguageValueValuesEnum(_messages.Enum):
    r"""`Language` of the `Source` bundle. If unspecified, the language will
    default to `FIREBASE_RULES`.

    Values:
      LANGUAGE_UNSPECIFIED: Language unspecified. Defaults to FIREBASE_RULES.
      FIREBASE_RULES: Firebase Rules language.
      EVENT_FLOW_TRIGGERS: Event Flow triggers.
    """
    LANGUAGE_UNSPECIFIED = 0
    FIREBASE_RULES = 1
    EVENT_FLOW_TRIGGERS = 2

  files = _messages.MessageField('File', 1, repeated=True)
  language = _messages.EnumField('LanguageValueValuesEnum', 2)


class SourcePosition(_messages.Message):
  r"""Position in the `Source` content including its line, column number, and
  an index of the `File` in the `Source` message. Used for debug purposes.

  Fields:
    column: First column on the source line associated with the source
      fragment.
    currentOffset: Start position relative to the beginning of the file.
    endOffset: End position relative to the beginning of the file.
    fileIndex: Index of the `File` in the `Source` message where the content
      appears. Output only.
    fileName: Name of the `File`.
    line: Line number of the source fragment. 1-based.
  """

  column = _messages.IntegerField(1, variant=_messages.Variant.INT32)
  currentOffset = _messages.IntegerField(2, variant=_messages.Variant.INT32)
  endOffset = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  fileIndex = _messages.IntegerField(4, variant=_messages.Variant.INT32)
  fileName = _messages.StringField(5)
  line = _messages.IntegerField(6, variant=_messages.Variant.INT32)


class StandardQueryParameters(_messages.Message):
  r"""Query parameters accepted by all methods.

  Enums:
    FXgafvValueValuesEnum: V1 error format.
    AltValueValuesEnum: Data format for response.

  Fields:
    f__xgafv: V1 error format.
    access_token: OAuth access token.
    alt: Data format for response.
    callback: JSONP
    fields: Selector specifying which fields to include in a partial response.
    key: API key. Your API key identifies your project and provides you with
      API access, quota, and reports. Required unless you provide an OAuth 2.0
      token.
    oauth_token: OAuth 2.0 token for the current user.
    prettyPrint: Returns response with indentations and line breaks.
    quotaUser: Available to use for quota purposes for server-side
      applications. Can be any arbitrary string assigned to a user, but should
      not exceed 40 characters.
    trace: A tracing token of the form "token:<tokenid>" to include in api
      requests.
    uploadType: Legacy upload protocol for media (e.g. "media", "multipart").
    upload_protocol: Upload protocol for media (e.g. "raw", "multipart").
  """

  class AltValueValuesEnum(_messages.Enum):
    r"""Data format for response.

    Values:
      json: Responses with Content-Type of application/json
      media: Media download with context-dependent Content-Type
      proto: Responses with Content-Type of application/x-protobuf
    """
    json = 0
    media = 1
    proto = 2

  class FXgafvValueValuesEnum(_messages.Enum):
    r"""V1 error format.

    Values:
      _1: v1 error format
      _2: v2 error format
    """
    _1 = 0
    _2 = 1

  f__xgafv = _messages.EnumField('FXgafvValueValuesEnum', 1)
  access_token = _messages.StringField(2)
  alt = _messages.EnumField('AltValueValuesEnum', 3, default='json')
  callback = _messages.StringField(4)
  fields = _messages.StringField(5)
  key = _messages.StringField(6)
  oauth_token = _messages.StringField(7)
  prettyPrint = _messages.BooleanField(8, default=True)
  quotaUser = _messages.StringField(9)
  trace = _messages.StringField(10)
  uploadType = _messages.StringField(11)
  upload_protocol = _messages.StringField(12)


class TestCase(_messages.Message):
  r"""`TestCase` messages provide the request context and an expectation as to
  whether the given context will be allowed or denied. Test cases may specify
  the `request`, `resource`, and `function_mocks` to mock a function call to a
  service-provided function. The `request` object represents context present
  at request-time. The `resource` is the value of the target resource as it
  appears in persistent storage before the request is executed.

  Enums:
    ExpectationValueValuesEnum: Test expectation.
    ExpressionReportLevelValueValuesEnum: Specifies what should be included in
      the response.
    PathEncodingValueValuesEnum: Specifies whether paths (such as
      request.path) are encoded and how.

  Fields:
    expectation: Test expectation.
    expressionReportLevel: Specifies what should be included in the response.
    functionMocks: Optional function mocks for service-defined functions. If
      not set, any service defined function is expected to return an error,
      which may or may not influence the test outcome.
    pathEncoding: Specifies whether paths (such as request.path) are encoded
      and how.
    request: Request context. The exact format of the request context is
      service-dependent. See the appropriate service documentation for
      information about the supported fields and types on the request.
      Minimally, all services support the following fields and types: Request
      field | Type ---------------|----------------- auth.uid | `string`
      auth.token | `map` headers | `map` method | `string` params | `map` path
      | `string` time | `google.protobuf.Timestamp` If the request value is
      not well-formed for the service, the request will be rejected as an
      invalid argument.
    resource: Optional resource value as it appears in persistent storage
      before the request is fulfilled. The resource type depends on the
      `request.path` value.
  """

  class ExpectationValueValuesEnum(_messages.Enum):
    r"""Test expectation.

    Values:
      EXPECTATION_UNSPECIFIED: Unspecified expectation.
      ALLOW: Expect an allowed result.
      DENY: Expect a denied result.
    """
    EXPECTATION_UNSPECIFIED = 0
    ALLOW = 1
    DENY = 2

  class ExpressionReportLevelValueValuesEnum(_messages.Enum):
    r"""Specifies what should be included in the response.

    Values:
      LEVEL_UNSPECIFIED: No level has been specified. Defaults to "NONE"
        behavior.
      NONE: Do not include any additional information.
      FULL: Include detailed reporting on expressions evaluated.
      VISITED: Only include the expressions that were visited during
        evaluation.
    """
    LEVEL_UNSPECIFIED = 0
    NONE = 1
    FULL = 2
    VISITED = 3

  class PathEncodingValueValuesEnum(_messages.Enum):
    r"""Specifies whether paths (such as request.path) are encoded and how.

    Values:
      ENCODING_UNSPECIFIED: No encoding has been specified. Defaults to
        "URL_ENCODED" behavior.
      URL_ENCODED: Treats path segments as URL encoded but with non-encoded
        separators ("/"). This is the default behavior.
      PLAIN: Treats total path as non-URL encoded e.g. raw.
    """
    ENCODING_UNSPECIFIED = 0
    URL_ENCODED = 1
    PLAIN = 2

  expectation = _messages.EnumField('ExpectationValueValuesEnum', 1)
  expressionReportLevel = _messages.EnumField('ExpressionReportLevelValueValuesEnum', 2)
  functionMocks = _messages.MessageField('FunctionMock', 3, repeated=True)
  pathEncoding = _messages.EnumField('PathEncodingValueValuesEnum', 4)
  request = _messages.MessageField('extra_types.JsonValue', 5)
  resource = _messages.MessageField('extra_types.JsonValue', 6)


class TestResult(_messages.Message):
  r"""Test result message containing the state of the test as well as a
  description and source position for test failures.

  Enums:
    StateValueValuesEnum: State of the test.

  Fields:
    debugMessages: Debug messages related to test execution issues encountered
      during evaluation. Debug messages may be related to too many or too few
      invocations of function mocks or to runtime errors that occur during
      evaluation. For example: ```Unable to read variable [name:
      "resource"]```
    errorPosition: Position in the `Source` or `Ruleset` where the principle
      runtime error occurs. Evaluation of an expression may result in an
      error. Rules are deny by default, so a `DENY` expectation when an error
      is generated is valid. When there is a `DENY` with an error, the
      `SourcePosition` is returned. E.g. `error_position { line: 19 column: 37
      }`
    expressionReports: The mapping from expression in the ruleset AST to the
      values they were evaluated to. Partially-nested to mirror AST structure.
      Note that this field is actually tracking expressions and not permission
      statements in contrast to the "visited_expressions" field above. Literal
      expressions are omitted.
    functionCalls: The set of function calls made to service-defined methods.
      Function calls are included in the order in which they are encountered
      during evaluation, are provided for both mocked and unmocked functions,
      and included on the response regardless of the test `state`.
    state: State of the test.
    visitedExpressions: The set of visited permission expressions for a given
      test. This returns the positions and evaluation results of all visited
      permission expressions which were relevant to the test case, e.g. ```
      match /path { allow read if: } ``` For a detailed report of the
      intermediate evaluation states, see the `expression_reports` field
  """

  class StateValueValuesEnum(_messages.Enum):
    r"""State of the test.

    Values:
      STATE_UNSPECIFIED: Test state is not set.
      SUCCESS: Test is a success.
      FAILURE: Test is a failure.
    """
    STATE_UNSPECIFIED = 0
    SUCCESS = 1
    FAILURE = 2

  debugMessages = _messages.StringField(1, repeated=True)
  errorPosition = _messages.MessageField('SourcePosition', 2)
  expressionReports = _messages.MessageField('ExpressionReport', 3, repeated=True)
  functionCalls = _messages.MessageField('FunctionCall', 4, repeated=True)
  state = _messages.EnumField('StateValueValuesEnum', 5)
  visitedExpressions = _messages.MessageField('VisitedExpression', 6, repeated=True)


class TestRulesetRequest(_messages.Message):
  r"""The request for FirebaseRulesService.TestRuleset.

  Fields:
    source: Optional. Optional `Source` to be checked for correctness. This
      field must not be set when the resource name refers to a `Ruleset`.
    testSuite: Required. The tests to execute against the `Source`. When
      `Source` is provided inline, the test cases will only be run if the
      `Source` is syntactically and semantically valid. Inline `TestSuite` to
      run.
  """

  source = _messages.MessageField('Source', 1)
  testSuite = _messages.MessageField('TestSuite', 2)


class TestRulesetResponse(_messages.Message):
  r"""The response for FirebaseRulesService.TestRuleset.

  Fields:
    issues: Syntactic and semantic `Source` issues of varying severity. Issues
      of `ERROR` severity will prevent tests from executing.
    testResults: The set of test results given the test cases in the
      `TestSuite`. The results will appear in the same order as the test cases
      appear in the `TestSuite`.
  """

  issues = _messages.MessageField('Issue', 1, repeated=True)
  testResults = _messages.MessageField('TestResult', 2, repeated=True)


class TestSuite(_messages.Message):
  r"""`TestSuite` is a collection of `TestCase` instances that validate the
  logical correctness of a `Ruleset`. The `TestSuite` may be referenced in-
  line within a `TestRuleset` invocation or as part of a `Release` object as a
  pre-release check.

  Fields:
    testCases: Collection of test cases associated with the `TestSuite`.
  """

  testCases = _messages.MessageField('TestCase', 1, repeated=True)


class UpdateReleaseRequest(_messages.Message):
  r"""The request for FirebaseRulesService.UpdateRelease.

  Fields:
    release: Required. `Release` to update.
    updateMask: Optional. Specifies which fields to update.
  """

  release = _messages.MessageField('Release', 1)
  updateMask = _messages.StringField(2)


class ValueCount(_messages.Message):
  r"""Tuple for how many times an Expression was evaluated to a particular
  ExpressionValue.

  Fields:
    count: The amount of times that expression returned.
    value: The return value of the expression
  """

  count = _messages.IntegerField(1, variant=_messages.Variant.INT32)
  value = _messages.MessageField('extra_types.JsonValue', 2)


class VisitedExpression(_messages.Message):
  r"""Store the position and access outcome for an expression visited in
  rules.

  Fields:
    sourcePosition: Position in the `Source` or `Ruleset` where an expression
      was visited.
    value: The evaluated value for the visited expression, e.g. true/false
  """

  sourcePosition = _messages.MessageField('SourcePosition', 1)
  value = _messages.MessageField('extra_types.JsonValue', 2)


encoding.AddCustomJsonFieldMapping(
    StandardQueryParameters, 'f__xgafv', '$.xgafv')
encoding.AddCustomJsonEnumMapping(
    StandardQueryParameters.FXgafvValueValuesEnum, '_1', '1')
encoding.AddCustomJsonEnumMapping(
    StandardQueryParameters.FXgafvValueValuesEnum, '_2', '2')
