"""Generated message classes for ftp version v1alpha.

"""
# NOTE: This file is autogenerated and should not be edited by hand.

from apitools.base.protorpclite import messages as _messages
from apitools.base.py import encoding
from apitools.base.py import extra_types


package = 'ftp'


class AllowedConsumer(_messages.Message):
  r"""A consumer project or network that is permitted to connect to the server
  via PSC.

  Fields:
    connectionLimit: Required. The connection limit for the consumer. Value
      must be greater than 0.
    project: The project ID or number of the consumer project. Must be in the
      format: `projects/{project}`.
  """

  connectionLimit = _messages.IntegerField(1)
  project = _messages.StringField(2)


class CancelOperationRequest(_messages.Message):
  r"""The request message for Operations.CancelOperation."""


class DeniedConsumer(_messages.Message):
  r"""A consumer project or network that is denied to connect to the server
  via PSC.

  Fields:
    project: The project ID or number of the consumer project. Must be in the
      format: `projects/{project}`.
  """

  project = _messages.StringField(1)


class Empty(_messages.Message):
  r"""A generic empty message that you can re-use to avoid defining duplicated
  empty messages in your APIs. A typical example is to use it as the request
  or the response type of an API method. For instance: service Foo { rpc
  Bar(google.protobuf.Empty) returns (google.protobuf.Empty); }
  """



class ExternalServerConfig(_messages.Message):
  r"""Configuration for external server.

  Fields:
    allowedCidrBlocks: Optional. List of CIDR blocks that are allowed to
      access the Server. A CIDR range consists of an IP Address and a prefix
      length to construct the subnet mask. By default, the prefix length is 32
      (i.e. matches a single IP address). For now, only IPV4 addresses are
      supported. Examples: "203.0.113.0/24" - matches with the IP addresses in
      the range 203.0.113.0 - 203.0.113.255. "0.0.0.0/0" - matches against any
      IP address. This field must contain at least one entry if the access
      type is EXTERNAL. The number of allowed CIDR blocks cannot exceed 500.
      Example: 192.168.0.0/16
    ipAddress: Output only. IP address of the LB via which clients will
      connect.
  """

  allowedCidrBlocks = _messages.StringField(1, repeated=True)
  ipAddress = _messages.StringField(2)


class FtpProjectsLocationsGetRequest(_messages.Message):
  r"""A FtpProjectsLocationsGetRequest object.

  Fields:
    name: Resource name for the location.
  """

  name = _messages.StringField(1, required=True)


class FtpProjectsLocationsListRequest(_messages.Message):
  r"""A FtpProjectsLocationsListRequest object.

  Fields:
    extraLocationTypes: Optional. Do not use this field unless explicitly
      documented otherwise. This is primarily for internal usage.
    filter: A filter to narrow down results to a preferred subset. The
      filtering language accepts strings like `"displayName=tokyo"`, and is
      documented in more detail in [AIP-160](https://google.aip.dev/160).
    name: The resource that owns the locations collection, if applicable.
    pageSize: The maximum number of results to return. If not set, the service
      selects a default.
    pageToken: A page token received from the `next_page_token` field in the
      response. Send that page token to receive the subsequent page.
  """

  extraLocationTypes = _messages.StringField(1, repeated=True)
  filter = _messages.StringField(2)
  name = _messages.StringField(3, required=True)
  pageSize = _messages.IntegerField(4, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(5)


class FtpProjectsLocationsOperationsCancelRequest(_messages.Message):
  r"""A FtpProjectsLocationsOperationsCancelRequest object.

  Fields:
    cancelOperationRequest: A CancelOperationRequest resource to be passed as
      the request body.
    name: The name of the operation resource to be cancelled.
  """

  cancelOperationRequest = _messages.MessageField('CancelOperationRequest', 1)
  name = _messages.StringField(2, required=True)


class FtpProjectsLocationsOperationsDeleteRequest(_messages.Message):
  r"""A FtpProjectsLocationsOperationsDeleteRequest object.

  Fields:
    name: The name of the operation resource to be deleted.
  """

  name = _messages.StringField(1, required=True)


class FtpProjectsLocationsOperationsGetRequest(_messages.Message):
  r"""A FtpProjectsLocationsOperationsGetRequest object.

  Fields:
    name: The name of the operation resource.
  """

  name = _messages.StringField(1, required=True)


class FtpProjectsLocationsOperationsListRequest(_messages.Message):
  r"""A FtpProjectsLocationsOperationsListRequest object.

  Fields:
    filter: The standard list filter.
    name: The name of the operation's parent resource.
    pageSize: The standard list page size.
    pageToken: The standard list page token.
    returnPartialSuccess: When set to `true`, operations that are reachable
      are returned as normal, and those that are unreachable are returned in
      the ListOperationsResponse.unreachable field. This can only be `true`
      when reading across collections. For example, when `parent` is set to
      `"projects/example/locations/-"`. This field is not supported by default
      and will result in an `UNIMPLEMENTED` error if set unless explicitly
      documented otherwise in service or product specific documentation.
  """

  filter = _messages.StringField(1)
  name = _messages.StringField(2, required=True)
  pageSize = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(4)
  returnPartialSuccess = _messages.BooleanField(5)


class FtpProjectsLocationsServersCreateRequest(_messages.Message):
  r"""A FtpProjectsLocationsServersCreateRequest object.

  Fields:
    parent: Required. Value for parent.
    requestId: Optional. An optional request ID to identify requests. Specify
      a unique request ID so that if you must retry your request, the server
      will know to ignore the request if it has already been completed. The
      server will guarantee that for at least 60 minutes since the first
      request. For example, consider a situation where you make an initial
      request and the request times out. If you make the request again with
      the same request ID, the server can check if original operation with the
      same request ID was received, and if so, will ignore the second request.
      This prevents clients from accidentally creating duplicate commitments.
      The request ID must be a valid UUID with the exception that zero UUID is
      not supported (00000000-0000-0000-0000-000000000000).
    server: A Server resource to be passed as the request body.
    serverId: Required. Id of the requesting object If auto-generating Id
      server-side, remove this field and server_id from the method_signature
      of Create RPC
  """

  parent = _messages.StringField(1, required=True)
  requestId = _messages.StringField(2)
  server = _messages.MessageField('Server', 3)
  serverId = _messages.StringField(4)


class FtpProjectsLocationsServersDeleteRequest(_messages.Message):
  r"""A FtpProjectsLocationsServersDeleteRequest object.

  Fields:
    name: Required. Name of the resource
  """

  name = _messages.StringField(1, required=True)


class FtpProjectsLocationsServersGetRequest(_messages.Message):
  r"""A FtpProjectsLocationsServersGetRequest object.

  Fields:
    name: Required. Name of the resource
  """

  name = _messages.StringField(1, required=True)


class FtpProjectsLocationsServersListRequest(_messages.Message):
  r"""A FtpProjectsLocationsServersListRequest object.

  Fields:
    filter: Optional. Filtering results
    orderBy: Optional. Hint for how to order the results
    pageSize: Optional. Requested page size. Server may return fewer items
      than requested. If unspecified, server will pick an appropriate default.
    pageToken: Optional. A token identifying a page of results the server
      should return.
    parent: Required. Parent value for ListServersRequest
  """

  filter = _messages.StringField(1)
  orderBy = _messages.StringField(2)
  pageSize = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(4)
  parent = _messages.StringField(5, required=True)


class FtpProjectsLocationsServersPatchRequest(_messages.Message):
  r"""A FtpProjectsLocationsServersPatchRequest object.

  Fields:
    name: Identifier. name of resource
    requestId: Optional. An optional request ID to identify requests. Specify
      a unique request ID so that if you must retry your request, the server
      will know to ignore the request if it has already been completed. The
      server will guarantee that for at least 60 minutes since the first
      request. For example, consider a situation where you make an initial
      request and the request times out. If you make the request again with
      the same request ID, the server can check if original operation with the
      same request ID was received, and if so, will ignore the second request.
      This prevents clients from accidentally creating duplicate commitments.
      The request ID must be a valid UUID with the exception that zero UUID is
      not supported (00000000-0000-0000-0000-000000000000).
    server: A Server resource to be passed as the request body.
    updateMask: Optional. Field mask is used to specify the fields to be
      overwritten in the Server resource by the update. The fields specified
      in the update_mask are relative to the resource, not the full request. A
      field will be overwritten if it is in the mask. If the user does not
      provide a mask then all fields present in the request will be
      overwritten.
  """

  name = _messages.StringField(1, required=True)
  requestId = _messages.StringField(2)
  server = _messages.MessageField('Server', 3)
  updateMask = _messages.StringField(4)


class FtpProjectsLocationsServersUsersCreateRequest(_messages.Message):
  r"""A FtpProjectsLocationsServersUsersCreateRequest object.

  Fields:
    parent: Required. Value for parent.
    requestId: Optional. An optional request ID to identify requests. Specify
      a unique request ID so that if you must retry your request, the server
      will know to ignore the request if it has already been completed. The
      server will guarantee that for at least 60 minutes since the first
      request. For example, consider a situation where you make an initial
      request and the request times out. If you make the request again with
      the same request ID, the server can check if original operation with the
      same request ID was received, and if so, will ignore the second request.
      This prevents clients from accidentally creating duplicate commitments.
      The request ID must be a valid UUID with the exception that zero UUID is
      not supported (00000000-0000-0000-0000-000000000000).
    user: A User resource to be passed as the request body.
    userId: Required. Id of the requesting object If auto-generating Id
      server-side, remove this field and server_id from the method_signature
      of Create RPC
  """

  parent = _messages.StringField(1, required=True)
  requestId = _messages.StringField(2)
  user = _messages.MessageField('User', 3)
  userId = _messages.StringField(4)


class FtpProjectsLocationsServersUsersDeleteRequest(_messages.Message):
  r"""A FtpProjectsLocationsServersUsersDeleteRequest object.

  Fields:
    force: Optional. If set to true, the request will force the deletion of
      the User.
    name: Required. Name of the resource
  """

  force = _messages.BooleanField(1)
  name = _messages.StringField(2, required=True)


class FtpProjectsLocationsServersUsersGetRequest(_messages.Message):
  r"""A FtpProjectsLocationsServersUsersGetRequest object.

  Fields:
    name: Required. Name of the resource
  """

  name = _messages.StringField(1, required=True)


class FtpProjectsLocationsServersUsersListRequest(_messages.Message):
  r"""A FtpProjectsLocationsServersUsersListRequest object.

  Fields:
    filter: Optional. Filtering results
    orderBy: Optional. Hint for how to order the results
    pageSize: Optional. Requested page size. User may return fewer items than
      requested. The maximum value is 1000; The default value is 50 if the
      field is omitted (or set to 0).
    pageToken: Optional. A token identifying a page of results the user should
      return.
    parent: Required. Parent value for ListUsersRequest
  """

  filter = _messages.StringField(1)
  orderBy = _messages.StringField(2)
  pageSize = _messages.IntegerField(3, variant=_messages.Variant.INT32)
  pageToken = _messages.StringField(4)
  parent = _messages.StringField(5, required=True)


class FtpProjectsLocationsServersUsersPatchRequest(_messages.Message):
  r"""A FtpProjectsLocationsServersUsersPatchRequest object.

  Fields:
    name: Identifier. User-friendly name via which User will be identified.
      projects/{project}/locations/{location}/servers/{server}/users/{user}
    updateMask: Optional. Field mask is used to specify the fields to be
      overwritten in the User resource by the update. The fields specified in
      the update_mask are relative to the resource, not the full request. A
      field will be overwritten if it is in the mask. If the user does not
      provide a mask then all fields present in the request will be
      overwritten.
    user: A User resource to be passed as the request body.
  """

  name = _messages.StringField(1, required=True)
  updateMask = _messages.StringField(2)
  user = _messages.MessageField('User', 3)


class InternalServerConfig(_messages.Message):
  r"""Configuration for private server accessible via PSC.

  Fields:
    consumerAcceptList: Required. A list of projects that are permitted to
      connect. At least one project is required in the allow list.
    consumerRejectList: Optional. A list of projects that are denied
      connection. Format: "projects/sample_project_id" or
      "projects/1234567890" Projects in this list will be denied access, even
      if they are included in the `allow_list`. If this list is empty, no
      projects are explicitly rejected.
    pscEndpoints: Output only. Details of endpoints created by the customer.
    serviceAttachment: Output only. The resource name of the service
      attachment. Format: `projects/{project}/regions/{region}/serviceAttachme
      nts/{service_attachment}`
  """

  consumerAcceptList = _messages.MessageField('AllowedConsumer', 1, repeated=True)
  consumerRejectList = _messages.MessageField('DeniedConsumer', 2, repeated=True)
  pscEndpoints = _messages.MessageField('PscEndpoint', 3, repeated=True)
  serviceAttachment = _messages.StringField(4)


class ListLocationsResponse(_messages.Message):
  r"""The response message for Locations.ListLocations.

  Fields:
    locations: A list of locations that matches the specified filter in the
      request.
    nextPageToken: The standard List next-page token.
  """

  locations = _messages.MessageField('Location', 1, repeated=True)
  nextPageToken = _messages.StringField(2)


class ListOperationsResponse(_messages.Message):
  r"""The response message for Operations.ListOperations.

  Fields:
    nextPageToken: The standard List next-page token.
    operations: A list of operations that matches the specified filter in the
      request.
    unreachable: Unordered list. Unreachable resources. Populated when the
      request sets `ListOperationsRequest.return_partial_success` and reads
      across collections. For example, when attempting to list all resources
      across all supported locations.
  """

  nextPageToken = _messages.StringField(1)
  operations = _messages.MessageField('Operation', 2, repeated=True)
  unreachable = _messages.StringField(3, repeated=True)


class ListServersResponse(_messages.Message):
  r"""Message for response to listing Servers

  Fields:
    nextPageToken: A token identifying a page of results the server should
      return.
    servers: The list of Server
    unreachable: Unordered list. Locations that could not be reached.
  """

  nextPageToken = _messages.StringField(1)
  servers = _messages.MessageField('Server', 2, repeated=True)
  unreachable = _messages.StringField(3, repeated=True)


class ListUsersResponse(_messages.Message):
  r"""Message for response to listing Users

  Fields:
    nextPageToken: A token identifying a page of results the user should
      return.
    unreachable: Unordered list. Locations that could not be reached.
    users: The list of User
  """

  nextPageToken = _messages.StringField(1)
  unreachable = _messages.StringField(2, repeated=True)
  users = _messages.MessageField('User', 3, repeated=True)


class Location(_messages.Message):
  r"""A resource that represents a Google Cloud location.

  Messages:
    LabelsValue: Cross-service attributes for the location. For example
      {"cloud.googleapis.com/region": "us-east1"}
    MetadataValue: Service-specific metadata. For example the available
      capacity at the given location.

  Fields:
    displayName: The friendly name for this location, typically a nearby city
      name. For example, "Tokyo".
    labels: Cross-service attributes for the location. For example
      {"cloud.googleapis.com/region": "us-east1"}
    locationId: The canonical id for this location. For example: `"us-east1"`.
    metadata: Service-specific metadata. For example the available capacity at
      the given location.
    name: Resource name for the location, which may vary between
      implementations. For example: `"projects/example-project/locations/us-
      east1"`
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class LabelsValue(_messages.Message):
    r"""Cross-service attributes for the location. For example
    {"cloud.googleapis.com/region": "us-east1"}

    Messages:
      AdditionalProperty: An additional property for a LabelsValue object.

    Fields:
      additionalProperties: Additional properties of type LabelsValue
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a LabelsValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class MetadataValue(_messages.Message):
    r"""Service-specific metadata. For example the available capacity at the
    given location.

    Messages:
      AdditionalProperty: An additional property for a MetadataValue object.

    Fields:
      additionalProperties: Properties of the object. Contains field @type
        with type URL.
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a MetadataValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  displayName = _messages.StringField(1)
  labels = _messages.MessageField('LabelsValue', 2)
  locationId = _messages.StringField(3)
  metadata = _messages.MessageField('MetadataValue', 4)
  name = _messages.StringField(5)


class Operation(_messages.Message):
  r"""This resource represents a long-running operation that is the result of
  a network API call.

  Messages:
    MetadataValue: Service-specific metadata associated with the operation. It
      typically contains progress information and common metadata such as
      create time. Some services might not provide such metadata. Any method
      that returns a long-running operation should document the metadata type,
      if any.
    ResponseValue: The normal, successful response of the operation. If the
      original method returns no data on success, such as `Delete`, the
      response is `google.protobuf.Empty`. If the original method is standard
      `Get`/`Create`/`Update`, the response should be the resource. For other
      methods, the response should have the type `XxxResponse`, where `Xxx` is
      the original method name. For example, if the original method name is
      `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.

  Fields:
    done: If the value is `false`, it means the operation is still in
      progress. If `true`, the operation is completed, and either `error` or
      `response` is available.
    error: The error result of the operation in case of failure or
      cancellation.
    metadata: Service-specific metadata associated with the operation. It
      typically contains progress information and common metadata such as
      create time. Some services might not provide such metadata. Any method
      that returns a long-running operation should document the metadata type,
      if any.
    name: The server-assigned name, which is only unique within the same
      service that originally returns it. If you use the default HTTP mapping,
      the `name` should be a resource name ending with
      `operations/{unique_id}`.
    response: The normal, successful response of the operation. If the
      original method returns no data on success, such as `Delete`, the
      response is `google.protobuf.Empty`. If the original method is standard
      `Get`/`Create`/`Update`, the response should be the resource. For other
      methods, the response should have the type `XxxResponse`, where `Xxx` is
      the original method name. For example, if the original method name is
      `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class MetadataValue(_messages.Message):
    r"""Service-specific metadata associated with the operation. It typically
    contains progress information and common metadata such as create time.
    Some services might not provide such metadata. Any method that returns a
    long-running operation should document the metadata type, if any.

    Messages:
      AdditionalProperty: An additional property for a MetadataValue object.

    Fields:
      additionalProperties: Properties of the object. Contains field @type
        with type URL.
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a MetadataValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  @encoding.MapUnrecognizedFields('additionalProperties')
  class ResponseValue(_messages.Message):
    r"""The normal, successful response of the operation. If the original
    method returns no data on success, such as `Delete`, the response is
    `google.protobuf.Empty`. If the original method is standard
    `Get`/`Create`/`Update`, the response should be the resource. For other
    methods, the response should have the type `XxxResponse`, where `Xxx` is
    the original method name. For example, if the original method name is
    `TakeSnapshot()`, the inferred response type is `TakeSnapshotResponse`.

    Messages:
      AdditionalProperty: An additional property for a ResponseValue object.

    Fields:
      additionalProperties: Properties of the object. Contains field @type
        with type URL.
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a ResponseValue object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  done = _messages.BooleanField(1)
  error = _messages.MessageField('Status', 2)
  metadata = _messages.MessageField('MetadataValue', 3)
  name = _messages.StringField(4)
  response = _messages.MessageField('ResponseValue', 5)


class OperationMetadata(_messages.Message):
  r"""Represents the metadata of the long-running operation.

  Fields:
    apiVersion: Output only. API version used to start the operation.
    createTime: Output only. The time the operation was created.
    endTime: Output only. The time the operation finished running.
    requestedCancellation: Output only. Identifies whether the user has
      requested cancellation of the operation. Operations that have been
      cancelled successfully have google.longrunning.Operation.error value
      with a google.rpc.Status.code of `1`, corresponding to `Code.CANCELLED`.
    statusMessage: Output only. Human-readable status of the operation, if
      any.
    target: Output only. Server-defined resource path for the target of the
      operation.
    verb: Output only. Name of the verb executed by the operation.
  """

  apiVersion = _messages.StringField(1)
  createTime = _messages.StringField(2)
  endTime = _messages.StringField(3)
  requestedCancellation = _messages.BooleanField(4)
  statusMessage = _messages.StringField(5)
  target = _messages.StringField(6)
  verb = _messages.StringField(7)


class PscEndpoint(_messages.Message):
  r"""Details of PSC endpoint created by customer.

  Fields:
    endpoint: Output only. This is a Resource name for Private Service Connect
      endpoint. Format:
      `projects/{project}/regions/{region}/forwardingRules/{forwarding_rule}`
    network: Output only. The consumer network. Format:
      `projects/{project}/locations/{location}/networks/{network}`
    status: Output only. The status of the connected endpoint.
  """

  endpoint = _messages.StringField(1)
  network = _messages.StringField(2)
  status = _messages.StringField(3)


class Server(_messages.Message):
  r"""Message describing Server object

  Enums:
    AccessTypeValueValuesEnum: Required. The access type of the Server.
    StateValueValuesEnum: Output only. The state of the server.

  Messages:
    LabelsValue: Optional. Labels as key value pairs

  Fields:
    accessType: Required. The access type of the Server.
    createTime: Output only. [Output only] Create time stamp
    displayName: Optional. Display name of the Server
    externalConfig: Configuration for external access.
    googleManagedServerCredential: Output only. Credentials of the FTP Server.
    internalConfig: Configuration for internal access.
    labels: Optional. Labels as key value pairs
    name: Identifier. name of resource
    serviceAgent: Output only. Service agent used to access the customer
      bucket.
    state: Output only. The state of the server.
    updateTime: Output only. [Output only] Update time stamp
  """

  class AccessTypeValueValuesEnum(_messages.Enum):
    r"""Required. The access type of the Server.

    Values:
      ACCESS_TYPE_UNSPECIFIED: Default value. This value is unused.
      EXTERNAL: Server is assigned a public IP.
      INTERNAL: Server is assigned an internal IP.
    """
    ACCESS_TYPE_UNSPECIFIED = 0
    EXTERNAL = 1
    INTERNAL = 2

  class StateValueValuesEnum(_messages.Enum):
    r"""Output only. The state of the server.

    Values:
      STATE_UNSPECIFIED: Default value. This value is unused.
      CREATING: Server is being created.
      STARTING: Server is starting.
      ACTIVE: Server is ready to be used.
      STOPPING: Server is stopping.
      STOPPED: Server is stopped.
      DELETING: Server is being deleted.
      ERROR: Server is in error state.
      UPDATING: Server is being updated.
    """
    STATE_UNSPECIFIED = 0
    CREATING = 1
    STARTING = 2
    ACTIVE = 3
    STOPPING = 4
    STOPPED = 5
    DELETING = 6
    ERROR = 7
    UPDATING = 8

  @encoding.MapUnrecognizedFields('additionalProperties')
  class LabelsValue(_messages.Message):
    r"""Optional. Labels as key value pairs

    Messages:
      AdditionalProperty: An additional property for a LabelsValue object.

    Fields:
      additionalProperties: Additional properties of type LabelsValue
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a LabelsValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  accessType = _messages.EnumField('AccessTypeValueValuesEnum', 1)
  createTime = _messages.StringField(2)
  displayName = _messages.StringField(3)
  externalConfig = _messages.MessageField('ExternalServerConfig', 4)
  googleManagedServerCredential = _messages.MessageField('ServerCredential', 5)
  internalConfig = _messages.MessageField('InternalServerConfig', 6)
  labels = _messages.MessageField('LabelsValue', 7)
  name = _messages.StringField(8)
  serviceAgent = _messages.StringField(9)
  state = _messages.EnumField('StateValueValuesEnum', 10)
  updateTime = _messages.StringField(11)


class ServerCredential(_messages.Message):
  r"""Represents credentials of an FTP Server.

  Fields:
    asymmetricAlgorithm: Output only. Asymmetric algorithm used by the public
      key. Possible values (can be expanded in future): - ssh-ed25519
    fingerprint: Output only. The fingerprint is a hash of the public key, and
      is displayed when clients access the server for the first time to verify
      the server's identity.
  """

  asymmetricAlgorithm = _messages.StringField(1)
  fingerprint = _messages.StringField(2)


class StandardQueryParameters(_messages.Message):
  r"""Query parameters accepted by all methods.

  Enums:
    FXgafvValueValuesEnum: V1 error format.
    AltValueValuesEnum: Data format for response.

  Fields:
    f__xgafv: V1 error format.
    access_token: OAuth access token.
    alt: Data format for response.
    callback: JSONP
    fields: Selector specifying which fields to include in a partial response.
    key: API key. Your API key identifies your project and provides you with
      API access, quota, and reports. Required unless you provide an OAuth 2.0
      token.
    oauth_token: OAuth 2.0 token for the current user.
    prettyPrint: Returns response with indentations and line breaks.
    quotaUser: Available to use for quota purposes for server-side
      applications. Can be any arbitrary string assigned to a user, but should
      not exceed 40 characters.
    trace: A tracing token of the form "token:<tokenid>" to include in api
      requests.
    uploadType: Legacy upload protocol for media (e.g. "media", "multipart").
    upload_protocol: Upload protocol for media (e.g. "raw", "multipart").
  """

  class AltValueValuesEnum(_messages.Enum):
    r"""Data format for response.

    Values:
      json: Responses with Content-Type of application/json
      media: Media download with context-dependent Content-Type
      proto: Responses with Content-Type of application/x-protobuf
    """
    json = 0
    media = 1
    proto = 2

  class FXgafvValueValuesEnum(_messages.Enum):
    r"""V1 error format.

    Values:
      _1: v1 error format
      _2: v2 error format
    """
    _1 = 0
    _2 = 1

  f__xgafv = _messages.EnumField('FXgafvValueValuesEnum', 1)
  access_token = _messages.StringField(2)
  alt = _messages.EnumField('AltValueValuesEnum', 3, default='json')
  callback = _messages.StringField(4)
  fields = _messages.StringField(5)
  key = _messages.StringField(6)
  oauth_token = _messages.StringField(7)
  prettyPrint = _messages.BooleanField(8, default=True)
  quotaUser = _messages.StringField(9)
  trace = _messages.StringField(10)
  uploadType = _messages.StringField(11)
  upload_protocol = _messages.StringField(12)


class Status(_messages.Message):
  r"""The `Status` type defines a logical error model that is suitable for
  different programming environments, including REST APIs and RPC APIs. It is
  used by [gRPC](https://github.com/grpc). Each `Status` message contains
  three pieces of data: error code, error message, and error details. You can
  find out more about this error model and how to work with it in the [API
  Design Guide](https://cloud.google.com/apis/design/errors).

  Messages:
    DetailsValueListEntry: A DetailsValueListEntry object.

  Fields:
    code: The status code, which should be an enum value of google.rpc.Code.
    details: A list of messages that carry the error details. There is a
      common set of message types for APIs to use.
    message: A developer-facing error message, which should be in English. Any
      user-facing error message should be localized and sent in the
      google.rpc.Status.details field, or localized by the client.
  """

  @encoding.MapUnrecognizedFields('additionalProperties')
  class DetailsValueListEntry(_messages.Message):
    r"""A DetailsValueListEntry object.

    Messages:
      AdditionalProperty: An additional property for a DetailsValueListEntry
        object.

    Fields:
      additionalProperties: Properties of the object. Contains field @type
        with type URL.
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a DetailsValueListEntry object.

      Fields:
        key: Name of the additional property.
        value: A extra_types.JsonValue attribute.
      """

      key = _messages.StringField(1)
      value = _messages.MessageField('extra_types.JsonValue', 2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  code = _messages.IntegerField(1, variant=_messages.Variant.INT32)
  details = _messages.MessageField('DetailsValueListEntry', 2, repeated=True)
  message = _messages.StringField(3)


class StorageDirectoryMapping(_messages.Message):
  r"""Mapping of backing Cloud Storage path to the directory where the user
  lands in the SFTP server. If directory is not specified, it'll default to
  '/'. Eg 1 - (bucket_name: bucket, bucket_prefix: path1/path2, directory:
  /abc/def/username) The user will land at /abcd/def/username, and the view
  there will match that of /bucket/path1/path2. The user will not be aware of
  Cloud Storage prefix '/bucket/path1' and there will be no such directory in
  the view. Eg 2 - (bucket_name: bucket, bucket_prefix: path1/path2,
  directory: '') The user will land at '/', and the view there will match that
  of /bucket/path1/path2. The user will not be aware of Cloud Storage prefix
  '/bucket/path1/path2' and there will be no such directory in the view.

  Enums:
    PermissionValueValuesEnum: Required. Permission to the bucket.

  Fields:
    bucket: Required. Name of the bucket.
    bucketPrefix: Optional. Prefix inside the bucket.
    directory: Required. Directory where the user lands in the SFTP server.
    permission: Required. Permission to the bucket.
  """

  class PermissionValueValuesEnum(_messages.Enum):
    r"""Required. Permission to the bucket.

    Values:
      PERMISSION_UNSPECIFIED: Permission unspecified.
      READ_ONLY: Read only permission.
      READ_WRITE: Read write permission.
    """
    PERMISSION_UNSPECIFIED = 0
    READ_ONLY = 1
    READ_WRITE = 2

  bucket = _messages.StringField(1)
  bucketPrefix = _messages.StringField(2)
  directory = _messages.StringField(3)
  permission = _messages.EnumField('PermissionValueValuesEnum', 4)


class User(_messages.Message):
  r"""Message describing User object

  Enums:
    StateValueValuesEnum: Output only. Tracks user creation.

  Messages:
    LabelsValue: Optional. Labels as key value pairs

  Fields:
    createTime: Output only. [Output only] Create time stamp
    customerServiceAccount: Required. Service account in customer project
      attached to this SFTP User.
    labels: Optional. Labels as key value pairs
    name: Identifier. User-friendly name via which User will be identified.
      projects/{project}/locations/{location}/servers/{server}/users/{user}
    state: Output only. Tracks user creation.
    storageDirectoryMappings: Required. Mapping of Cloud Storage buckets to
      directories where the user will land in the SFTP server.
    updateTime: Output only. [Output only] Update time stamp
    userCredentials: Required. User credential for the user. The maximum
      number of user credentials is 10.
    username: Output only. [Output only] The username of the user.
  """

  class StateValueValuesEnum(_messages.Enum):
    r"""Output only. Tracks user creation.

    Values:
      STATE_UNSPECIFIED: State unspecified.
      CREATING: User is being created.
      ACTIVE: User is ready to be used.
      ERROR: User creation failed.
      UPDATING: The resource is being updated.
      DELETING: The resource is being deleted.
    """
    STATE_UNSPECIFIED = 0
    CREATING = 1
    ACTIVE = 2
    ERROR = 3
    UPDATING = 4
    DELETING = 5

  @encoding.MapUnrecognizedFields('additionalProperties')
  class LabelsValue(_messages.Message):
    r"""Optional. Labels as key value pairs

    Messages:
      AdditionalProperty: An additional property for a LabelsValue object.

    Fields:
      additionalProperties: Additional properties of type LabelsValue
    """

    class AdditionalProperty(_messages.Message):
      r"""An additional property for a LabelsValue object.

      Fields:
        key: Name of the additional property.
        value: A string attribute.
      """

      key = _messages.StringField(1)
      value = _messages.StringField(2)

    additionalProperties = _messages.MessageField('AdditionalProperty', 1, repeated=True)

  createTime = _messages.StringField(1)
  customerServiceAccount = _messages.StringField(2)
  labels = _messages.MessageField('LabelsValue', 3)
  name = _messages.StringField(4)
  state = _messages.EnumField('StateValueValuesEnum', 5)
  storageDirectoryMappings = _messages.MessageField('StorageDirectoryMapping', 6, repeated=True)
  updateTime = _messages.StringField(7)
  userCredentials = _messages.MessageField('UserCredential', 8, repeated=True)
  username = _messages.StringField(9)


class UserCredential(_messages.Message):
  r"""Message describing UserCredential object

  Enums:
    CredentialTypeValueValuesEnum: Required. Type of credential.

  Fields:
    credentialName: Required. Name of the user credential.
    credentialType: Required. Type of credential.
    sshPublicKeyBody: Optional. SSH public key body in OpenSSH format.
      Example: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQ..."
  """

  class CredentialTypeValueValuesEnum(_messages.Enum):
    r"""Required. Type of credential.

    Values:
      TYPE_UNSPECIFIED: Type unspecified.
      PUBLIC_KEY: Public key credential.
    """
    TYPE_UNSPECIFIED = 0
    PUBLIC_KEY = 1

  credentialName = _messages.StringField(1)
  credentialType = _messages.EnumField('CredentialTypeValueValuesEnum', 2)
  sshPublicKeyBody = _messages.StringField(3)


encoding.AddCustomJsonFieldMapping(
    StandardQueryParameters, 'f__xgafv', '$.xgafv')
encoding.AddCustomJsonEnumMapping(
    StandardQueryParameters.FXgafvValueValuesEnum, '_1', '1')
encoding.AddCustomJsonEnumMapping(
    StandardQueryParameters.FXgafvValueValuesEnum, '_2', '2')
