# -*- coding: utf-8 -*- #
# Copyright 2026 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Utilities for workloadidentity service_agents API."""

from apitools.base.py import exceptions as apitools_exceptions
from googlecloudsdk.api_lib.workloadidentity import util
from googlecloudsdk.core import exceptions


class GenerateServiceAgentsPermissionDeniedException(exceptions.Error):
  pass


def GenerateServiceAgents(parent, release_track):
  """Generate a service agent for a project, folder, or organization, location, and service producer.

  Args:
    parent: The fully qualified resource parent string (e.g.
      projects/123/locations/global/serviceProducers/example.com or
      folders/123/locations/global/serviceProducers/example.com or
      organizations/123/locations/global/serviceProducers/example.com).
    release_track: The release track of the command (e.g. ALPHA, BETA).

  Raises:
    GenerateServiceAgentsPermissionDeniedException: when generating service
    agents fails
      due to permission errors.
    apitools_exceptions.HttpError: Another miscellaneous error with the service.

  Returns:
    The response generated by the API containing the Operation.
  """
  client = util.GetClientInstance(release_track)
  messages = util.GetMessagesModule(release_track)

  request = messages.WorkloadidentityLocationsServiceProducersGenerateServiceAgentsRequest(
      parent=parent,
      generateServiceAgentsRequest=messages.GenerateServiceAgentsRequest(),
  )

  try:
    return client.locations_serviceProducers.GenerateServiceAgents(request)
  except (
      apitools_exceptions.HttpForbiddenError,
      apitools_exceptions.HttpNotFoundError,
  ) as e:
    raise GenerateServiceAgentsPermissionDeniedException(
        f'Permission denied or not found: {e}'
    ) from e
